// examples/wrapper-components/react-vite-js/src/components/RadioButton/RadioButton.jsx
import { useState } from 'react';
import { IfxRadioButton, IfxButton } from '@infineon/infineon-design-system-react';

function RadioButton() {
  const [disabled, setDisabled] = useState(false);
  const [error, setError] = useState(false);
  const [checked, setChecked] = useState(false);

  const [sizeIndex, setSizeIndex] = useState(0);
  const sizes = ['s', 'm'];

  const toggleRadioBtnDisabled = () => {
    setDisabled((prev) => !prev);
  };

  const toggleRadioBtnError = () => {
    setError((prev) => !prev);
  };

  const toggleRadioBtnChecked = () => {
    setChecked((prev) => !prev);
  };

  const toggleRadioBtnSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  };

  return (
    <div>
      <h2>Radio Button</h2>

      <IfxRadioButton
        size={sizes[sizeIndex]}
        name="radio-button"
        value="radio"
        checked={checked}
        disabled={disabled}
        error={error}
      >
        Text
      </IfxRadioButton>

      <br />
      <br />
      <h3 style={{ textDecoration: 'underline' }}>Controls</h3>
      <IfxButton variant="secondary" onClick={toggleRadioBtnDisabled}>Toggle Disabled</IfxButton>
      <IfxButton variant="secondary" onClick={toggleRadioBtnError}>Toggle Error</IfxButton>
      <IfxButton variant="secondary" onClick={toggleRadioBtnChecked}>Toggle Checked</IfxButton>
      <IfxButton variant="secondary" onClick={toggleRadioBtnSize}>Toggle Size</IfxButton>
      <br />
      <br />
      <span><b>Disabled:</b> {String(disabled)}</span><br />
      <span><b>Error:</b> {String(error)}</span><br />
      <span><b>Checked:</b> {String(checked)}</span><br />
      <span><b>Size:</b> {sizes[sizeIndex]}</span><br />
    </div>
  );
}

export default RadioButton;

// packages/components-angular/projects/my-app/src/app/components/radio-button/radio-button.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-radio-button',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './radio-button.component.html',
  styleUrl: './radio-button.component.scss'
})
export class RadioButtonComponent {
  error = false;
  disabled = false;

  size = "s";
  sizes = ["s", "m"];
  sizeIndex = 0;

  toggleDisabled() {
    this.disabled = !this.disabled;
  }
  
  toggleError() {
    this.error = !this.error;
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }

}
<h2>Radio Button</h2>
<ifx-radio-button [size]="radioBtnSize" name="radio-button" value="radio" [checked]="radioBtnChecked" [disabled]="radioBtnDisabled" [error]="radioBtnError">Text</ifx-radio-button>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleRadioBtnDisabled()">Toggle Disabled</ifx-button>
<ifx-button variant="secondary" (click)="toggleRadioBtnError()">Toggle Error</ifx-button>
<ifx-button variant="secondary" (click)="toggleRadioBtnChecked()">Toggle Checked</ifx-button>
<ifx-button variant="secondary" (click)="toggleRadioBtnSize()">Toggle Size</ifx-button>
<br>
<br>
<span><b>Disabled:</b> {{ radioBtnDisabled }} </span><br>
<span><b>Error:</b> {{ radioBtnError }} </span><br>
<span><b>Checked:</b> {{ radioBtnChecked }}</span><br>
<span><b>Size:</b> {{ radioBtnSize }}</span><br>
