// examples/wrapper-components/react-typescript/src/components/ProgressBar/ProgressBar.tsx
import React, { useState } from 'react';
import { IfxProgressBar, IfxButton } from '@infineon/infineon-design-system-react';

function ProgressBar() {
  const [progressValue, setProgressValue] = useState(25);

  // Define your methods here
  const updateProgressOnClick = () => {
    setProgressValue((currentValue) => {
      console.log("updating progress-bar value ", progressValue)
      if (currentValue < 100) {
        return currentValue + 10;
      } else {
        return 10;
      }
    });
  };

  return (
    <div>
      <IfxProgressBar value={progressValue} showLabel={true}></IfxProgressBar>
      <IfxButton onClick={updateProgressOnClick} variant="outline" href="" target="_blank" color="primary" size="s"
        disabled={false} icon={false}>
        Update Progress
      </IfxButton>
    </div >
  );
}

export default ProgressBar;

// examples/stencil-components/vue3-vite/src/components/ProgressBar.vue


<template>
  <div class="app">
    <h2>Progress bar</h2>
    <ifx-progress-bar value="50" size="m" show-label="true"></ifx-progress-bar>
    <ifx-progress-bar :value="progressValue" size="m" show-label="true"></ifx-progress-bar>

    <div>
      <ifx-button variant="solid" icon="" position="left" href="" target="_blank" color="primary" size="m"
        disabled="false" @click="updateProgressOnClick">
        Update progress
      </ifx-button>
    </div>

    <br />

  </div>
</template>

<script setup>
import { ref } from 'vue'

const progressValue = ref("10");


function updateProgressOnClick() {
  console.log("val", progressValue.value)
  progressValue.value < 100 ? progressValue.value += 10 : progressValue.value = 10;
}


</script>

<style scoped>
.app {
  text-align: center;
  flex-direction: column;
  display: flex;
  align-items: center;
}
</style>
