// examples/vue-example/src/generated/IfxSearchFieldExample.vue
<script setup lang="ts">

import { IfxSearchField } from '@infineon/infineon-design-system-vue';

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleSuggestionRequested = (event: CustomEvent) => {
  console.log('ifxSuggestionRequested:', event);
  // Add your handler logic here
};

const handleSuggestionSelected = (event: CustomEvent) => {
  console.log('ifxSuggestionSelected:', event);
  // Add your handler logic here
};

const handleFocus = (event: CustomEvent) => {
  console.log('ifxFocus:', event);
  // Add your handler logic here
};

const handleBlur = (event: CustomEvent) => {
  console.log('ifxBlur:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleSuggestionRequested = (event: CustomEvent) => {
  console.log('ifxSuggestionRequested:', event);
  // Add your handler logic here
};

const handleSuggestionSelected = (event: CustomEvent) => {
  console.log('ifxSuggestionSelected:', event);
  // Add your handler logic here
};

const handleFocus = (event: CustomEvent) => {
  console.log('ifxFocus:', event);
  // Add your handler logic here
};

const handleBlur = (event: CustomEvent) => {
  console.log('ifxBlur:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-search-field
      size="m"
      :show-delete-icon="true"
      :show-suggestions="false"
      :enable-history="true"
      :max-suggestions=10
      :max-history-items=5
      history-key="ifx-search-history"
      history-header-text="Recent Searches"
      value=""
      autocomplete="on"
      placeholder="Search..."
      aria-label-text="Search field"
      delete-icon-aria-label="Clear search"
      history-delete-aria-label="Remove from history"
      dropdown-aria-label="Search suggestions and history"
      suggestion-aria-label="Search suggestion"
      history-item-aria-label="Search history item"
      :disabled="false"
      @ifxInput="handleInput"
      @ifxSuggestionRequested="handleSuggestionRequested"
      @ifxSuggestionSelected="handleSuggestionSelected"
      @ifxFocus="handleFocus"
      @ifxBlur="handleBlur" />
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-search-field
      size="m"
      :show-delete-icon="true"
      :show-suggestions="false"
      :enable-history="true"
      :max-suggestions=10
      :max-history-items=5
      history-key="ifx-search-history"
      history-header-text="Recent Searches"
      value=""
      autocomplete="on"
      placeholder="Search..."
      aria-label-text="Search field"
      delete-icon-aria-label="Clear search"
      history-delete-aria-label="Remove from history"
      dropdown-aria-label="Search suggestions and history"
      suggestion-aria-label="Search suggestion"
      history-item-aria-label="Search history item"
      :disabled="false"
      @ifxInput="handleInput"
      @ifxSuggestionRequested="handleSuggestionRequested"
      @ifxSuggestionSelected="handleSuggestionSelected"
      @ifxFocus="handleFocus"
      @ifxBlur="handleBlur" />
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-standalone-example/src/app/generated/ifx-search-field-example/ifx-search-field-example.ts
import { IfxSearchField } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-search-field-example',
  imports: [ IfxSearchField ],
  templateUrl: './ifx-search-field-example.html',
  styleUrl: './ifx-search-field-example.scss'
})
export class IfxSearchFieldExample {
  protected readonly tsCode = `import { IfxSearchField } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-search-field-example&#039;,
  imports: [ IfxSearchField ],
  templateUrl: &#039;./ifx-search-field-example.html&#039;,
  styleUrl: &#039;./ifx-search-field-example.scss&#039;
})
export class IfxSearchFieldExample {
  protected handleInput(event: any) {
    console.log(&#039;ifxInput:&#039;, event.detail);
    // Add your handler logic here
  }

  protected handleSuggestionRequested(event: any) {
    console.log(&#039;ifxSuggestionRequested:&#039;, event.detail);
    // Add your handler logic here
  }

  protected handleSuggestionSelected(event: any) {
    console.log(&#039;ifxSuggestionSelected:&#039;, event.detail);
    // Add your handler logic here
  }

  protected handleFocus(event: any) {
    console.log(&#039;ifxFocus:&#039;, event.detail);
    // Add your handler logic here
  }

  protected handleBlur(event: any) {
    console.log(&#039;ifxBlur:&#039;, event.detail);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-search-field
    size=&quot;m&quot;
    disabled=&quot;false&quot;
    show-delete-icon=&quot;true&quot;
    show-suggestions=&quot;false&quot;
    enable-history=&quot;true&quot;
    max-suggestions=&quot;10&quot;
    max-history-items=&quot;5&quot;
    history-key=&quot;ifx-search-history&quot;
    history-header-text=&quot;Recent Searches&quot;
    value=&quot;true&quot;
    autocomplete=&quot;on&quot;
    placeholder=&quot;Search...&quot;
    aria-label=&quot;Search field&quot;
    delete-icon-aria-label=&quot;Clear search&quot;
    history-delete-aria-label=&quot;Remove from history&quot;
    dropdown-aria-label=&quot;Search suggestions and history&quot;
    suggestion-aria-label=&quot;Search suggestion&quot;
    history-item-aria-label=&quot;Search history item&quot;
    (ifxInput)=&quot;handleInput(\$event)&quot;
    (ifxSuggestionRequested)=&quot;handleSuggestionRequested(\$event)&quot;
    (ifxSuggestionSelected)=&quot;handleSuggestionSelected(\$event)&quot;
    (ifxFocus)=&quot;handleFocus(\$event)&quot;
    (ifxBlur)=&quot;handleBlur(\$event)&quot;&gt;&lt;/ifx-search-field&gt;`;

  protected handleInput(event: any) {
    console.log('ifxInput:', event.detail);
    // Add your handler logic here
  }

  protected handleSuggestionRequested(event: any) {
    console.log('ifxSuggestionRequested:', event.detail);
    // Add your handler logic here
  }

  protected handleSuggestionSelected(event: any) {
    console.log('ifxSuggestionSelected:', event.detail);
    // Add your handler logic here
  }

  protected handleFocus(event: any) {
    console.log('ifxFocus:', event.detail);
    // Add your handler logic here
  }

  protected handleBlur(event: any) {
    console.log('ifxBlur:', event.detail);
    // Add your handler logic here
  }
}
