// examples/wrapper-components/react-vite-js/src/components/Pagination/Pagination.jsx
import { useState } from 'react';
import { IfxPagination, IfxButton } from '@infineon/infineon-design-system-react';

export default function App() {
  const [showItemsPerPage, setShowItemsPerPage] = useState(true);

  const toggleShowItemsPerPage = () => {
    setShowItemsPerPage(prevShow => !prevShow);
  }

  return (
    <div className="component">
      <h2>Pagination</h2>
      <IfxPagination
        total="50"
        current-page="1"
        showItemsPerPage={showItemsPerPage}
        items-per-page='[{"value":"10","selected":true}, {"value":"20","selected":false}, {"value":"30","selected":false}]'>
      </IfxPagination>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleShowItemsPerPage}>Toggle Show Items per Page</IfxButton>
      </div>
      <br />
      
      <div class="state">
        <div><b>Show Items per Page:</b> {String(showItemsPerPage)} </div>
      </div>
    </div>
  );
}

// packages/components-angular/projects/my-app/src/app/components/pagination/pagination.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './pagination.component.html',
  styleUrl: './pagination.component.scss'
})
export class PaginationComponent {

}

<h2>Pagination</h2>
<ifx-pagination total="100" current-page="1" [showItemsPerPage]="itemsPerPage"
  items-per-page='[{"value":"10","selected":true}, {"value":"20","selected":false}, {"value":"30","selected":false}]'></ifx-pagination>
<br>
<br>

<h3 class="controls-title">Controls</h3>
<div class="controls">
  <ifx-button variant="secondary" (click)="toggleShowItemsPerPage()">Toggle Show Items per Page</ifx-button>
</div>
<br>

<div class="state">
  <div><b>Show Items per Page:</b> {{ itemsPerPage }} </div>
</div><br />
