// examples/vue-example/src/generated/IfxSpinnerExample.vue
<script setup lang="ts">

import { IfxButton, IfxSpinner } from '@infineon/infineon-design-system-vue';

import { computed, ref } from 'vue';

const sizeOptions = ["s","m"];
const sizeIndex = ref(1);
const variantOptions = ["default","brand"];
const variantIndex = ref(0);
const inverted = ref(false);

const toggleSize = () => (sizeIndex.value = (sizeIndex.value + 1) % sizeOptions.length);
const toggleVariant = () => (variantIndex.value = (variantIndex.value + 1) % variantOptions.length);
const toggleInverted = () => (inverted.value = !inverted.value);

const controlledProps = computed(() => ({
  "size": sizeOptions[sizeIndex.value],
  "variant": variantOptions[variantIndex.value],
  "inverted": inverted.value,
}));

const formatAttrValueForCode = (value: unknown): string => {
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  if (value === null) return "null";
  if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
    return JSON.stringify(value);
  }
  return String(value).replace(/"/g, '&quot;');
};

const controlledAttrsCode = [
  ["size", controlledProps.value["size"]],
  ["variant", controlledProps.value["variant"]],
  ["inverted", controlledProps.value["inverted"]],
]
	.map(([name, value]) => '      ' + String(name) + '="' + formatAttrValueForCode(value) + '"')
  .join("\n");

const codeString = `<script setup lang="ts">
${'</'}script>

<template>
  <div>
    <ifx-spinner
      aria-label=""
      __CONTROLLED_ATTRS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_ATTRS__", controlledAttrsCode);

</script>

<template>
  <div>
    <ifx-spinner
      aria-label=""
      v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <IfxButton variant="secondary" @click="toggleSize">Toggle Size</IfxButton>
      <IfxButton variant="secondary" @click="toggleVariant">Toggle Variant</IfxButton>
      <IfxButton variant="secondary" @click="toggleInverted">Toggle Inverted</IfxButton>
    </div>

    <div class="state">
        <div><b>size:</b> {{ String(sizeOptions[sizeIndex.value]) }}</div>
        <div><b>variant:</b> {{ String(variantOptions[variantIndex.value]) }}</div>
        <div><b>inverted:</b> {{ String(inverted.value) }}</div>
    </div>

    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-standalone-example/src/app/generated/ifx-spinner-example/ifx-spinner-example.ts
import { IfxButton, IfxSpinner } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-spinner-example',
  imports: [ IfxButton, IfxSpinner ],
  templateUrl: './ifx-spinner-example.html',
	styleUrl: './ifx-spinner-example.scss'
})
export class IfxSpinnerExample {
  protected readonly tsCode = `import { IfxButton, IfxSpinner } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-spinner-example&#039;,
  imports: [ IfxButton, IfxSpinner ],
  templateUrl: &#039;./ifx-spinner-example.html&#039;,
	styleUrl: &#039;./ifx-spinner-example.scss&#039;
})
export class IfxSpinnerExample {}`;
  protected get htmlCode(): string {
    const controlledAttrs = [
      ["size", this.controlledProps["size"]],
      ["variant", this.controlledProps["variant"]],
      ["inverted", this.controlledProps["inverted"]],
    ]
			.map(([name, value]) => '    ' + String(name) + '=&quot;' + String(value) + '&quot;')
      .join("\n");

    return `  &lt;ifx-spinner
    aria-label=&quot;true&quot;
    __CONTROLLED_ATTRS__&gt;&lt;/ifx-spinner&gt;`.replace("__CONTROLLED_ATTRS__", controlledAttrs);
  }
  protected readonly sizeOptions = ["s","m"];
  protected sizeIndex = 1;
  protected readonly variantOptions = ["default","brand"];
  protected variantIndex = 0;
  protected inverted = false;

  protected toggleSize() { this.sizeIndex = (this.sizeIndex + 1) % this.sizeOptions.length; }
  protected toggleVariant() { this.variantIndex = (this.variantIndex + 1) % this.variantOptions.length; }
  protected toggleInverted() { this.inverted = !this.inverted; }

  protected get controlledProps(): Record<string, unknown> {
    return {
      "size": this.sizeOptions[this.sizeIndex],
      "variant": this.variantOptions[this.variantIndex],
      "inverted": this.inverted,
    };
  }
}
