// packages/components-angular/projects/my-app/src/app/components/alert/alert.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-alert',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './alert.component.html',
  styleUrl: './alert.component.scss'
})
export class AlertComponent {
  variant = "primary";
  variants = ["primary", "success", "danger", "warning"];
  variantIndex = 0;

  closable = true;

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }

  toggleClosable() {
    this.closable = !this.closable;
  }

}
<h2>Alert</h2>
<ifx-alert 
    aria-live="assertive" 
    [variant]="alertVariant" 
    icon="c-info-16" 
    [closable]="alertClosable">
    Attention! This is an alert message — check it out!
</ifx-alert>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleAlertVariant()">Toggle Variant</ifx-button>
<ifx-button variant="secondary" (click)="toggleAlertClosable()">Toggle Closable State</ifx-button>
<br>
<br>
<span><b>Variant:</b> {{ alertVariant }} </span>
<br>
<span><b>Closable State:</b> {{ alertClosable }} </span><br>

// examples/wrapper-components/vue-javascript/src/components/Alert.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["primary", "success", "danger", "warning"] as const;

const variantIndex = ref(0);
const closable = ref(true);

const variant = computed(() => variants[variantIndex.value]);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleClosable() {
  closable.value = !closable.value;
}
</script>

<template>
  <div class="component">
    <h2>Alert</h2>

    <ifx-alert aria-live="assertive" icon="c-info-16" :variant="variant" :closable="closable">
      Attention! This is an alert message — check it out!
    </ifx-alert>
    <br>
    <br>
    <h3 class="controls-title">Controls</h3>
    <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
    <ifx-button variant="secondary" @click="toggleClosable">Toggle Closable State</ifx-button>
    <br>
    <br>
    <div class="state">
      <div><b>Variant:</b> {{ variant }}</div>
      <div><b>Closable:</b> {{ String(closable) }}</div>
    </div>
  </div>
</template>
