// examples/wrapper-components/react-vite-js/src/components/Alert/Alert.jsx
import { useState } from 'react';
import { IfxAlert, IfxButton } from '@infineon/infineon-design-system-react';

function Alert() {

  const [closable, setClosable] = useState(true);

  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ["primary", "success", "danger", "warning"];

  const toggleClosable = () => {
    setClosable(prevClosable => !prevClosable);
  }

  const toggleVariant = () => {
    setVariantIndex((index) => (index + 1) % variants.length);
  }

  return (
    <div className="component">
      <h2>Alert</h2>
      <IfxAlert aria-live="assertive" variant={variants[variantIndex]} icon="c-info-16" closable={closable}>Attention! This is an alert message — check it out!</IfxAlert>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
        <IfxButton variant="secondary" onClick={toggleClosable}>Toggle Closable State</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Variant:</b> {variants[variantIndex]}</div>
        <div><b>Closable:</b> {String(closable)}</div>
      </div>
    </div>
  )
}

export default Alert;

// examples/wrapper-components/vue-javascript/src/components/Alert.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["primary", "success", "danger", "warning"] as const;

const variantIndex = ref(0);
const closable = ref(true);

const variant = computed(() => variants[variantIndex.value]);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleClosable() {
  closable.value = !closable.value;
}
</script>

<template>
  <div class="component">
    <h2>Alert</h2>

    <ifx-alert aria-live="assertive" icon="c-info-16" :variant="variant" :closable="closable">
      Attention! This is an alert message — check it out!
    </ifx-alert>
    <br>
    <br>
    <h3 class="controls-title">Controls</h3>
    <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
    <ifx-button variant="secondary" @click="toggleClosable">Toggle Closable State</ifx-button>
    <br>
    <br>
    <div class="state">
      <div><b>Variant:</b> {{ variant }}</div>
      <div><b>Closable:</b> {{ String(closable) }}</div>
    </div>
  </div>
</template>
