// examples/wrapper-components/react-vite-js/src/components/BasicTable/BasicTable.jsx
import  { useState } from 'react';
import { IfxBasicTable } from '@infineon/infineon-design-system-react';

function BasicTable() {
  const [rows] = useState([
    { make: 'Toyota', model: 'Celica', price: 35000, age: 10 },
    { make: 'Ford', model: 'Mondeo', price: 32000, age: 12 },
    { make: 'Porsche', model: 'Boxster', price: 72000 }
    ]
  )

  const [cols] = useState([
    { headerName: 'Make', field: 'make', sortable: true, sort: 'desc', unSortIcon: true },
    { headerName: 'Model', field: 'model', sortable: true, unSortIcon: true },
    { headerName: 'Price', field: 'price' },
    { headerName: 'Age', field: 'age' }
  ]
  )

  return (
    <div>
      <h2>Basic Table</h2>
      <IfxBasicTable id='myTable' row-height='default'
        cols={JSON.stringify(cols)}
        rows={JSON.stringify(rows)}
        table-height='auto'>
      </IfxBasicTable>
    </div>

  );
}

export default BasicTable;

// examples/wrapper-components/vue-javascript/src/components/BasicTable.vue


<template>
  <div class="component">
    <h2>Table (Basic)</h2>
    <ifx-basic-table row-height='default'
      cols='[{"headerName":"Make","field":"make","sortable":true,"sort":"desc","unSortIcon":true},{"headerName":"Model","field":"model","sortable":true,"unSortIcon":true},{"headerName":"Price","field":"price"},{"headerName":"Age","field":"age"}]'
      rows='[{"make":"Toyota","model":"Celica","price":35000,"age":10},{"make":"Ford","model":"Mondeo","price":32000,"age":12},{"make":"Porsche","model":"Boxster","price":72000}]'
      table-height='auto'>
    </ifx-basic-table>
    <br />
  </div>
</template>

<script setup>



</script>
