// examples/wrapper-components/react-javascript/src/components/Card/Card.js
import React from 'react';
import { IfxCard, IfxLink } from '@infineon/infineon-design-system-react';
import { IfxCardHeadline } from '@infineon/infineon-design-system-react';
import { IfxCardOverline } from '@infineon/infineon-design-system-react';
import { IfxCardText } from '@infineon/infineon-design-system-react';

function Card() {
    return (
        <div>
        <IfxCard img src="https://upload.wikimedia.org/wikipedia/commons/e/e4/Latte_and_dark_coffee.jpg" alt="" slot="img" direction='horizontal'>
        <IfxCardOverline slot="overline">
            Overline
            </IfxCardOverline>
        <IfxCardHeadline slot="headline">
            Headline
            </IfxCardHeadline>
        <IfxCardText slot="text">
            Some quick example text to build on the card title and make up the bulk of the card's content.
            </IfxCardText>
        <IfxLink href="" target="_blank" icon="true" slot="btn" underline="false" position="right">Link</IfxLink>
        </IfxCard>

        <IfxCard img src="https://upload.wikimedia.org/wikipedia/commons/e/e4/Latte_and_dark_coffee.jpg" alt="" slot="img" alignment='right'>
        <IfxCardOverline slot="overline">
            Overline
            </IfxCardOverline>
        <IfxCardHeadline slot="headline">
            Headline
            </IfxCardHeadline>
        <IfxCardText slot="text">
            Some quick example text to build on the card title and make up the bulk of the card's content.
            </IfxCardText>
        <IfxLink href="" target="_blank" icon="true" slot="btn" underline="false" position="right">Link</IfxLink>
        </IfxCard>

        <div>
            text for card component
        </div>
        </div>
    );
}

export default Card;

// examples/wrapper-components/vue-javascript/src/components/Card.vue
<template>
  <div class="app">
      <ifx-card direction="vertical" href="http://google.com" target="_blank">
    <ifx-card-image position="right" src="https://upload.wikimedia.org/wikipedia/commons/e/e4/Latte_and_dark_coffee.jpg" alt="" slot="img"></ifx-card-image>
    <ifx-card-overline>Overline</ifx-card-overline>
    <ifx-card-headline>Headline</ifx-card-headline>
     <ifx-card-text>
      Some quick example text to build on the card title and make up the bulk of the card's content
    </ifx-card-text>
      <ifx-link href="" target="_blank" underline="false">
        <ifx-icon icon="calendar16"></ifx-icon>
        Link
      </ifx-link>
  </ifx-card>
  </div>
</template>
