// examples/wrapper-components/react-vite-js/src/components/CheckboxGroup/CheckboxGroup.jsx
import { IfxCheckboxGroup, IfxCheckbox } from '@infineon/infineon-design-system-react';

function CheckboxGroup() {

  return (
    <div>
      <IfxCheckboxGroup alignment="vertical" show-group-label="true" group-label-text="Group Label" show-caption="true" caption-text="Caption text, description, error notification" show-caption-icon="true">
          <IfxCheckbox value="0" error={false} disabled={false} checked={false} size="m" indeterminate={false}>Option 0</IfxCheckbox>
          <IfxCheckbox value="1" disabled={false} checked={false} size="m" indeterminate={false} error={false}>Option 1</IfxCheckbox>
          <IfxCheckbox value="2" disabled={false} checked={false} size="m" indeterminate={false} error={false}>Option 2</IfxCheckbox>
          <IfxCheckbox value="3" disabled={false} checked={false} size="m" indeterminate={false} error={false}>Option 3</IfxCheckbox>
      </IfxCheckboxGroup>
    </div>
  );
}

export default CheckboxGroup;

// examples/wrapper-components/vue-javascript/src/components/CheckboxGroup.vue

<template>
  <div>
    <h2>Checkbox group</h2>
    <ifx-checkbox-group alignment="vertical" show-group-label="false" group-label-text="Group Label" show-caption="false" caption-text="Caption text, description, error notification" show-caption-icon="false">
        <ifx-checkbox value="0" disabled="false" checked="false" size="m" indeterminate="false" error="false">Option 0</ifx-checkbox>
        <ifx-checkbox value="1" size="m">Option 1</ifx-checkbox>
        <ifx-checkbox value="2" size="m">Option 2</ifx-checkbox>
    </ifx-checkbox-group>
    <br />
    <br />
  </div>
</template>

<script setup>


</script>
