// examples/wrapper-components/react-vite-js/src/components/DatePicker/DatePicker.jsx
import { useState } from 'react';
import { IfxDatePicker, IfxButton } from '@infineon/infineon-design-system-react';

function DatePicker() {
  const [success, setSuccess] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [error, setError] = useState(false);
  const [required, setRequired] = useState(false);

  const [sizeIndex, setSizeIndex] = useState(0);
  const sizes = ["s", "l"];

  const [typeIndex, setTypeIndex] = useState(0);
  const types = ["date", "datetime-local"];

  const toggleSuccess = () => {
    setSuccess(prevSuccess => !prevSuccess);
  }

  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  const toggleError = () => {
    setError(prevError => !prevError);
  }

  const toggleRequired = () => {
    setRequired(prevRequired => !prevRequired);
  }

  const toggleSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  }

  const toggleType = () => {
    setTypeIndex((index) => (index + 1) % types.length);
  }

  return (
    <div className="component">
      <h2>Date Picker</h2>
      <IfxDatePicker name="date-picker" error={error} disabled={disabled} size={sizes[sizeIndex]} success={success} value="" max="" min="" label="Label Text" caption="Caption text, description, error notification." aria-label="Date Picker" required={required} autocomplete="on" type={types[typeIndex]}></IfxDatePicker>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleSuccess}>Toggle Success</IfxButton>
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={toggleError}>Toggle Error</IfxButton>
        <IfxButton variant="secondary" onClick={toggleRequired}>Toggle Required</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={toggleType}>Toggle Type</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Success:</b> {String(success)}</div>
        <div><b>Disabled:</b> {String(disabled)}</div>
        <div><b>Error:</b> {String(error)}</div>
        <div><b>Required:</b> {String(required)}</div>
        <div><b>Size:</b> {sizes[sizeIndex]}</div>
        <div><b>Type:</b> {types[typeIndex]}</div>
      </div >
    </div>
  );
}

export default DatePicker;

// examples/wrapper-components/vue-javascript/src/components/DatePicker.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const types = ["date", "datetime-local"];
const typeIndex = ref(0);
const type = computed(() => types[typeIndex.value]);

const sizes = ["s", "l"];
const sizeIndex = ref(0);
const size = computed(() => sizes[sizeIndex.value]);

const success = ref(false);
const disabled = ref(false);
const error = ref(false);
const required = ref(false);

function toggleType() {
  typeIndex.value = (typeIndex.value + 1) % types.length;
}

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleSuccess() {
  success.value = !success.value;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleError() {
  error.value = !error.value;
}

function toggleRequired() {
  required.value = !required.value;
}

</script>

<template>
  <div class="component">
    <h2>Date Picker</h2>
    <ifx-date-picker name="date-picker" :error="error" :disabled="disabled" :size="size" :success="success" value=""
      max="" min="" label="Label Text" caption="Caption text, description, error notification." arialabel="Date Picker"
      :required="required" autocomplete="on" :type="type">
    </ifx-date-picker>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleSuccess">Toggle Success</ifx-button>
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleError">Toggle Error</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleType">Toggle Type</ifx-button>
      <ifx-button variant="secondary" @click="toggleRequired">Toggle Required</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Success:</b> {{ String(success) }}</div>
      <div><b>Disabled:</b> {{ String(disabled) }}</div>
      <div><b>Error:</b> {{ String(error) }}</div>
      <div><b>Size:</b> {{ size }}</div>
      <div><b>Type:</b> {{ type }}</div>
      <div><b>Required:</b> {{ String(required) }}</div>
    </div>
  </div>
</template>
