// packages/components-angular/projects/my-app/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {

}

<h2>Footer</h2>
<br>
<h3>Small Footer</h3>
<ifx-footer copyright-text="© 1999 - 2024 Infineon Technologies AG">
    <div slot="info">
      <ifx-link variant="menu" aria-label="Go to Homepage" href="http://infineon.com" target="_blank">Terms</ifx-link>
      <ifx-link variant="menu" href="https://yourwebsite.com/imprint" target="_blank">Imprint</ifx-link>
      <ifx-link variant="menu" href="https://yourwebsite.com/privacy-policy" target="_blank">Privacy policy</ifx-link>
      <ifx-link variant="menu" href="https://yourwebsite.com/glossary" target="_blank">Glossary</ifx-link>
    </div>
  </ifx-footer>
<br>
<h3>Medium Footer</h3>
<ifx-footer copyright-text="© 1999 - 2024 Infineon Technologies AG">
    <div slot="socials">
    <ifx-link variant="title" href="http://infineon.com" aria-label="Go to Homepage">
        <ifx-icon icon=home-16></ifx-icon>
      </ifx-link>
      <ifx-link variant="title" href="http://facebook.com/infineon" aria-label="Follow us on Facebook">
        <ifx-icon icon="facebook"></ifx-icon>
      </ifx-link>
      <ifx-link variant="title" href="http://youtube.com/infineon" aria-label="Follow us on Youtube">
        <ifx-icon icon="youtube"></ifx-icon>
      </ifx-link>
      <ifx-link variant="title" href="http://instagram.com/infineon" aria-label="Follow us on Instagram">
        <ifx-icon icon="instagram"></ifx-icon>
      </ifx-link>
      <ifx-link variant="title" href="http://linkedin.com/infineon" aria-label="Follow us on LinkedIn">
        <ifx-icon icon="linkedin"></ifx-icon>
      </ifx-link>
      <ifx-link variant="title" href="http://xing.com/infineon" aria-label="Follow us on Xing">
        <ifx-icon icon="xing"></ifx-icon>
      </ifx-link>
    </div>
    <div slot="info">
      <ifx-link variant="menu" href="https://yourwebsite.com/terms" target="_blank">Terms</ifx-link>
      <ifx-link variant="menu" href="https://yourwebsite.com/imprint" target="_blank">Imprint</ifx-link>
      <ifx-link variant="menu" href="https://yourwebsite.com/privacy-policy" target="_blank">Privacy policy</ifx-link>
      <ifx-link variant="menu" href="https://yourwebsite.com/glossary" target="_blank">Glossary</ifx-link>
    </div>
  </ifx-footer>
<br>
<h3>Large Footer</h3>
<ifx-footer variant="large" terms-url="https://yourwebsite.com/terms">
    <ifx-footer-column slot="col">
      <h5 slot="title">Title</h5>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
    </ifx-footer-column>
    <ifx-footer-column slot="col">
      <h5 slot="title">Title</h5>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
    </ifx-footer-column>
    <ifx-footer-column slot="col">
      <h5 slot="title">Title</h5>
      <ifx-link bold="false" slot="link" href="https://google.com" underline="false">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link" href="https://google.com">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link" href="https://google.com">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link" href="https://google.com">Footer Link</ifx-link>
    </ifx-footer-column>
    <ifx-footer-column slot="col">
      <h5 slot="title">Title</h5>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      <ifx-link bold="false" slot="link">Footer Link</ifx-link>
    </ifx-footer-column>
    <div slot="socials">
      <ifx-link href="http://facebook.com/infineon">
        <ifx-icon icon="c-info-16"></ifx-icon>
      </ifx-link>
      <ifx-link href="http://youtube.com/infineon">
        <ifx-icon icon="calendar-16"></ifx-icon>
      </ifx-link>
      <ifx-link href="http://instagram.com/infineon">
        <ifx-icon icon="fileexe16"></ifx-icon>
      </ifx-link>
      <ifx-link href="http://linkedin.com/infineon">
        <ifx-icon icon="filegif16"></ifx-icon>
      </ifx-link>
      <ifx-link href="http://twitter.com/infineon">
        <ifx-icon icon="filehtml16"></ifx-icon>
      </ifx-link>
      <ifx-link href="http://xing.com/infineon">
        <ifx-icon icon="filejpg16"></ifx-icon>
      </ifx-link>
    </div>
    <div slot="info">
      <ifx-link variant="menu" href="https://yourwebsite.com/terms" target="_blank">Terms</ifx-link>
    </div>
  </ifx-footer>

// examples/wrapper-components/vue-javascript/src/components/Footer.vue
<template>
  <div class="component">
    <h2>Footer</h2>
    <br>
    <h3>Small Footer</h3>
    <ifx-footer copyright-text="© 1999 - 2024 Infineon Technologies AG">
      <div slot="info">
        <ifx-link variant="menu" aria-label="Go to Homepage" href="http://infineon.com" target="_blank">Terms</ifx-link>
        <ifx-link variant="menu" href="https://yourwebsite.com/imprint" target="_blank">Imprint</ifx-link>
        <ifx-link variant="menu" href="https://yourwebsite.com/privacy-policy" target="_blank">Privacy policy</ifx-link>
        <ifx-link variant="menu" href="https://yourwebsite.com/glossary" target="_blank">Glossary</ifx-link>
      </div>
    </ifx-footer>
    <br>
    <h3>Medium Footer</h3>
    <ifx-footer copyright-text="© 1999 - 2024 Infineon Technologies AG">
      <div slot="socials">
        <ifx-link variant="title" href="http://infineon.com" aria-label="Go to Homepage">
          <ifx-icon icon=home-16></ifx-icon>
        </ifx-link>
        <ifx-link variant="title" href="http://facebook.com/infineon" aria-label="Follow us on Facebook">
          <ifx-icon icon="facebook"></ifx-icon>
        </ifx-link>
        <ifx-link variant="title" href="http://youtube.com/infineon" aria-label="Follow us on Youtube">
          <ifx-icon icon="youtube"></ifx-icon>
        </ifx-link>
        <ifx-link variant="title" href="http://instagram.com/infineon" aria-label="Follow us on Instagram">
          <ifx-icon icon="instagram"></ifx-icon>
        </ifx-link>
        <ifx-link variant="title" href="http://linkedin.com/infineon" aria-label="Follow us on LinkedIn">
          <ifx-icon icon="linkedin"></ifx-icon>
        </ifx-link>
        <ifx-link variant="title" href="http://xing.com/infineon" aria-label="Follow us on Xing">
          <ifx-icon icon="xing"></ifx-icon>
        </ifx-link>
      </div>
      <div slot="info">
        <ifx-link variant="menu" href="https://yourwebsite.com/terms" target="_blank">Terms</ifx-link>
        <ifx-link variant="menu" href="https://yourwebsite.com/imprint" target="_blank">Imprint</ifx-link>
        <ifx-link variant="menu" href="https://yourwebsite.com/privacy-policy" target="_blank">Privacy policy</ifx-link>
        <ifx-link variant="menu" href="https://yourwebsite.com/glossary" target="_blank">Glossary</ifx-link>
      </div>
    </ifx-footer>
    <br>
    <h3>Large Footer</h3>
    <ifx-footer variant="large" terms-url="https://yourwebsite.com/terms">
      <ifx-footer-column slot="col">
        <h5 slot="title">Title</h5>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      </ifx-footer-column>
      <ifx-footer-column slot="col">
        <h5 slot="title">Title</h5>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      </ifx-footer-column>
      <ifx-footer-column slot="col">
        <h5 slot="title">Title</h5>
        <ifx-link bold="false" slot="link" href="https://google.com" underline="false">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link" href="https://google.com">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link" href="https://google.com">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link" href="https://google.com">Footer Link</ifx-link>
      </ifx-footer-column>
      <ifx-footer-column slot="col">
        <h5 slot="title">Title</h5>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
        <ifx-link bold="false" slot="link">Footer Link</ifx-link>
      </ifx-footer-column>
      <div slot="socials">
        <ifx-link href="http://facebook.com/infineon">
          <ifx-icon icon="c-info-16"></ifx-icon>
        </ifx-link>
        <ifx-link href="http://youtube.com/infineon">
          <ifx-icon icon="calendar-16"></ifx-icon>
        </ifx-link>
        <ifx-link href="http://instagram.com/infineon">
          <ifx-icon icon="fileexe16"></ifx-icon>
        </ifx-link>
        <ifx-link href="http://linkedin.com/infineon">
          <ifx-icon icon="filegif16"></ifx-icon>
        </ifx-link>
        <ifx-link href="http://twitter.com/infineon">
          <ifx-icon icon="filehtml16"></ifx-icon>
        </ifx-link>
        <ifx-link href="http://xing.com/infineon">
          <ifx-icon icon="filejpg16"></ifx-icon>
        </ifx-link>
      </div>
      <div slot="info">
        <ifx-link variant="menu" href="https://yourwebsite.com/terms" target="_blank">Terms</ifx-link>
      </div>
    </ifx-footer>
  </div>
</template>
