// packages/components/src/components/link/link.tsx
import { Component, Prop, h } from "@stencil/core";
import classNames from 'classnames';

@Component({
  tag: 'ifx-link',
  styleUrl: 'link.scss',
  shadow: true
})

export class Link {
  @Prop({ mutable: true }) href: string
  @Prop({ mutable: true }) target: string = '_self';
  @Prop() size: string;
  @Prop() disabled: boolean = false;
  @Prop({ mutable: true }) variant: string = 'bold';


  render() {
    return (
      <a aria-label='a navigation link button' href={this.href} target={this.target} class={this.linkClassNames()}>
        <slot></slot>
      </a>
    )
  }

  getSizeClass() {
    const small = this.size === 's' ? 'small' : null;
    const medium = this.size === 'm' ? 'medium' : null;
    const large = this.size === 'l' ? 'large' : null;
    const extraLarge = this.size === 'xl' ? 'extraLarge' : null;

    if (small) {
      return small;
    } else if (medium) {
      return medium;
    } else if (large) {
      return large;
    } else if (extraLarge && this.variant === 'underlined') {
      return 'large';
    } else if (extraLarge && this.variant !== 'underlined') {
      return extraLarge;
    } else return "";
  }

  getVariantClass() {
    const bold = this.variant === 'bold' ? 'bold' : null;
    const title = this.variant === 'title' ? 'title' : null;
    const underlined = this.variant === 'underlined' ? 'underlined' : null;
    const menu = this.variant === 'menu' ? 'menu' : null;

    if (bold) {
      return bold
    } else if (title) {
      return title;
    } else if (underlined) {
      return underlined;
    } else if (menu) {
      return menu;
    } else return bold;
  }

  linkClassNames() {
    return classNames(
      'link',
      'primary',
      this.getVariantClass(),
      this.getSizeClass(),
      this.disabled ? 'disabled' : '',
    );
  }
}

// examples/wrapper-components/vue-javascript/src/components/Link.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["bold", "underlined", "title", "menu"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const sizes = ["s", "m", "l", "xl"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const disabled = ref(false);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

</script>

<template>
  <div class="component">
    <h2>Link</h2>
    <ifx-link href="" aria-label="Link" target="_blank" :size="size" :variant="variant" :disabled="disabled" download="">Link</ifx-link>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Variant:</b> {{ variant }} </div>
      <div><b>Size:</b> {{ size }}</div>
      <div><b>Disabled:</b> {{ disabled }}</div>
    </div>
  </div>
</template>
