// packages/components-angular/projects/my-app/src/app/components/link/link.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-link',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './link.component.html',
  styleUrl: './link.component.scss'
})
export class LinkComponent {
  variant = "bold";
  variants = ["bold", "underlined", "title", "menu"];
  variantIndex = 0;

  size = "m";
  sizes = ["s", "m", "l", "xl"];
  sizeIndex = 1;

  disabled = false;

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }

  toggleDisabled() {
    this.disabled = !this.disabled;
  }
}

<h2>Link</h2>

<ifx-link href="" aria-label="Link" target="_blank" [size]="linkSize" [variant]="linkVariant" [disabled]="linkDisabled" download="" >
  Link
</ifx-link>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleLinkVariant()">Toggle Variant</ifx-button>
<ifx-button variant="secondary" (click)="toggleLinkSize()">Toggle Size</ifx-button>
<ifx-button variant="secondary" (click)="toggleLinkDisabled()">Toggle Disabled</ifx-button>
<br>
<br>
<span><b>Variant:</b> {{ linkVariant }} </span><br>
<span><b>Size:</b> {{ linkSize }}</span><br>
<span><b>Disabled:</b> {{ linkDisabled }}</span><br>

// examples/wrapper-components/vue-javascript/src/components/Link.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["bold", "underlined", "title", "menu"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const sizes = ["s", "m", "l", "xl"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const disabled = ref(false);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

</script>

<template>
  <div class="component">
    <h2>Link</h2>
    <ifx-link href="" aria-label="Link" target="_blank" :size="size" :variant="variant" :disabled="disabled" download="">Link</ifx-link>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Variant:</b> {{ variant }} </div>
      <div><b>Size:</b> {{ size }}</div>
      <div><b>Disabled:</b> {{ disabled }}</div>
    </div>
  </div>
</template>
