// packages/components-angular/projects/my-app/src/app/components/multi-select/multi-select.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-multi-select',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './multi-select.component.html',
  styleUrl: './multi-select.component.scss'
})
export class MultiSelectComponent {

}

<h2>Multi Select</h2>

<ifx-multiselect name="multiselect" [disabled]="multiDisabled" [required]="multiRequired" [error]="multiError"
  caption="Caption for generic multi-select component." label="Generic Multi-Level Selection"
  placeholder="Select options..." [showSearch]="multiShowSearch" [showSelectAll]="multiShowSelectAll"
  [showExpandCollapse]="multiShowExpandCollapse" [showClearButton]="multiShowClearButton"
  no-results-message="No results found." [showNoResultsMessage]="multiShowNoResultsMessage" search-placeholder="Search"
  select-all-label="Select all" expand-label="Expand" collapse-label="Collapse"
  aria-multi-select-label="Multi-select dropdown" aria-multi-select-labelled-by="" aria-multi-select-described-by=""
  aria-search-label="Search options" aria-clear-label="Clear all selections" aria-toggle-label="Toggle dropdown"
  aria-select-all-label="Select all options" aria-expand-all-label="Expand all categories"
  aria-collapse-all-label="Collapse all categories">

  <ifx-multiselect-option value="category-a">
    Category A - Main Section

    <ifx-multiselect-option value="category-a-1" slot="children">
      Category A.1 - First Subsection
      <ifx-multiselect-option value="option-a-1-1" slot="children">Option A.1.1 - Basic Item</ifx-multiselect-option>
      <ifx-multiselect-option value="option-a-1-2" selected slot="children">Option A.1.2 - Preselected
        Item</ifx-multiselect-option>
      <ifx-multiselect-option value="option-a-1-3" slot="children">Option A.1.3 - Another Item</ifx-multiselect-option>
    </ifx-multiselect-option>

    <ifx-multiselect-option value="category-a-2" slot="children">
      Category A.2 - Second Subsection
      <ifx-multiselect-option value="option-a-2-1" slot="children">Option A.2.1 - Nested Item</ifx-multiselect-option>
      <ifx-multiselect-option value="option-a-2-2" slot="children">
        Option A.2.2 - Deep Nested Parent
        <ifx-multiselect-option value="option-a-2-2-1" slot="children">Option A.2.2.1 - Level 4
          Item</ifx-multiselect-option>
        <ifx-multiselect-option value="option-a-2-2-2" slot="children">Option A.2.2.2 - Level 4
          Item</ifx-multiselect-option>
        <ifx-multiselect-option value="option-a-2-2-3" slot="children">
          Option A.2.2.3 - Even Deeper
          <ifx-multiselect-option value="option-a-2-2-3-1" slot="children">Option A.2.2.3.1 - Level 5
            Item</ifx-multiselect-option>
          <ifx-multiselect-option value="option-a-2-2-3-2" slot="children">Option A.2.2.3.2 - Level 5
            Item</ifx-multiselect-option>
        </ifx-multiselect-option>
      </ifx-multiselect-option>
      <ifx-multiselect-option value="option-a-2-3" slot="children">Option A.2.3 - Final Nested</ifx-multiselect-option>
    </ifx-multiselect-option>

    <ifx-multiselect-option value="option-a-3" slot="children">Option A.3 - Direct Child</ifx-multiselect-option>
    <ifx-multiselect-option value="option-a-4" slot="children">Option A.4 - Another Direct
      Child</ifx-multiselect-option>
  </ifx-multiselect-option>

  <ifx-multiselect-option value="category-b">
    Category B - Secondary Section

    <ifx-multiselect-option value="category-b-1" slot="children">
      Category B.1 - Mixed Content
      <ifx-multiselect-option value="option-b-1-1" slot="children">Option B.1.1 - Standard Item</ifx-multiselect-option>
      <ifx-multiselect-option value="category-b-1-2" slot="children">
        Category B.1.2 - Sub-Category
        <ifx-multiselect-option value="option-b-1-2-1" slot="children">Option B.1.2.1 - Nested
          Choice</ifx-multiselect-option>
        <ifx-multiselect-option value="option-b-1-2-2" slot="children">Option B.1.2.2 - Nested
          Choice</ifx-multiselect-option>
        <ifx-multiselect-option value="option-b-1-2-3" slot="children">Option B.1.2.3 - Nested
          Choice</ifx-multiselect-option>
      </ifx-multiselect-option>
      <ifx-multiselect-option value="option-b-1-3" slot="children">Option B.1.3 - Standard Item</ifx-multiselect-option>
    </ifx-multiselect-option>

    <ifx-multiselect-option value="option-b-2" slot="children">Option B.2 - Standalone Item</ifx-multiselect-option>
    <ifx-multiselect-option value="option-b-3" slot="children">Option B.3 - Standalone Item</ifx-multiselect-option>
  </ifx-multiselect-option>

  <ifx-multiselect-option value="category-c">
    Category C - Complex Structure

    <ifx-multiselect-option value="category-c-1" slot="children">
      Category C.1 - Multi-Level Group
      <ifx-multiselect-option value="category-c-1-1" slot="children">
        Category C.1.1 - Sub-Group Alpha
        <ifx-multiselect-option value="option-c-1-1-1" slot="children">Option C.1.1.1 - Alpha Item
          1</ifx-multiselect-option>
        <ifx-multiselect-option value="option-c-1-1-2" slot="children">Option C.1.1.2 - Alpha Item
          2</ifx-multiselect-option>
      </ifx-multiselect-option>
      <ifx-multiselect-option value="category-c-1-2" slot="children">
        Category C.1.2 - Sub-Group Beta
        <ifx-multiselect-option value="option-c-1-2-1" slot="children">Option C.1.2.1 - Beta Item
          1</ifx-multiselect-option>
        <ifx-multiselect-option value="option-c-1-2-2" slot="children">Option C.1.2.2 - Beta Item
          2</ifx-multiselect-option>
        <ifx-multiselect-option value="option-c-1-2-3" slot="children">Option C.1.2.3 - Beta Item
          3</ifx-multiselect-option>
      </ifx-multiselect-option>
      <ifx-multiselect-option value="option-c-1-3" slot="children">Option C.1.3 - Direct Item</ifx-multiselect-option>
    </ifx-multiselect-option>

    <ifx-multiselect-option value="category-c-2" slot="children">
      Category C.2 - Another Group
      <ifx-multiselect-option value="option-c-2-1" slot="children">Option C.2.1 - Group Item</ifx-multiselect-option>
      <ifx-multiselect-option value="option-c-2-2" slot="children">Option C.2.2 - Group Item</ifx-multiselect-option>
    </ifx-multiselect-option>
  </ifx-multiselect-option>

  <ifx-multiselect-option value="option-d">Option D - Top-Level Standalone</ifx-multiselect-option>

  <ifx-multiselect-option value="option-e">Option E - Top-Level Standalone</ifx-multiselect-option>

  <ifx-multiselect-option value="category-f">
    Category F - Final Section

    <ifx-multiselect-option value="option-f-1" slot="children">Option F.1 - Simple Item</ifx-multiselect-option>
    <ifx-multiselect-option value="option-f-2" slot="children">Option F.2 - Simple Item</ifx-multiselect-option>

    <ifx-multiselect-option value="category-f-3" slot="children">
      Category F.3 - Last Group
      <ifx-multiselect-option value="option-f-3-1" slot="children">Option F.3.1 - Final Nested</ifx-multiselect-option>
      <ifx-multiselect-option value="option-f-3-2" slot="children">Option F.3.2 - Final Nested</ifx-multiselect-option>
      <ifx-multiselect-option value="option-f-3-3" slot="children">Option F.3.3 - Final Nested</ifx-multiselect-option>
    </ifx-multiselect-option>
  </ifx-multiselect-option>
</ifx-multiselect>
<br />
<br />

<h3 class="controls-title">Controls</h3>
<div class="controls">
  <ifx-button variant="secondary" (click)="toggleDisabled()">Toggle Disabled</ifx-button>
  <ifx-button variant="secondary" (click)="toggleRequired()">Toggle Required</ifx-button>
  <ifx-button variant="secondary" (click)="toggleError()">Toggle Error</ifx-button>
  <ifx-button variant="secondary" (click)="toggleShowSearch()">Toggle Search</ifx-button>
  <ifx-button variant="secondary" (click)="toggleShowSelectAll()">Toggle Select All</ifx-button>
  <ifx-button variant="secondary" (click)="toggleShowExpandCollapse()">Toggle Expand / Collapse</ifx-button>
  <ifx-button variant="secondary" (click)="toggleShowClearButton()">Toggle Clear Button</ifx-button>
  <ifx-button variant="secondary" (click)="toggleShowNoResultsMessage()">Toggle No Results Message</ifx-button>
</div>
<br />

<div class="state">
  <div><b>Disabled:</b> {{ multiDisabled }}</div>
  <div><b>Required:</b> {{ multiRequired }}</div>
  <div><b>Error:</b> {{ multiError }}</div>
  <div><b>Show Search:</b> {{ multiShowSearch }}</div>
  <div><b>Show Select All:</b> {{ multiShowSelectAll }}</div>
  <div><b>Show Expand / Collapse:</b> {{ multiShowExpandCollapse }}</div>
  <div><b>Show Clear Button:</b> {{ multiShowClearButton }}</div>
  <div><b>Show No Results Message:</b> {{ multiShowNoResultsMessage }}</div>
</div>

// examples/wrapper-components/vue-javascript/src/components/MultiSelect.vue
<script setup lang="ts">
import { ref } from "vue";

const disabled = ref(false);
const required = ref(true);
const error = ref(false);
const showSearch = ref(true);
const showSelectAll = ref(true);
const showExpandCollapse = ref(true);
const showClearButton = ref(true);
const showNoResultsMessage = ref(true);

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleRequired() {
  required.value = !required.value;
}

function toggleError() {
  error.value = !error.value;
}

function toggleShowSearch() {
  showSearch.value = !showSearch.value;
}

function toggleShowClearButton() {
  showClearButton.value = !showClearButton.value;
}

function toggleShowSelectAll() {
  showSelectAll.value = !showSelectAll.value;
}

function toggleShowExpandCollapse() {
  showExpandCollapse.value = !showExpandCollapse.value;
}

function toggleShowNoResultsMessage() {
  showNoResultsMessage.value = !showNoResultsMessage.value;
}

</script>

<template>
  <div class="component">
    <h2>Multi Select</h2>
    <ifx-multiselect name="multiselect" :disabled="disabled" :required="required" :error="error"
      caption="Caption for generic multi-select component." label="Generic Multi-Level Selection"
      placeholder="Select options..." :showSearch="showSearch" :showSelectAll="showSelectAll"
      :showExpandCollapse="showExpandCollapse" :showClearButton="showClearButton"
      no-results-message="No results found." :showNoResultsMessage="showNoResultsMessage" search-placeholder="Search"
      select-all-label="Select all" expand-label="Expand" collapse-label="Collapse"
      aria-multi-select-label="Multi-select dropdown" aria-multi-select-labelled-by="" aria-multi-select-described-by=""
      aria-search-label="Search options" aria-clear-label="Clear all selections" aria-toggle-label="Toggle dropdown"
      aria-select-all-label="Select all options" aria-expand-all-label="Expand all categories"
      aria-collapse-all-label="Collapse all categories">

      <ifx-multiselect-option value="category-a">
        Category A - Main Section

        <ifx-multiselect-option value="category-a-1" slot="children">
          Category A.1 - First Subsection
          <ifx-multiselect-option value="option-a-1-1" slot="children">Option A.1.1 - Basic
            Item</ifx-multiselect-option>
          <ifx-multiselect-option value="option-a-1-2" selected slot="children">Option A.1.2 - Preselected
            Item</ifx-multiselect-option>
          <ifx-multiselect-option value="option-a-1-3" slot="children">Option A.1.3 - Another
            Item</ifx-multiselect-option>
        </ifx-multiselect-option>

        <ifx-multiselect-option value="category-a-2" slot="children">
          Category A.2 - Second Subsection
          <ifx-multiselect-option value="option-a-2-1" slot="children">Option A.2.1 - Nested
            Item</ifx-multiselect-option>
          <ifx-multiselect-option value="option-a-2-2" slot="children">
            Option A.2.2 - Deep Nested Parent
            <ifx-multiselect-option value="option-a-2-2-1" slot="children">Option A.2.2.1 - Level 4
              Item</ifx-multiselect-option>
            <ifx-multiselect-option value="option-a-2-2-2" slot="children">Option A.2.2.2 - Level 4
              Item</ifx-multiselect-option>
            <ifx-multiselect-option value="option-a-2-2-3" slot="children">
              Option A.2.2.3 - Even Deeper
              <ifx-multiselect-option value="option-a-2-2-3-1" slot="children">Option A.2.2.3.1 - Level 5
                Item</ifx-multiselect-option>
              <ifx-multiselect-option value="option-a-2-2-3-2" slot="children">Option A.2.2.3.2 - Level 5
                Item</ifx-multiselect-option>
            </ifx-multiselect-option>
          </ifx-multiselect-option>
          <ifx-multiselect-option value="option-a-2-3" slot="children">Option A.2.3 - Final
            Nested</ifx-multiselect-option>
        </ifx-multiselect-option>

        <ifx-multiselect-option value="option-a-3" slot="children">Option A.3 - Direct Child</ifx-multiselect-option>
        <ifx-multiselect-option value="option-a-4" slot="children">Option A.4 - Another Direct
          Child</ifx-multiselect-option>
      </ifx-multiselect-option>

      <ifx-multiselect-option value="category-b">
        Category B - Secondary Section

        <ifx-multiselect-option value="category-b-1" slot="children">
          Category B.1 - Mixed Content
          <ifx-multiselect-option value="option-b-1-1" slot="children">Option B.1.1 - Standard
            Item</ifx-multiselect-option>
          <ifx-multiselect-option value="category-b-1-2" slot="children">
            Category B.1.2 - Sub-Category
            <ifx-multiselect-option value="option-b-1-2-1" slot="children">Option B.1.2.1 - Nested
              Choice</ifx-multiselect-option>
            <ifx-multiselect-option value="option-b-1-2-2" slot="children">Option B.1.2.2 - Nested
              Choice</ifx-multiselect-option>
            <ifx-multiselect-option value="option-b-1-2-3" slot="children">Option B.1.2.3 - Nested
              Choice</ifx-multiselect-option>
          </ifx-multiselect-option>
          <ifx-multiselect-option value="option-b-1-3" slot="children">Option B.1.3 - Standard
            Item</ifx-multiselect-option>
        </ifx-multiselect-option>

        <ifx-multiselect-option value="option-b-2" slot="children">Option B.2 - Standalone Item</ifx-multiselect-option>
        <ifx-multiselect-option value="option-b-3" slot="children">Option B.3 - Standalone Item</ifx-multiselect-option>
      </ifx-multiselect-option>

      <ifx-multiselect-option value="category-c">
        Category C - Complex Structure

        <ifx-multiselect-option value="category-c-1" slot="children">
          Category C.1 - Multi-Level Group
          <ifx-multiselect-option value="category-c-1-1" slot="children">
            Category C.1.1 - Sub-Group Alpha
            <ifx-multiselect-option value="option-c-1-1-1" slot="children">Option C.1.1.1 - Alpha Item
              1</ifx-multiselect-option>
            <ifx-multiselect-option value="option-c-1-1-2" slot="children">Option C.1.1.2 - Alpha Item
              2</ifx-multiselect-option>
          </ifx-multiselect-option>
          <ifx-multiselect-option value="category-c-1-2" slot="children">
            Category C.1.2 - Sub-Group Beta
            <ifx-multiselect-option value="option-c-1-2-1" slot="children">Option C.1.2.1 - Beta Item
              1</ifx-multiselect-option>
            <ifx-multiselect-option value="option-c-1-2-2" slot="children">Option C.1.2.2 - Beta Item
              2</ifx-multiselect-option>
            <ifx-multiselect-option value="option-c-1-2-3" slot="children">Option C.1.2.3 - Beta Item
              3</ifx-multiselect-option>
          </ifx-multiselect-option>
          <ifx-multiselect-option value="option-c-1-3" slot="children">Option C.1.3 - Direct
            Item</ifx-multiselect-option>
        </ifx-multiselect-option>

        <ifx-multiselect-option value="category-c-2" slot="children">
          Category C.2 - Another Group
          <ifx-multiselect-option value="option-c-2-1" slot="children">Option C.2.1 - Group
            Item</ifx-multiselect-option>
          <ifx-multiselect-option value="option-c-2-2" slot="children">Option C.2.2 - Group
            Item</ifx-multiselect-option>
        </ifx-multiselect-option>
      </ifx-multiselect-option>

      <ifx-multiselect-option value="option-d">Option D - Top-Level Standalone</ifx-multiselect-option>

      <ifx-multiselect-option value="option-e">Option E - Top-Level Standalone</ifx-multiselect-option>

      <ifx-multiselect-option value="category-f">
        Category F - Final Section

        <ifx-multiselect-option value="option-f-1" slot="children">Option F.1 - Simple Item</ifx-multiselect-option>
        <ifx-multiselect-option value="option-f-2" slot="children">Option F.2 - Simple Item</ifx-multiselect-option>

        <ifx-multiselect-option value="category-f-3" slot="children">
          Category F.3 - Last Group
          <ifx-multiselect-option value="option-f-3-1" slot="children">Option F.3.1 - Final
            Nested</ifx-multiselect-option>
          <ifx-multiselect-option value="option-f-3-2" slot="children">Option F.3.2 - Final
            Nested</ifx-multiselect-option>
          <ifx-multiselect-option value="option-f-3-3" slot="children">Option F.3.3 - Final
            Nested</ifx-multiselect-option>
        </ifx-multiselect-option>
      </ifx-multiselect-option>
    </ifx-multiselect>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleRequired">Toggle Required</ifx-button>
      <ifx-button variant="secondary" @click="toggleError">Toggle Error</ifx-button>
      <ifx-button variant="secondary" @click="toggleShowSearch">Toggle Search</ifx-button>
      <ifx-button variant="secondary" @click="toggleShowSelectAll">Toggle Select All</ifx-button>
      <ifx-button variant="secondary" @click="toggleShowExpandCollapse">Toggle Expand / Collapse</ifx-button>
      <ifx-button variant="secondary" @click="toggleShowClearButton">Toggle Clear Button</ifx-button>
      <ifx-button variant="secondary" @click="toggleShowNoResultsMessage">Toggle No Results Message</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Disabled:</b> {{ disabled }}</div>
      <div><b>Required:</b> {{ required }}</div>
      <div><b>Error:</b> {{ error }}</div>
      <div><b>Show Search:</b> {{ showSearch }}</div>
      <div><b>Show Select All:</b> {{ showSelectAll }}</div>
      <div><b>Show Expand / Collapse:</b> {{ showExpandCollapse }}</div>
      <div><b>Show Clear Button:</b> {{ showClearButton }}</div>
      <div><b>Show No Results Message:</b> {{ showNoResultsMessage }}</div>
    </div>
  </div>
</template>
