// examples/wrapper-components/react-typescript/src/components/SearchInput/SearchInput.tsx
import { IfxIcon, IfxSearchInput } from '@infineon/infineon-design-system-react';

function SearchInput() {
  const handleSearch = (event: CustomEvent) => {
    console.log("handling input: ", event.detail?.detail)
  };

  return (
    <div  >
        <IfxSearchInput disabled={false} size='m' show-delete-icon="true" onIfxInput={handleSearch}></IfxSearchInput>
    </div>
  )
}

export default SearchInput;

// examples/wrapper-components/vue-javascript/src/components/SearchInput.vue
<template>
  <div>
    <ifx-search-input disabled="false" size='m' show-delete-icon="true" @ifxInput="handleSearch">
      <ifx-icon icon="search-16" class="search-icon"></ifx-icon>
    </ifx-search-input>
  </div>
</template>

<script  setup>

const handleSearch = (e) => { 
  console.log(e.detail)
}

</script>

<style scoped>

</style>
