// packages/components-angular/projects/my-app/src/app/components/segmented-control/segmented-control.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-segmented-control',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './segmented-control.component.html',
  styleUrl: './segmented-control.component.scss'
})
export class SegmentedControlComponent {
  error = false;
  required = false;

  size = "regular";
  sizes = ["regular", "small"];
  sizeIndex = 0;

  toggleError() {
    this.error = !this.error;
  }

  toggleRequired() {
    this.required = !this.required;
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }
}

<h2>Segmented Control</h2>
<ifx-segmented-control caption="Caption text to describe the controls" label="Group Label" [size]="segmentedControlSize" [error]="segmentedControlError" [required]="segmentedControlRequired">
    <ifx-segment value="Value1" icon="star-16">Label</ifx-segment>
    <ifx-segment value="Value2" icon="star-16">Label</ifx-segment>
    <ifx-segment value="Value3" icon="star-16">Label</ifx-segment>
    <ifx-segment value="Value4" icon="star-16">Label</ifx-segment>
    <ifx-segment value="Value5" icon="star-16">Label</ifx-segment>
</ifx-segmented-control>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleSerchFieldError()">Toggle Error</ifx-button>
<ifx-button variant="secondary" (click)="toggleSegmentedControlRequired()">Toggle Required</ifx-button>
<ifx-button variant="secondary" (click)="toggleSegmentedControlSize()">Toggle Size</ifx-button>
<br>
<br>
<span><b>Error:</b> {{ segmentedControlError }} </span><br>
<span><b>Required:</b> {{ segmentedControlRequired }} </span><br>
<span><b>Size:</b> {{ segmentedControlSize }} </span><br>

// examples/wrapper-components/vue-javascript/src/components/SegmentedControl.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["regular", "small"];
const sizeIndex = ref(0);
const size = computed(() => sizes[sizeIndex.value]);

const error = ref(false);
const required = ref(false);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleRequired() {
  required.value = !required.value;
}

function toggleError() {
  error.value = !error.value;
}

</script>

<template>
  <div class="component">
    <h2>Segmented Control</h2>
    <ifx-segmented-control caption="Caption text to describe the controls" label="Group Label" :size="size"
      :error="error" :required="required">
      <ifx-segment value="Value1" icon="star-16">Label</ifx-segment>
      <ifx-segment value="Value2" icon="star-16">Label</ifx-segment>
      <ifx-segment value="Value3" icon="star-16">Label</ifx-segment>
      <ifx-segment value="Value4" icon="star-16">Label</ifx-segment>
      <ifx-segment value="Value5" icon="star-16">Label</ifx-segment>
    </ifx-segmented-control>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleError">Toggle Error</ifx-button>
      <ifx-button variant="secondary" @click="toggleRequired">Toggle Required</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Error:</b> {{ error }} </div>
      <div><b>Required:</b> {{ required }} </div>
      <div><b>Size:</b> {{ size }} </div>
    </div>
  </div>
</template>
