// examples/wrapper-components/react-vite-js/src/components/Sidebar/Sidebar.jsx
import { IfxSidebar, IfxSidebarItem, IfxSidebarTitle } from '@infineon/infineon-design-system-react';


function Sidebar() {

  return (
    <div>
      <IfxSidebar application-name="Application Name" collapsible="true" collapsed="false" hide-menu-label="Hide Menu" show-header="true" show-footer="true" initial-collapse="true" terms-of-use="undefined" imprint="undefined" privacy-policy="undefined" copyright-text="© 1999 - 2026 Infineon Technologies AG">
    <IfxSidebarTitle>Menu Items</IfxSidebarTitle>
    <IfxSidebarItem href="https://google.com" target="_blank" icon="image-16">Menu Item</IfxSidebarItem>
    <IfxSidebarItem href="https://google.com" target="_blank" icon="image-16">Menu Item</IfxSidebarItem>
    <IfxSidebarItem href="https://google.com" target="_blank" icon="image-16">Menu Item</IfxSidebarItem>
    <IfxSidebarItem href="https://google.com" target="_blank" icon="image-16">Menu Item</IfxSidebarItem>
    <IfxSidebarItem>
    Section
    <IfxSidebarItem href="https://google.com" target="_blank" icon="image-16">Menu Item</IfxSidebarItem>
    <IfxSidebarItem icon="image-16">
    Menu Item
    <IfxSidebarItem>Sub menu item</IfxSidebarItem>
    <IfxSidebarItem active="true">Sub menu item</IfxSidebarItem>
    <IfxSidebarItem>Sub menu item</IfxSidebarItem>
    </IfxSidebarItem>
    <IfxSidebarItem href="https://google.com" target="_blank">Menu Item</IfxSidebarItem>
    <IfxSidebarItem href="https://google.com" target="_blank">Menu Item</IfxSidebarItem>
    </IfxSidebarItem>
    <IfxSidebarTitle>Items group</IfxSidebarTitle>
    <IfxSidebarItem href="https://google.com" target="_self" icon="image-16" number-indicator="" isactionitem="false" active="false">Item 1</IfxSidebarItem>
    <IfxSidebarItem href="https://google.com" target="_blank" icon="image-16">Item 2</IfxSidebarItem>
  </IfxSidebar>
    </div>
  )
}

export default Sidebar;

// examples/wrapper-components/vue-javascript/src/components/Sidebar.vue
<template>
  <div class="component">
    <h2>Sidebar</h2>
    <ifx-sidebar application-name="Application Name" collapsible="true" collapsed="false" hide-menu-label="Hide Menu"
      show-header="true" show-footer="true" initial-collapse="true" terms-of-use="https://yourwebsite.com/terms"
      imprint="https://yourwebsite.com/imprint" privacy-policy="https://yourwebsite.com/privacy-policy"
      copyright-text="© 1999 - 2026 Infineon Technologies AG">
      <ifx-sidebar-title>Menu Items</ifx-sidebar-title>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item>
        Section
        <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
        <ifx-sidebar-item icon="image-16">
          Menu Item
          <ifx-sidebar-item>Sub menu item</ifx-sidebar-item>
          <ifx-sidebar-item active="true">Sub menu item</ifx-sidebar-item>
          <ifx-sidebar-item>Sub menu item</ifx-sidebar-item>
        </ifx-sidebar-item>
        <ifx-sidebar-item href="https://google.com" target="_blank">Menu Item</ifx-sidebar-item>
        <ifx-sidebar-item href="https://google.com" target="_blank">Menu Item</ifx-sidebar-item>
      </ifx-sidebar-item>
      <ifx-sidebar-title>Items group</ifx-sidebar-title>
      <ifx-sidebar-item href="https://google.com" target="_self" icon="image-16" number-indicator=""
        isactionitem="false" active="false">Item 1</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Item 2</ifx-sidebar-item>
    </ifx-sidebar>
  </div>
</template>
