// examples/wrapper-components/react-vite-js/src/components/Spinner/Spinner.jsx
import { useState } from 'react';
import { IfxSpinner, IfxButton } from '@infineon/infineon-design-system-react';

function Spinner() {
  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ['default', 'brand'];

  const [sizeIndex, setSizeIndex] = useState(1);
  const sizes = ['s', 'm'];

  const [inverted, setInverted] = useState(false);

  const toggleVariant = () => {
    setVariantIndex((index) => (index + 1) % variants.length);
  };

  const toggleSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  };

  const toggleInverted = () => {
    setInverted((prev) => !prev);
  };

  return (
    <div className="component">
      <h2>Spinner</h2>

      <IfxSpinner
        variant={variants[variantIndex]}
        size={sizes[sizeIndex]}
        inverted={inverted}
      ></IfxSpinner>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
        <IfxButton variant="secondary" onClick={toggleInverted}>Toggle Inverted</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Variant:</b> {variants[variantIndex]}</div>
        <div><b>Inverted:</b> {String(inverted)}</div>
        <div><b>Size:</b> {sizes[sizeIndex]}</div>
      </div>
    </div>
  );
}

export default Spinner;

// examples/wrapper-components/vue-javascript/src/components/Spinner.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["default", "brand"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const sizes = ["s", "m"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const inverted = ref(false);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleInverted() {
  inverted.value = !inverted.value;
}

</script>

<template>
  <div class="component">
    <h2>Spinner</h2>
    <ifx-spinner aria-label="" :variant="variant" :size="size" :inverted="inverted"></ifx-spinner>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="toggleInverted">Toggle Inverted</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Variant:</b> {{ variant }} </div>
      <div><b>Inverted:</b> {{ inverted }} </div>
      <div><b>Size:</b> {{ size }} </div>
    </div>
  </div>
</template>
