// examples/wrapper-components/react-javascript/src/components/Status/Status.js
import React from 'react';
import { IfxStatus } from '@infineon/infineon-design-system-react';

function Status() {
  return (
    <div>
      <IfxStatus label="Status without border" color="red" border="false"></IfxStatus>
      <br />
      <IfxStatus label="Status with border" color="orange" border="true"></IfxStatus>
    </div >
  );
}

export default Status;

// examples/wrapper-components/vue-javascript/src/components/Status.vue

<template>
  <div class="component">
    <h2>Status</h2>
    <div>
      <ifx-status label="Status with border" color="ocean-500" border="true" />
      <ifx-status label="Status without border" color="orange-500" border="false" />
    </div>
    <br />
    <br />
  </div>
</template>

<script setup>


</script>
