// packages/components-angular/projects/my-app/src/app/components/switch/switch.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-switch',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './switch.component.html',
  styleUrl: './switch.component.scss'
})
export class SwitchComponent {
  switchDisable = false;

  toggleSwitchDisable() {
    this.switchDisable = !this.switchDisable;
  }
}

<h2>Switch</h2>
<ifx-switch checked="false" name="switch" value="switch" [disabled]="disabled">Switch</ifx-switch>
<br>
<br>

<h3 class="controls-title">Controls</h3>
<div class="controls">
  <ifx-button variant="secondary" (click)="toggleDisable()">Toggle Disabled</ifx-button>
</div>
<br>

<div class="state">
  <div><b>Disabled:</b> {{ disabled }} </div>
</div>

// examples/wrapper-components/vue-javascript/src/components/Switch.vue
<script setup lang="ts">
import { ref } from "vue";

const disabled = ref(false);

function toggleDisable() {
  disabled.value = !disabled.value;
}

</script>

<template>
  <div class="component">
    <h2>Switch</h2>
    <ifx-switch checked="false" name="switch" value="switch" :disabled="disabled">Switch</ifx-switch>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleDisable">Toggle Disabled</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Disabled:</b> {{ disabled }} </div>
    </div>
  </div>
</template>
