// packages/components-angular/projects/my-app/src/app/components/text-field/text-field.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-text-field',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './text-field.component.html',
  styleUrl: './text-field.component.scss'
})
export class TextFieldComponent {
  error = false;
  disabled = false;
  success = false;
  readOnly = false;
  required = false;
  deleteIcon = false;

  size = "m";
  sizes = ["s", "m"];
  sizeIndex = 1;

  icon = "";
  icons = ["", "arrowDown16"];
  iconIndex = 0;

  toggleError() {
    this.error = !this.error;
  }

  toggleDisabled() {
    this.disabled = !this.disabled;
  }

  toggleSuccess() {
    this.success = !this.success;
  }

  toggleReadOnly() {
    this.readOnly = !this.readOnly;
  }

  toggleRequired() {
    this.required = !this.required;
  }

  toggleDeleteIcon() {
    this.deleteIcon = !this.deleteIcon;
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }

  toggleIcon() {
    this.iconIndex = (this.iconIndex + 1) % this.icons.length;
    this.icon = this.icons[this.iconIndex];
  }
}

<h2>Text Field</h2>
<ifx-text-field 
[error]="textFieldError" 
[disabled]="textFieldDisabled" 
[size]="textFieldSize" 
[icon]="textFieldIcon" 
[success]="textFieldSuccess" 
placeholder="Placeholder" 
[readOnly]="textFieldReadOnly" 
caption="Caption" 
label="Label" 
[required]="textFieldRequired" 
name="text-field" 
[showDeleteIcon]="textFieldDeleteIcon" 
value="" 
autocomplete="on" 
type="text" 
internal-id="text-field" 
aria-label="text field for user input">
</ifx-text-field>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleTextFieldError()">Toggle Error</ifx-button>
<ifx-button variant="secondary" (click)="toggleTextFieldDisabled()">Toggle Disabled</ifx-button>
<ifx-button variant="secondary" (click)="toggleTextFieldSize()">Toggle Size</ifx-button>
<ifx-button variant="secondary" (click)="toggleTextFieldSuccess()">Toggle Success</ifx-button>
<ifx-button variant="secondary" (click)="toggleTextFieldReadOnly()">Toggle Read Only</ifx-button>
<ifx-button variant="secondary" (click)="toggleTextFieldRequired()">Toggle Required</ifx-button>
<ifx-button variant="secondary" (click)="toggleTextFieldDeleteIcon()">Toggle Delete Icon</ifx-button>
<ifx-button variant="secondary" (click)="toggleTextFieldIcon()">Toggle Icon</ifx-button>
<br>
<br>
<span><b>Error:</b> {{ textFieldError }} </span><br>
<span><b>Disabled:</b> {{ textFieldDisabled }} </span><br>
<span><b>Size:</b> {{ textFieldSize }} </span><br>
<span><b>Success:</b> {{ textFieldSuccess }} </span><br>
<span><b>Read Only:</b> {{ textFieldReadOnly }} </span><br>
<span><b>Required:</b> {{ textFieldRequired }} </span><br>
<span><b>Delete Icon:</b> {{ textFieldDeleteIcon }} </span><br>
<span><b>Icon:</b> {{ textFieldIcon }} </span><br>

// examples/wrapper-components/vue-javascript/src/components/TextField.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["s", "m"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const icons = ["", "arrowDown16"];
const iconIndex = ref(0);
const icon = computed(() => icons[iconIndex.value]);

const error = ref(false);
const disabled = ref(false);
const success = ref(false);
const readOnly = ref(false);
const required = ref(false);
const deleteIcon = ref(false);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleIcon() {
  iconIndex.value = (iconIndex.value + 1) % icons.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleError() {
  error.value = !error.value;
}

function toggleSuccess() {
  success.value = !success.value;
}

function toggleReadOnly() {
  readOnly.value = !readOnly.value;
}

function toggleRequired() {
  required.value = !required.value;
}

function toggleDeleteIcon() {
  deleteIcon.value = !deleteIcon.value;
}

</script>

<template>
  <div class="component">
    <h2>Text Field</h2>
    <ifx-text-field :error="error" :disabled="disabled" :size="size" :icon="icon" :success="success"
      placeholder="Placeholder" :readOnly="readOnly" caption="Caption" label="Label" :required="required"
      name="text-field" :showDeleteIcon="deleteIcon" value="" autocomplete="on" type="text" internal-id="text-field"
      aria-label="text field for user input">
    </ifx-text-field>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleError">Toggle Error</ifx-button>
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleSuccess">Toggle Success</ifx-button>
      <ifx-button variant="secondary" @click="toggleReadOnly">Toggle Read Only</ifx-button>
      <ifx-button variant="secondary" @click="toggleRequired">Toggle Required</ifx-button>
      <ifx-button variant="secondary" @click="toggleDeleteIcon">Toggle Delete Icon</ifx-button>
      <ifx-button variant="secondary" @click="toggleIcon">Toggle Icon</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Error:</b> {{ error }} </div>
      <div><b>Disabled:</b> {{ disabled }} </div>
      <div><b>Size:</b> {{ size }} </div>
      <div><b>Success:</b> {{ success }} </div>
      <div><b>Read Only:</b> {{ readOnly }} </div>
      <div><b>Required:</b> {{ required }} </div>
      <div><b>Delete Icon:</b> {{ deleteIcon }} </div>
      <div><b>Icon:</b> {{ icon }} </div>
    </div>
  </div>
</template>
