// src/components/text-input/text-input.tsx
import { Component, h, Element, Prop } from '@stencil/core';

@Component({
  tag: 'ifx-text-input',
  styleUrl: '../../index.scss', 
  shadow: true
})

export class TextInput {
  @Element() el;
  @Prop() placeholder: string = "Placeholder"
  @Prop() error: boolean = false;
  @Prop() errorMessage: string = ""
  @Prop() success: boolean = false;
  @Prop() disabled: boolean = false;

  render() {
    console.log('error message', this.errorMessage)
    return (
      <div class={`textInput__container ${this.disabled ? 'disabled' : ""}`}>
        <div class="textInput__top-wrapper">
          <label htmlFor="text-field">
            <slot />
          </label>
        </div>
        <div class="textInput__bottom-wrapper">
          <input 
          disabled={this.disabled}
          type="text" 
          id='text-field' 
          placeholder={this.placeholder} 
          class={`${this.error ? 'error' : ""} ${this.success ? "success" : ""}`}/>
          {this.error && 
            <div class="textInput__bottom-wrapper-error">
            {this.errorMessage}
          </div>}
        </div>
      </div>
    );
  }
}

// examples/wrapper-components/vue-javascript/src/components/TextInput.vue
<template>
  <div>
    <h2>Text Input</h2>
    <h3>Using v-model</h3>
    <div>
      <ifx-text-input v-model="inputValue" error="false" disabled="false" success="false" placeholder="Placeholder"
        errorMessage="">Label</ifx-text-input>
    </div>
    <p>Text field value: {{ inputValue }}</p>
    <br />
    <br />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';

let inputValue = ref("");

onMounted(() => {
  updateTextInput();
  setInterval(updateTextInput, 10000);
})

function updateTextInput() {
  console.log("updating text input from parent component")
  inputValue.value = inputValue.value + "+1";

}

</script>
