// examples/wrapper-components/react-vite-js/src/components/TextField/TextField.jsx
import { useState } from 'react';
import { IfxTextField, IfxButton } from '@infineon/infineon-design-system-react';

function TextField() {
  const [error, setError] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [success, setSuccess] = useState(false);
  const [readOnly, setReadOnly] = useState(false);
  const [required, setRequired] = useState(false);
  const [showDeleteIcon, setShowDeleteIcon] = useState(false);

  const sizes = ['s', 'm'];
  const [sizeIndex, setSizeIndex] = useState(1);

  const icons = ['', 'calendar-16'];
  const [iconIndex, setIconIndex] = useState(0);

  const toggleError = () => {
    setError(prevError => !prevError);
  }

  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  const toggleSuccess = () => {
    setSuccess(prevSuccess => !prevSuccess);
  }

  const toggleReadOnly = () => {
    setReadOnly(prevReadOnly => !prevReadOnly);
  }

  const toggleRequired = () => {
    setRequired(prevRequired => !prevRequired);
  }

  const toggleDeleteIcon = () => {
    setShowDeleteIcon(prevShowDeleteIcon => !prevShowDeleteIcon);
  }

  const toggleSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  }

  const toggleIcon = () => {
    setIconIndex((index) => (index + 1) % icons.length);
  }

  return (
    <div className="component">
      <h2>Text Field</h2>

      <IfxTextField
        error={error}
        disabled={disabled}
        size={sizes[sizeIndex]}
        icon={icons[iconIndex]}
        success={success}
        placeholder="Placeholder"
        readOnly={readOnly}
        caption="Caption"
        label="Label"
        required={required}
        name="text-field"
        showDeleteIcon={showDeleteIcon}
        value=""
        autocomplete="on"
        type="text"
        aria-label="text field for user input"
      />
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleError}>Toggle Error</IfxButton>
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSuccess}>Toggle Success</IfxButton>
        <IfxButton variant="secondary" onClick={toggleReadOnly}>Toggle Read Only</IfxButton>
        <IfxButton variant="secondary" onClick={toggleRequired}>Toggle Required</IfxButton>
        <IfxButton variant="secondary" onClick={toggleDeleteIcon}>Toggle Delete Icon</IfxButton>
        <IfxButton variant="secondary" onClick={toggleIcon}>Toggle Icon</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Error:</b> {String(error)}</div>
        <div><b>Disabled:</b> {String(disabled)}</div>
        <div><b>Size:</b> {sizes[sizeIndex]}</div>
        <div><b>Success:</b> {String(success)}</div>
        <div><b>Read Only:</b> {String(readOnly)}</div>
        <div><b>Required:</b> {String(required)}</div>
        <div><b>Delete Icon:</b> {String(showDeleteIcon)}</div>
        <div><b>Icon:</b> {icons[iconIndex]}</div>
      </div>
    </div>
  );
}

export default TextField;

// examples/wrapper-components/vue-javascript/src/components/TextField.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["s", "m"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const icons = ["", "arrowDown16"];
const iconIndex = ref(0);
const icon = computed(() => icons[iconIndex.value]);

const error = ref(false);
const disabled = ref(false);
const success = ref(false);
const readOnly = ref(false);
const required = ref(false);
const deleteIcon = ref(false);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleIcon() {
  iconIndex.value = (iconIndex.value + 1) % icons.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleError() {
  error.value = !error.value;
}

function toggleSuccess() {
  success.value = !success.value;
}

function toggleReadOnly() {
  readOnly.value = !readOnly.value;
}

function toggleRequired() {
  required.value = !required.value;
}

function toggleDeleteIcon() {
  deleteIcon.value = !deleteIcon.value;
}

</script>

<template>
  <div class="component">
    <h2>Text Field</h2>
    <ifx-text-field :error="error" :disabled="disabled" :size="size" :icon="icon" :success="success"
      placeholder="Placeholder" :readOnly="readOnly" caption="Caption" label="Label" :required="required"
      name="text-field" :showDeleteIcon="deleteIcon" value="" autocomplete="on" type="text" internal-id="text-field"
      aria-label="text field for user input">
    </ifx-text-field>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleError">Toggle Error</ifx-button>
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleSuccess">Toggle Success</ifx-button>
      <ifx-button variant="secondary" @click="toggleReadOnly">Toggle Read Only</ifx-button>
      <ifx-button variant="secondary" @click="toggleRequired">Toggle Required</ifx-button>
      <ifx-button variant="secondary" @click="toggleDeleteIcon">Toggle Delete Icon</ifx-button>
      <ifx-button variant="secondary" @click="toggleIcon">Toggle Icon</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Error:</b> {{ error }} </div>
      <div><b>Disabled:</b> {{ disabled }} </div>
      <div><b>Size:</b> {{ size }} </div>
      <div><b>Success:</b> {{ success }} </div>
      <div><b>Read Only:</b> {{ readOnly }} </div>
      <div><b>Required:</b> {{ required }} </div>
      <div><b>Delete Icon:</b> {{ deleteIcon }} </div>
      <div><b>Icon:</b> {{ icon }} </div>
    </div>
  </div>
</template>
