// examples/wrapper-components/react-vite-js/src/components/Tooltip/Tooltip.jsx
import { useState } from 'react';
import { IfxTooltip, IfxButton } from '@infineon/infineon-design-system-react';

function Tooltip() {
  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ['compact', 'dismissible', 'extended'];

  const [positionIndex, setPositionIndex] = useState(0);
  const positions = ['auto', 'top', 'right', 'bottom', 'left'];

  const toggleVariant = () => {
    setVariantIndex((index) => (index + 1) % variants.length);
  };

  const togglePosition = () => {
    setPositionIndex((index) => (index + 1) % positions.length);
  };

  return (
    <div className="component">
      <h2>Tooltip</h2>

      <IfxTooltip header="Tooltip header" text="Hi, I'm a tooltip" variant={variants[variantIndex]} position={positions[positionIndex]}>I'm the tooltip reference element - Please hover me</IfxTooltip>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
        <IfxButton variant="secondary" onClick={togglePosition}>Toggle Position</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Variant:</b> {variants[variantIndex]}</div>
        <div><b>Position:</b> {positions[positionIndex]}</div>
      </div>
    </div>
  );
}

export default Tooltip;

// examples/wrapper-components/vue-javascript/src/components/Tooltip.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["compact", "dismissible", "extended"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const positions = ["auto", "bottom-start", "top-start", "left", "bottom-end", "top-end", "right", "bottom", "top"];
const positionIndex = ref(0);
const position = computed(() => positions[positionIndex.value]);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function togglePosition() {
  positionIndex.value = (positionIndex.value + 1) % positions.length;
}

</script>

<template>
  <div class="component">
    <h2>Tooltip</h2>
    <ifx-tooltip text="Hi, I'm a tooltip" :variant="variant" :position="position" icon="arrowLeft16"
      aria-label="Tooltip with important information">
      I'm the tooltip reference element - Please hover me
    </ifx-tooltip>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="togglePosition">Toggle Position</ifx-button>
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Position:</b> {{ position }} </div>
      <div><b>Variant:</b> {{ variant }} </div>
    </div>
  </div>
</template>
