// examples/wrapper-components/vue-javascript/src/components/Chip.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["small", "medium", "large"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const variants = ["single", "multi"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const themes = ["outlined", "filled-light", "filled-dark"];
const themeIndex = ref(0);
const theme = computed(() => themes[themeIndex.value]);

const icons = ["", "windows16"];
const iconIndex = ref(0);
const icon = computed(() => icons[iconIndex.value]);

const disabled = ref(false);
const readOnly = ref(false);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleTheme() {
  themeIndex.value = (themeIndex.value + 1) % themes.length;
}

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleIcon() {
  iconIndex.value = (iconIndex.value + 1) % icons.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleReadOnly() {
  readOnly.value = !readOnly.value;
}

</script>

<template>
  <div class="component">
    <h2>Chip</h2>
    <ifx-chip placeholder="Label" :size="size" :variant="variant" :theme="theme" :icon="icon" :read-only="readOnly"
      aria-label="Chip" :disabled="disabled">
      <ifx-chip-item value="Item Value 1">Item Label 1</ifx-chip-item>
      <ifx-chip-item value="Item Value 2">Item Label 2</ifx-chip-item>
      <ifx-chip-item value="Item Value 3">Item Label 3</ifx-chip-item>
      <ifx-chip-item value="Item Value 4">Item Label 4</ifx-chip-item>
    </ifx-chip>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="toggleReadOnly">Toggle Read Only</ifx-button>
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleTheme">Toggle Theme</ifx-button>
      <ifx-button variant="secondary" @click="toggleIcon">Toggle Icon</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Size:</b> {{ size }}</div>
      <div><b>Variant:</b> {{ variant }}</div>
      <div><b>Read Only:</b> {{ String(readOnly) }}</div>
      <div><b>Disabled:</b> {{ String(disabled) }}</div>
      <div><b>Theme:</b> {{ theme }}</div>
      <div><b>Icon:</b> {{ icon }}</div>
    </div>
  </div>
</template>

// examples/wrapper-components/react-vite-js/src/components/Chip/Chip.jsx
import { useState } from 'react';
import { IfxChip, IfxChipItem, IfxButton } from '@infineon/infineon-design-system-react';

function Chip() {
  const [sizeIndex, setSizeIndex] = useState(1);
  const sizes = ["small", "medium", "large"];

  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ["single", "multi"];

  const [readOnly, setReadOnly] = useState(false);
  const [disabled, setDisabled] = useState(false);

  const [themeIndex, setThemeIndex] = useState(0);
  const themes = ["outlined", "filled-light", "filled-dark"];

  const [iconIndex, setIconIndex] = useState(0);
  const icons = ["", "windows16"];

  const toggleSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  }

  const toggleVariant = () => {
    setVariantIndex((index) => (index + 1) % variants.length);
  }

  const toggleReadOnly = () => {
    setReadOnly(prevReadOnly => !prevReadOnly);
  }

  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  const toggleTheme = () => {
    setThemeIndex((index) => (index + 1) % themes.length);
  }

  const toggleIcon = () => {
    setIconIndex((index) => (index + 1) % icons.length);
  }

  return (
    <div className="component">
      <h2>Chip</h2>
      <IfxChip placeholder="Label" size={sizes[sizeIndex]} variant={variants[variantIndex]} theme={themes[themeIndex]} icon={icons[iconIndex]} read-only={readOnly} aria-label="Chip" disabled={disabled}>
        <IfxChipItem value="Item Value 1">Item Label 1</IfxChipItem>
        <IfxChipItem value="Item Value 2">Item Label 2</IfxChipItem>
        <IfxChipItem value="Item Value 3">Item Label 3</IfxChipItem>
        <IfxChipItem value="Item Value 4">Item Label 4</IfxChipItem>
      </IfxChip>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
        <IfxButton variant="secondary" onClick={toggleReadOnly}>Toggle Read Only</IfxButton>
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={toggleTheme}>Toggle Theme</IfxButton>
        <IfxButton variant="secondary" onClick={toggleIcon}>Toggle Icon</IfxButton>
      </div>
      <br />
      
      <div class="state">
        <div><b>Size:</b> {sizes[sizeIndex]}</div>
        <div><b>Variant:</b> {variants[variantIndex]}</div>
        <div><b>Read Only:</b> {String(readOnly)}</div>
        <div><b>Disabled:</b> {String(disabled)}</div>
        <div><b>Theme:</b> {themes[themeIndex]}</div>
        <div><b>Icon:</b> {icons[iconIndex]}</div>
      </div>
    </div>
  );
}

export default Chip;
