// examples/vue-example/src/generated/IfxDropdownExample.vue
<script setup lang="ts">
import { onMounted, nextTick } from 'vue';
import Prism from 'prismjs';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-markup-templating';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';

const handleOpen = (event: CustomEvent) => {
  console.log('ifxOpen:', event.detail);
  // Add your handler logic here
};

const handleClose = (event: CustomEvent) => {
  console.log('ifxClose:', event.detail);
  // Add your handler logic here
};

const handleDropdownMenuItem = (event: CustomEvent) => {
  console.log('ifxDropdownMenuItem:', event.detail);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleOpen = (event: CustomEvent) => {
  console.log('ifxOpen:', event.detail);
  // Add your handler logic here
};

const handleClose = (event: CustomEvent) => {
  console.log('ifxClose:', event.detail);
  // Add your handler logic here
};

const handleDropdownMenuItem = (event: CustomEvent) => {
  console.log('ifxDropdownMenuItem:', event.detail);
  // Add your handler logic here
};
</' + 'script>

<template>
  <div>
    <div
      @ifxOpen="handleOpen"
      @ifxClose="handleClose"
      @ifxDropdownMenuItem="handleDropdownMenuItem">
      <ifx-dropdown
        placement="bottom-start"
        disabled="false"
        default-open="false"
        no-close-on-outside-click="false"
        no-close-on-menu-click="false"
        no-append-to-body="false">
        <ifx-dropdown-trigger-button
          variant="primary"
          @ifxOpen="handleOpen"
          @ifxClose="handleClose"
          @ifxDropdownMenuItem="handleDropdownMenuItem">
          Dropdown
        </ifx-dropdown-trigger-button>
        <ifx-dropdown-menu
          size="m"
          @ifxOpen="handleOpen"
          @ifxClose="handleClose"
          @ifxDropdownMenuItem="handleDropdownMenuItem">
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href=""
            @ifxOpen="handleOpen"
            @ifxClose="handleClose"
            @ifxDropdownMenuItem="handleDropdownMenuItem">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
        </ifx-dropdown-menu>
      </ifx-dropdown>
    </div>
  </div>
</' + 'template>`;

onMounted(() => {
  nextTick(() => {
    Prism.highlightAll();
  });
});
</script>

<template>
  <div>
    <div
      @ifxOpen="handleOpen"
      @ifxClose="handleClose"
      @ifxDropdownMenuItem="handleDropdownMenuItem">
      <ifx-dropdown
        placement="bottom-start"
        disabled="false"
        default-open="false"
        no-close-on-outside-click="false"
        no-close-on-menu-click="false"
        no-append-to-body="false">
        <ifx-dropdown-trigger-button
          variant="primary"
          @ifxOpen="handleOpen"
          @ifxClose="handleClose"
          @ifxDropdownMenuItem="handleDropdownMenuItem">
          Dropdown
        </ifx-dropdown-trigger-button>
        <ifx-dropdown-menu
          size="m"
          @ifxOpen="handleOpen"
          @ifxClose="handleClose"
          @ifxDropdownMenuItem="handleDropdownMenuItem">
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href=""
            @ifxOpen="handleOpen"
            @ifxClose="handleClose"
            @ifxDropdownMenuItem="handleDropdownMenuItem">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
          <ifx-dropdown-item
            icon="c-info-16"
            target="_self"
            href="">
            Menu Item
          </ifx-dropdown-item>
        </ifx-dropdown-menu>
      </ifx-dropdown>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-module-example/src/app/generated/ifx-dropdown-example/ifx-dropdown-example.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-dropdown-example',
  templateUrl: './ifx-dropdown-example.html',
  styleUrl: './ifx-dropdown-example.scss',
  standalone: false
})
export class IfxDropdownExample {
  protected readonly tsCode = `import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-dropdown-example&#039;,
  templateUrl: &#039;./ifx-dropdown-example.html&#039;,
  styleUrl: &#039;./ifx-dropdown-example.scss&#039;,
  standalone: false
})
export class IfxDropdownExample {
  protected handleOpen(event: CustomEvent) {
    console.log(&#039;ifxOpen:&#039;, event.detail);
    // Add your handler logic here
  }

  protected handleClose(event: CustomEvent) {
    console.log(&#039;ifxClose:&#039;, event.detail);
    // Add your handler logic here
  }

  protected handleDropdownMenuItem(event: CustomEvent) {
    console.log(&#039;ifxDropdownMenuItem:&#039;, event.detail);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;div
    (ifxOpen)=&quot;handleOpen(\$any(\$event))&quot;
    (ifxClose)=&quot;handleClose(\$any(\$event))&quot;
    (ifxDropdownMenuItem)=&quot;handleDropdownMenuItem(\$any(\$event))&quot;&gt;
    &lt;ifx-dropdown
      placement=&quot;bottom-start&quot;
      disabled=&quot;false&quot;
      default-open=&quot;false&quot;
      no-close-on-outside-click=&quot;false&quot;
      no-close-on-menu-click=&quot;false&quot;
      no-append-to-body=&quot;false&quot;&gt;
      &lt;ifx-dropdown-trigger-button
        variant=&quot;primary&quot;
        (ifxOpen)=&quot;handleOpen(\$any(\$event))&quot;
        (ifxClose)=&quot;handleClose(\$any(\$event))&quot;
        (ifxDropdownMenuItem)=&quot;handleDropdownMenuItem(\$any(\$event))&quot;&gt;
        Dropdown
      &lt;/ifx-dropdown-trigger-button&gt;
      &lt;ifx-dropdown-menu
        size=&quot;m&quot;
        (ifxOpen)=&quot;handleOpen(\$any(\$event))&quot;
        (ifxClose)=&quot;handleClose(\$any(\$event))&quot;
        (ifxDropdownMenuItem)=&quot;handleDropdownMenuItem(\$any(\$event))&quot;&gt;
        &lt;ifx-dropdown-item
          icon=&quot;c-info-16&quot;
          target=&quot;_self&quot;
          href=&quot;true&quot;
          (ifxOpen)=&quot;handleOpen(\$any(\$event))&quot;
          (ifxClose)=&quot;handleClose(\$any(\$event))&quot;
          (ifxDropdownMenuItem)=&quot;handleDropdownMenuItem(\$any(\$event))&quot;&gt;
          Menu Item
        &lt;/ifx-dropdown-item&gt;
        &lt;ifx-dropdown-item
          icon=&quot;c-info-16&quot;
          target=&quot;_self&quot;
          href=&quot;true&quot;&gt;
          Menu Item
        &lt;/ifx-dropdown-item&gt;
        &lt;ifx-dropdown-item
          icon=&quot;c-info-16&quot;
          target=&quot;_self&quot;
          href=&quot;true&quot;&gt;
          Menu Item
        &lt;/ifx-dropdown-item&gt;
        &lt;ifx-dropdown-item
          icon=&quot;c-info-16&quot;
          target=&quot;_self&quot;
          href=&quot;true&quot;&gt;
          Menu Item
        &lt;/ifx-dropdown-item&gt;
        &lt;ifx-dropdown-item
          icon=&quot;c-info-16&quot;
          target=&quot;_self&quot;
          href=&quot;true&quot;&gt;
          Menu Item
        &lt;/ifx-dropdown-item&gt;
      &lt;/ifx-dropdown-menu&gt;
    &lt;/ifx-dropdown&gt;
  &lt;/div&gt;`;

  protected handleOpen(event: CustomEvent) {
    console.log('ifxOpen:', event.detail);
    // Add your handler logic here
  }

  protected handleClose(event: CustomEvent) {
    console.log('ifxClose:', event.detail);
    // Add your handler logic here
  }

  protected handleDropdownMenuItem(event: CustomEvent) {
    console.log('ifxDropdownMenuItem:', event.detail);
    // Add your handler logic here
  }
}
