// examples/vue-example/src/generated/IfxTableExample.vue
<script setup lang="ts">
import { onMounted, nextTick } from 'vue';
import Prism from 'prismjs';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-markup-templating';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';

const codeString = `<script setup lang="ts">
<\/script>

<template>
  <div>
    <ifx-table
      row-height="default"
      cols='[{"headerName":"Make","field":"make","sortable":true,"sort":"desc","unSortIcon":true},{"headerName":"Model","field":"model","sortable":true,"unSortIcon":true},{"headerName":"Price","field":"price"},{"headerName":"Age","field":"age"}]'
      rows='[{"make":"Toyota","model":"Celica","price":35000,"age":10},{"make":"Ford","model":"Mondeo","price":32000,"age":12},{"make":"Porsche","model":"Boxster","price":72000},{"make":"Bmw","model":"x","price":72000},{"make":"Mercedes","model":"y","price":72000},{"make":"Ferrari","model":"z","price":72000},{"make":"Chrysler","model":"a","price":72000},{"make":"Range rover","model":"b","price":72000},{"make":"Tesla","model":"x","price":72000},{"make":"Audi","model":"3","price":72000},{"make":"Landrover","model":"x","price":72000}]'
      table-height="auto"
      pagination="true"
      server-side-pagination="false"
      pagination-items-per-page='[{"value":"10","selected":true}, {"value":"20","selected":false}, {"value":"30","selected":false}]'
      filter-orientation="none"
      variant="default" />
  </div>
<\/template>`;

onMounted(() => {
  nextTick(() => {
    Prism.highlightAll();
  });
});
</script>

<template>
  <div>
    <ifx-table
      row-height="default"
      cols='[{"headerName":"Make","field":"make","sortable":true,"sort":"desc","unSortIcon":true},{"headerName":"Model","field":"model","sortable":true,"unSortIcon":true},{"headerName":"Price","field":"price"},{"headerName":"Age","field":"age"}]'
      rows='[{"make":"Toyota","model":"Celica","price":35000,"age":10},{"make":"Ford","model":"Mondeo","price":32000,"age":12},{"make":"Porsche","model":"Boxster","price":72000},{"make":"Bmw","model":"x","price":72000},{"make":"Mercedes","model":"y","price":72000},{"make":"Ferrari","model":"z","price":72000},{"make":"Chrysler","model":"a","price":72000},{"make":"Range rover","model":"b","price":72000},{"make":"Tesla","model":"x","price":72000},{"make":"Audi","model":"3","price":72000},{"make":"Landrover","model":"x","price":72000}]'
      table-height="auto"
      pagination="true"
      server-side-pagination="false"
      pagination-items-per-page='[{"value":"10","selected":true}, {"value":"20","selected":false}, {"value":"30","selected":false}]'
      filter-orientation="none"
      variant="default" />
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-standalone-example/src/app/generated/ifx-table-example/ifx-table-example.ts
import { IfxTable } from '@infineon/infineon-design-system-angular/standalone';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-ifx-table-example',
  imports: [ IfxTable ],
  templateUrl: './ifx-table-example.html',
  styleUrl: './ifx-table-example.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IfxTableExample {
  protected readonly tsCode = `import { IfxTable } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component, CUSTOM_ELEMENTS_SCHEMA } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-table-example&#039;,
  imports: [ IfxTable ],
  templateUrl: &#039;./ifx-table-example.html&#039;,
  styleUrl: &#039;./ifx-table-example.scss&#039;,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IfxTableExample {}`;
  protected readonly htmlCode = `  &lt;ifx-table
    row-height=&quot;default&quot;
    [cols]=&#039;[{&quot;headerName&quot;:&quot;Make&quot;,&quot;field&quot;:&quot;make&quot;,&quot;sortable&quot;:true,&quot;sort&quot;:&quot;desc&quot;,&quot;unSortIcon&quot;:true},{&quot;headerName&quot;:&quot;Model&quot;,&quot;field&quot;:&quot;model&quot;,&quot;sortable&quot;:true,&quot;unSortIcon&quot;:true},{&quot;headerName&quot;:&quot;Price&quot;,&quot;field&quot;:&quot;price&quot;},{&quot;headerName&quot;:&quot;Age&quot;,&quot;field&quot;:&quot;age&quot;}]&#039;
    [rows]=&#039;[{&quot;make&quot;:&quot;Toyota&quot;,&quot;model&quot;:&quot;Celica&quot;,&quot;price&quot;:35000,&quot;age&quot;:10},{&quot;make&quot;:&quot;Ford&quot;,&quot;model&quot;:&quot;Mondeo&quot;,&quot;price&quot;:32000,&quot;age&quot;:12},{&quot;make&quot;:&quot;Porsche&quot;,&quot;model&quot;:&quot;Boxster&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Bmw&quot;,&quot;model&quot;:&quot;x&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Mercedes&quot;,&quot;model&quot;:&quot;y&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Ferrari&quot;,&quot;model&quot;:&quot;z&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Chrysler&quot;,&quot;model&quot;:&quot;a&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Range rover&quot;,&quot;model&quot;:&quot;b&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Tesla&quot;,&quot;model&quot;:&quot;x&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Audi&quot;,&quot;model&quot;:&quot;3&quot;,&quot;price&quot;:72000},{&quot;make&quot;:&quot;Landrover&quot;,&quot;model&quot;:&quot;x&quot;,&quot;price&quot;:72000}]&#039;
    table-height=&quot;auto&quot;
    [pagination]=&quot;true&quot;
    [server-side-pagination]=&quot;false&quot;
    [pagination-items-per-page]=&#039;[{&quot;value&quot;:&quot;10&quot;,&quot;selected&quot;:true}, {&quot;value&quot;:&quot;20&quot;,&quot;selected&quot;:false}, {&quot;value&quot;:&quot;30&quot;,&quot;selected&quot;:false}]&#039;
    filter-orientation=&quot;none&quot;
    variant=&quot;default&quot;&gt;&lt;/ifx-table&gt;`;
}
