// examples/wrapper-components/vue-javascript/src/components/ContentSwitcher.vue
<template>
  <div class="component">
    <h2>Content Switcher</h2>
    <ifx-content-switcher>
      <ifx-content-switcher-item selected>
        <ifx-icon icon="applications-16"></ifx-icon>Item 1
      </ifx-content-switcher-item>
      <ifx-content-switcher-item>
        <ifx-icon icon="applications-16"></ifx-icon>Item 2
      </ifx-content-switcher-item>
      <ifx-content-switcher-item>
        <ifx-icon icon="applications-16"></ifx-icon>Item 3
      </ifx-content-switcher-item>
      <ifx-content-switcher-item>
        <ifx-icon icon="applications-16"></ifx-icon>Item 4
      </ifx-content-switcher-item>
    </ifx-content-switcher>
    <br />
    <br />
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/content-switcher/content-switcher.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-content-switcher',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './content-switcher.component.html',
  styleUrl: './content-switcher.component.scss'
})
export class ContentSwitcherComponent {

}

<h2>Content Switcher</h2>
  <ifx-content-switcher>
    <ifx-content-switcher-item selected>
      <ifx-icon icon="applications-16"></ifx-icon>Item 1
    </ifx-content-switcher-item>
    <ifx-content-switcher-item>
      <ifx-icon icon="applications-16"></ifx-icon>Item 2
    </ifx-content-switcher-item>
    <ifx-content-switcher-item>
      <ifx-icon icon="applications-16"></ifx-icon>Item 3
    </ifx-content-switcher-item>
    <ifx-content-switcher-item>
      <ifx-icon icon="applications-16"></ifx-icon>Item 4
    </ifx-content-switcher-item>
  </ifx-content-switcher>
