// examples/wrapper-components/vue-javascript/src/components/NumberIndicator.vue


<template>
  <div>
    <h2>Number Indicator</h2>
    <ifx-number-indicator inverted="false">{{ number }}</ifx-number-indicator>
    <button @click="increaseNumber">+</button>
    <button @click="decreaseNumber">-</button>
  </div>
</template>

<script setup>
import { ref } from 'vue';

let number = ref(1);


function increaseNumber() {
  number.value = number.value + 1;

}

function decreaseNumber() {
  number.value = number.value - 1;
}
</script>

// packages/components-angular/projects/my-app/src/app/components/number-indicator/number-indicator.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-number-indicator',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './number-indicator.component.html',
  styleUrl: './number-indicator.component.scss'
})
export class NumberIndicatorComponent {
  numberIndicator = 1;

  increaseNumber() {
    this.numberIndicator = this.numberIndicator + 1;

  }

  decreaseNumber() {
    this.numberIndicator = this.numberIndicator - 1;
  }
}

<h2>Number Indicator</h2>
<ifx-number-indicator inverted='false'> {{ numberIndicator }}</ifx-number-indicator>
<button (click)="increaseNumber()">+</button>
<button (click)="decreaseNumber()">-</button>
