// examples/wrapper-components/react-javascript/src/components/NumberIndicator/NumberIndicator.js
import React from 'react';
import { IfxNumberIndicator } from '@infineon/infineon-design-system-react';

function NumberIndicator() {
    return (
        <div>
            <IfxNumberIndicator inverted = "false" color='secondary'>Number Indicator</IfxNumberIndicator>
            <div>
                random text NumberIndicator component
            </div>
        </div>
    );
}

export default NumberIndicator;

// packages/components-angular/projects/my-app/src/app/components/number-indicator/number-indicator.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-number-indicator',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './number-indicator.component.html',
  styleUrl: './number-indicator.component.scss'
})
export class NumberIndicatorComponent {
  numberIndicator = 1;

  increaseNumber() {
    this.numberIndicator = this.numberIndicator + 1;

  }

  decreaseNumber() {
    this.numberIndicator = this.numberIndicator - 1;
  }
}

<h2>Number Indicator</h2>
<ifx-number-indicator inverted='false'> {{ numberIndicator }}</ifx-number-indicator>
<button (click)="increaseNumber()">+</button>
<button (click)="decreaseNumber()">-</button>
