// examples/wrapper-components/vue-typescript/src/components/Breadcrumbs.vue


<template>
  <div>
    <h2>Breadcrumbs</h2>
    <div>
      <ifx-breadcrumb>
        <ifx-breadcrumb-item>
          <ifx-breadcrumb-item-label slot="label" icon="">Breadcrumb 1</ifx-breadcrumb-item-label>
          <ifx-dropdown-menu>
            <ifx-dropdown-item url="http://google.com">Google</ifx-dropdown-item>
            <ifx-dropdown-item url="http://bing.com">Bing</ifx-dropdown-item>
            <ifx-dropdown-item url="http://yahoo.com">Yahoo</ifx-dropdown-item>
            <ifx-dropdown-item url="http://naver.com">Naver</ifx-dropdown-item>
          </ifx-dropdown-menu>
        </ifx-breadcrumb-item>

        <ifx-breadcrumb-item>
          <ifx-breadcrumb-item-label slot="label" icon="">Breadcrumb 2</ifx-breadcrumb-item-label>
          <ifx-dropdown-menu>
          <ifx-dropdown-item url="http://google.com">Google</ifx-dropdown-item>
          <ifx-dropdown-item url="http://bing.com">Bing</ifx-dropdown-item>
          <ifx-dropdown-item url="http://yahoo.com">Yahoo</ifx-dropdown-item>
          <ifx-dropdown-item url="http://naver.com">Naver</ifx-dropdown-item>
          </ifx-dropdown-menu>
        </ifx-breadcrumb-item>

        <ifx-breadcrumb-item>
          <ifx-breadcrumb-item-label slot="label" icon="" url="http://google.com">Breadcrumb 3</ifx-breadcrumb-item-label>
        </ifx-breadcrumb-item>
      </ifx-breadcrumb>
    </div>
    <br />
    <br />
  </div>
</template>

<script setup>


</script>

// examples/wrapper-components/react-typescript/src/components/Breadcrumbs/Breadcrumbs.tsx
import { IfxBreadcrumb, IfxBreadcrumbItem, IfxBreadcrumbItemLabel, IfxDropdownMenu, IfxDropdownItem } from '@infineon/infineon-design-system-react';

function Breadcrumbs() {
  return (
    <div>
      <IfxBreadcrumb>
        <IfxBreadcrumbItem>
          <IfxBreadcrumbItemLabel slot="label" icon="">Breadcrumb 1</IfxBreadcrumbItemLabel>
          <IfxDropdownMenu>
            <IfxDropdownItem url="http://google.com">Google</IfxDropdownItem>
            <IfxDropdownItem url="http://bing.com">Bing</IfxDropdownItem>
            <IfxDropdownItem url="http://yahoo.com">Yahoo</IfxDropdownItem>
            <IfxDropdownItem url="http://naver.com">Naver</IfxDropdownItem>
          </IfxDropdownMenu>
        </IfxBreadcrumbItem>

        <IfxBreadcrumbItem>
          <IfxBreadcrumbItemLabel slot="label" icon="">Breadcrumb 2</IfxBreadcrumbItemLabel>
          <IfxDropdownMenu>
          <IfxDropdownItem url="http://google.com">Google</IfxDropdownItem>
          <IfxDropdownItem url="http://bing.com">Bing</IfxDropdownItem>
          <IfxDropdownItem url="http://yahoo.com">Yahoo</IfxDropdownItem>
          <IfxDropdownItem url="http://naver.com">Naver</IfxDropdownItem>
          </IfxDropdownMenu>
        </IfxBreadcrumbItem>

        <IfxBreadcrumbItem>
          <IfxBreadcrumbItemLabel slot="label" icon="" url="http://google.com">Breadcrumb 3</IfxBreadcrumbItemLabel>
        </IfxBreadcrumbItem>
      </IfxBreadcrumb>
    </div>
  );
}

export default Breadcrumbs;
