// examples/vue-example/src/generated/IfxTextareaExample.vue
<script setup lang="ts">

import { IfxTextarea } from '@infineon/infineon-design-system-vue';

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-textarea
      caption="Caption text, description, error notification"
      :cols=43
      :error="false"
      label="Label Text"
      name="textarea"
      placeholder="Placeholder"
      :required="true"
      :read-only="false"
      resize="both"
      :rows=5
      value=""
      wrap="soft"
      :full-width="false"
      :disabled="false"
      @ifxInput="handleInput" />
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-textarea
      caption="Caption text, description, error notification"
      :cols=43
      :error="false"
      label="Label Text"
      name="textarea"
      placeholder="Placeholder"
      :required="true"
      :read-only="false"
      resize="both"
      :rows=5
      value=""
      wrap="soft"
      :full-width="false"
      :disabled="false"
      @ifxInput="handleInput" />
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-module-example/src/app/generated/ifx-textarea-example/ifx-textarea-example.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-textarea-example',
  templateUrl: './ifx-textarea-example.html',
  styleUrl: './ifx-textarea-example.scss',
  standalone: false
})
export class IfxTextareaExample {
  protected readonly tsCode = `import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-textarea-example&#039;,
  templateUrl: &#039;./ifx-textarea-example.html&#039;,
  styleUrl: &#039;./ifx-textarea-example.scss&#039;,
  standalone: false
})
export class IfxTextareaExample {
  protected handleInput(event: CustomEvent) {
    console.log(&#039;ifxInput:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-textarea
    caption=&quot;Caption text, description, error notification&quot;
    cols=&quot;43&quot;
    [disabled]=&quot;false&quot;
    [error]=&quot;false&quot;
    label=&quot;Label Text&quot;
    name=&quot;textarea&quot;
    placeholder=&quot;Placeholder&quot;
    [required]=&quot;true&quot;
    [readOnly]=&quot;false&quot;
    resize=&quot;both&quot;
    rows=&quot;5&quot;
    value=&quot;&quot;
    wrap=&quot;soft&quot;
    full-width=&quot;false&quot;
    (ifxInput)=&quot;handleInput(\$any(\$event))&quot;&gt;&lt;/ifx-textarea&gt;`;

  protected handleInput(event: CustomEvent) {
    console.log('ifxInput:', event);
    // Add your handler logic here
  }
}
