// examples/wrapper-components/vue-javascript/src/components/SegmentedControl.vue
<template>
    <div>
      <h2>Segmented Control</h2>
      <ifx-segmented-control caption='Caption text to describe the controls' label='Group Label' size='regular'>
        <ifx-segment selected='true' icon='star-16' value='value1'> Label </ifx-segment>
        <ifx-segment icon='star-16' value='value2'> Label </ifx-segment>
        <ifx-segment icon='star-16' value='value3'> Label </ifx-segment>
        <ifx-segment icon='star-16' value='value4'> Label </ifx-segment>
      </ifx-segmented-control>
      <br />
      <br />
    </div>
</template>
  
  <style scoped></style>

// examples/wrapper-components/react-javascript/src/components/SegmentedControl/SegmentedControl.jsx
import { IfxSegmentedControl, IfxSegment } from '@infineon/infineon-design-system-react';

function SegmentedControls() {
    return (
        <div>
            <IfxSegmentedControl caption='Caption text to describe the controls' label='Group Label' size='regular'>
                <IfxSegment selected={true} icon='star16' value='value1'> Label </IfxSegment>
                <IfxSegment icon='star16' value='value2'> Label </IfxSegment>
                <IfxSegment icon='star16' value='value3'> Label </IfxSegment>
                <IfxSegment icon='star16' value='value4'> Label </IfxSegment>
            </IfxSegmentedControl>
        </div>
    )
}

export default SegmentedControls;
