// packages/components-angular/projects/my-app/src/app/components/tabs/tabs.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-tabs',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './tabs.component.html',
  styleUrl: './tabs.component.scss'
})
export class TabsComponent {

  orientation = "horizontal";
  orientations = ["horizontal", "vertical"];
  orientationIndex = 0;

  fullWidth = false;
  disabledTabTwo = true;

  toggleOrientation() {
    this.orientationIndex = (this.orientationIndex + 1) % this.orientations.length;
    this.orientation = this.orientations[this.orientationIndex];
  }

  toggleFullWidth() {
    this.fullWidth = !this.fullWidth;
  }

  toggleDisabled() {
    this.disabledTabTwo = !this.disabledTabTwo;
  }
}

<h2>Tabs</h2>

<ifx-tabs *ngIf="showTabs" [orientation]="orientation" active-tab-index="0" [fullWidth]="fullWidth"><ifx-tab
    header="Tab 1" icon="" icon-position="left">
    Content for Tab #1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam
    bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
    cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
    cursus ipsum, nec egestas odio sapien eget neque.
  </ifx-tab><ifx-tab header="Tab 2" [disabled]="disabledTabTwo" icon="" icon-position="left">
    Content for Tab #2. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam
    bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
    cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
    cursus ipsum, nec egestas odio sapien eget neque.
  </ifx-tab><ifx-tab header="Tab 3" icon="" icon-position="left">
    Content for Tab #3. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam
    bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
    cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
    cursus ipsum, nec egestas odio sapien eget neque.
  </ifx-tab>
</ifx-tabs>

<br>
<br>

<h3 class="controls-title">Controls</h3>
<div class="controls">
  <ifx-button variant="secondary" (click)="toggleOrientation()">Toggle Orientation</ifx-button>
  <ifx-button variant="secondary" (click)="toggleFullWidth()">Toggle Full Width</ifx-button>
  <ifx-button variant="secondary" (click)="toggleDisabled()">Toggle Disabled (Tab 2)</ifx-button>
</div>
<br>

<div class="state">
  <div><b>Orientation:</b> {{ orientation }} </div>
  <div><b>Full Width:</b> {{ fullWidth }} </div>
  <div><b>Disabled Tab 2:</b> {{ disabledTabTwo }} </div>
</div>

// examples/wrapper-components/react-vite-js/src/components/Tabs/Tabs.jsx
import { useState } from 'react';
import { IfxTabs, IfxTab, IfxButton } from '@infineon/infineon-design-system-react';

function Tabs() {
  const orientations = ['horizontal', 'vertical'];

  const [orientationIndex, setOrientationIndex] = useState(0);
  const [fullWidth, setFullWidth] = useState(false);
  const [disabled, setDisabled] = useState(false);

  const tabsKey = `${orientations[orientationIndex]}-${disabled}`;

  const toggleOrientation = () => {
    setOrientationIndex((index) => (index + 1) % orientations.length);
  }

  const toggleFullWidth = () => {
    setFullWidth(prevFullWidth => !prevFullWidth);
  }

  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  return (
    <div className="component">
      <h2>Tabs</h2>
      <IfxTabs
        key={tabsKey}
        orientation={orientations[orientationIndex]}
        active-tab-index="0"
        full-width={fullWidth}
      >
        <IfxTab header="Tab 1">
          Content for Tab #1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxTab>
        <IfxTab header="Tab 2" disabled={disabled}>
          Content for Tab #2. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxTab>
        <IfxTab header="Tab 3">
          Content for Tab #3. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxTab>
      </IfxTabs>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleOrientation}>Toggle Orientation</IfxButton>
        <IfxButton variant="secondary" onClick={toggleFullWidth}>Toggle Full Width</IfxButton>
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled (Tab 2)</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Orientation:</b> {orientations[orientationIndex]}</div>
        <div><b>Full Width:</b> {String(fullWidth)}</div>
        <div><b>Disabled Tab 2:</b> {String(disabled)}</div>
      </div>
    </div>
  );
}

export default Tabs;
