// examples/wrapper-components/vue-javascript/src/components/ProgressBar.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["s", "m"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const showLabel = ref(true);
const progressValue = ref(10);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleShowLabel() {
  showLabel.value = !showLabel.value;
}

function updateProgressOnClick() {
  if (progressValue.value < 100) {
    progressValue.value += 10;
  } else {
    progressValue.value = 10;
  }
}

</script>

<template>
  <div class="component">
    <h2>Progress Bar</h2>
    <ifx-progress-bar :value="progressValue" :size="size" :showLabel="showLabel"></ifx-progress-bar>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="updateProgressOnClick">Update progress</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleShowLabel">Toggle Label</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Size:</b> {{ size }} </div>
      <div><b>ShowLabel:</b> {{ showLabel }}</div>
    </div>
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/progress-bar/progress-bar.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-progress-bar',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './progress-bar.component.html',
  styleUrl: './progress-bar.component.scss'
})
export class ProgressBarComponent {
  progressValue = 10;

  size = "m";
  sizes = ["s", "m"];
  sizeIndex = 1;

  showLabel = true;

  updateProgressOnClick() {
    if (this.progressValue < 100) {
      this.progressValue += 10;
      } else {
      this.progressValue = 10;
    }
  }

    toggleShowLabel() {
    this.showLabel= !this.showLabel;
  }

    toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }
}

<h2>Progress bar</h2>
<ifx-progress-bar [value]="progressValue" [size]="size" [showLabel]="showLabel">
</ifx-progress-bar>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="updateProgressOnClick()">Update progress</ifx-button>
<ifx-button variant="secondary" (click)="toggleSize()">Toggle Size</ifx-button>
<ifx-button variant="secondary" (click)="toggleShowLabel()">Toggle Label</ifx-button>
<br>
<br>
<span><b>Size:</b> {{ size }} </span><br>
<span><b>ShowLabel:</b> {{ showLabel }}</span><br>
