// examples/wrapper-components/vue-javascript/src/components/Sidebar.vue
<template>
  <div class="component">
    <h2>Sidebar</h2>
    <ifx-sidebar application-name="Application Name" collapsible="true" collapsed="false" hide-menu-label="Hide Menu"
      show-header="true" show-footer="true" initial-collapse="true" terms-of-use="https://yourwebsite.com/terms"
      imprint="https://yourwebsite.com/imprint" privacy-policy="https://yourwebsite.com/privacy-policy"
      copyright-text="© 1999 - 2026 Infineon Technologies AG">
      <ifx-sidebar-title>Menu Items</ifx-sidebar-title>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
      <ifx-sidebar-item>
        Section
        <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
        <ifx-sidebar-item icon="image-16">
          Menu Item
          <ifx-sidebar-item>Sub menu item</ifx-sidebar-item>
          <ifx-sidebar-item active="true">Sub menu item</ifx-sidebar-item>
          <ifx-sidebar-item>Sub menu item</ifx-sidebar-item>
        </ifx-sidebar-item>
        <ifx-sidebar-item href="https://google.com" target="_blank">Menu Item</ifx-sidebar-item>
        <ifx-sidebar-item href="https://google.com" target="_blank">Menu Item</ifx-sidebar-item>
      </ifx-sidebar-item>
      <ifx-sidebar-title>Items group</ifx-sidebar-title>
      <ifx-sidebar-item href="https://google.com" target="_self" icon="image-16" number-indicator=""
        isactionitem="false" active="false">Item 1</ifx-sidebar-item>
      <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Item 2</ifx-sidebar-item>
    </ifx-sidebar>
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.scss'
})
export class SidebarComponent {

  handleSidebarNavigationItemClick(event: any) {
    console.log('Sidebar item clicked', event.detail);
  }

}

<h2>Sidebar</h2>
<ifx-sidebar application-name="Application Name" collapsible="true" collapsed="false" hide-menu-label="Hide Menu" show-header="true" show-footer="true" initial-collapse="true" terms-of-use="https://yourwebsite.com/terms" imprint="https://yourwebsite.com/imprint" privacy-policy="https://yourwebsite.com/privacy-policy" copyright-text="© 1999 - 2026 Infineon Technologies AG">
    <ifx-sidebar-title>Menu Items</ifx-sidebar-title>
    <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
    <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
    <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
    <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
    <ifx-sidebar-item>
    Section
    <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Menu Item</ifx-sidebar-item>
    <ifx-sidebar-item icon="image-16">
    Menu Item
    <ifx-sidebar-item>Sub menu item</ifx-sidebar-item>
    <ifx-sidebar-item active="true">Sub menu item</ifx-sidebar-item>
    <ifx-sidebar-item>Sub menu item</ifx-sidebar-item>
    </ifx-sidebar-item>
    <ifx-sidebar-item href="https://google.com" target="_blank">Menu Item</ifx-sidebar-item>
    <ifx-sidebar-item href="https://google.com" target="_blank">Menu Item</ifx-sidebar-item>
    </ifx-sidebar-item>
    <ifx-sidebar-title>Items group</ifx-sidebar-title>
    <ifx-sidebar-item href="https://google.com" target="_self" icon="image-16" number-indicator="" isactionitem="false" active="false">Item 1</ifx-sidebar-item>
    <ifx-sidebar-item href="https://google.com" target="_blank" icon="image-16">Item 2</ifx-sidebar-item>
  </ifx-sidebar>
