// examples/wrapper-components/vue-javascript/src/components/Spinner.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["default", "brand"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const sizes = ["s", "m"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const inverted = ref(false);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleInverted() {
  inverted.value = !inverted.value;
}

</script>

<template>
  <div class="component">
    <h2>Spinner</h2>
    <ifx-spinner aria-label="" :variant="variant" :size="size" :inverted="inverted"></ifx-spinner>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="toggleInverted">Toggle Inverted</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Variant:</b> {{ variant }} </div>
      <div><b>Inverted:</b> {{ inverted }} </div>
      <div><b>Size:</b> {{ size }} </div>
    </div>
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/spinner/spinner.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-spinner',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './spinner.component.html',
  styleUrl: './spinner.component.scss'
})
export class SpinnerComponent {
  inverted = false;

  variant = "default";
  variants = ["default", "brand"];
  variantIndex = 0;

  size = "m";
  sizes = ["s", "m"];
  sizeIndex = 1;

  toggleInverted() {
    this.inverted = !this.inverted;
  }

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }
}

<h2>Spinner</h2>
<ifx-spinner aria-label="" [variant]="variant" [size]="size" [inverted]="inverted"></ifx-spinner>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleVariant()">Toggle Variant</ifx-button>
<ifx-button variant="secondary" (click)="toggleInverted()">Toggle Inverted</ifx-button>
<ifx-button variant="secondary" (click)="toggleSize()">Toggle Size</ifx-button>
<br>
<br>
<span><b>Variant:</b> {{ variant }} </span><br>
<span><b>Inverted:</b> {{ inverted }} </span><br>
<span><b>Size:</b> {{ size }} </span><br>
