// examples/vue-example/src/generated/IfxCardExample.vue
<script setup lang="ts">

import { IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText } from '@infineon/infineon-design-system-vue';

const handleImgPosition = (event: CustomEvent) => {
  console.log('imgPosition:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleImgPosition = (event: CustomEvent) => {
  console.log('imgPosition:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-card
      direction="vertical"
      href=""
      target="_blank"
      aria-label=""
      aria-label-text="Card"
      :full-width="false">
      <ifx-card-image
        position="right"
        src="https://raw.githubusercontent.com/Infineon/public-assets/main/ifx-placeholder.png"
        alt="Default"
        slot="img"
        @imgPosition="handleImgPosition" />
      <ifx-card-overline @imgPosition="handleImgPosition">
        Overline
      </ifx-card-overline>
      <ifx-card-headline @imgPosition="handleImgPosition">
        Headline
      </ifx-card-headline>
      <ifx-card-text @imgPosition="handleImgPosition">
        Some quick example text to build on the card title and make up the bulk of the card's content.
      </ifx-card-text>
      <ifx-card-links
        slot="buttons"
        @imgPosition="handleImgPosition">
        <ifx-button variant="primary">
          Button
        </ifx-button>
        <ifx-button variant="secondary">
          Button
        </ifx-button>
      </ifx-card-links>
    </ifx-card>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-card
      direction="vertical"
      href=""
      target="_blank"
      aria-label=""
      aria-label-text="Card"
      :full-width="false">
      <ifx-card-image
        position="right"
        src="https://raw.githubusercontent.com/Infineon/public-assets/main/ifx-placeholder.png"
        alt="Default"
        slot="img"
        @imgPosition="handleImgPosition" />
      <ifx-card-overline @imgPosition="handleImgPosition">
        Overline
      </ifx-card-overline>
      <ifx-card-headline @imgPosition="handleImgPosition">
        Headline
      </ifx-card-headline>
      <ifx-card-text @imgPosition="handleImgPosition">
        Some quick example text to build on the card title and make up the bulk of the card's content.
      </ifx-card-text>
      <ifx-card-links
        slot="buttons"
        @imgPosition="handleImgPosition">
        <ifx-button variant="primary">
          Button
        </ifx-button>
        <ifx-button variant="secondary">
          Button
        </ifx-button>
      </ifx-card-links>
    </ifx-card>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/react-example/src/generated/IfxCardExample.tsx
import { IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText } from '@infineon/infineon-design-system-react';

export function IfxCardExample() {
  const handleImgPosition = (event: CustomEvent) => {
    console.log('imgPosition:', event);
    // Add your handler logic here
  };

  return (
    <>
      <IfxCard
        actionsPlacement="default"
        fullWidth={false}
        direction="vertical"
        href=""
        target="_blank"
        ariaLabel=""
        ariaLabelText="Card">
        <IfxCardImage
          objectFit="cover"
          position="right"
          src="https://raw.githubusercontent.com/Infineon/public-assets/main/ifx-placeholder.png"
          alt="Default"
          slot="img"
          onImgPosition={handleImgPosition} />
        <IfxCardOverline>
          Overline
        </IfxCardOverline>
        <IfxCardHeadline>
          Headline
        </IfxCardHeadline>
        <IfxCardText>
          Some quick example text to build on the card title and make up the bulk of the card's content.
        </IfxCardText>
        <IfxCardLinks slot="buttons">
          <IfxButton variant="primary">
            Button
          </IfxButton>
          <IfxButton variant="secondary">
            Button
          </IfxButton>
        </IfxCardLinks>
      </IfxCard>
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText } from '@infineon/infineon-design-system-react';

export function IfxCardExample() {
  const handleImgPosition = (event: CustomEvent) => {
    console.log('imgPosition:', event);
    // Add your handler logic here
  };

  return (
      <IfxCard
        actionsPlacement="default"
        fullWidth={false}
        direction="vertical"
        href=""
        target="_blank"
        ariaLabel=""
        ariaLabelText="Card">
        <IfxCardImage
          objectFit="cover"
          position="right"
          src="https://raw.githubusercontent.com/Infineon/public-assets/main/ifx-placeholder.png"
          alt="Default"
          slot="img"
          onImgPosition={handleImgPosition} />
        <IfxCardOverline>
          Overline
        </IfxCardOverline>
        <IfxCardHeadline>
          Headline
        </IfxCardHeadline>
        <IfxCardText>
          Some quick example text to build on the card title and make up the bulk of the card's content.
        </IfxCardText>
        <IfxCardLinks slot="buttons">
          <IfxButton variant="primary">
            Button
          </IfxButton>
          <IfxButton variant="secondary">
            Button
          </IfxButton>
        </IfxCardLinks>
      </IfxCard>
  );
}`;
