// examples/vue-example/src/generated/IfxErrorPageExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxErrorPage, IfxTextField } from '@infineon/infineon-design-system-vue';

const typeOptions = ["403","404","503","maintenance"];
const typeIndex = ref(0);
const illustrationUrl = ref("");
const imgAlt = ref("");
const headline = ref("");
const description = ref("");

const handleTypeChange = () => { typeIndex.value = (typeIndex.value + 1) % typeOptions.length; };
const handleIllustrationUrlChange = (nextValue: string) => { illustrationUrl.value = nextValue; };
const handleImgAltChange = (nextValue: string) => { imgAlt.value = nextValue; };
const handleHeadlineChange = (nextValue: string) => { headline.value = nextValue; };
const handleDescriptionChange = (nextValue: string) => { description.value = nextValue; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "type": typeOptions[typeIndex.value],
  "illustrationUrl": illustrationUrl.value,
  "imgAlt": imgAlt.value,
  "headline": headline.value,
  "description": description.value,
}));

const getInputValue = (event: Event) => String((event.target as HTMLInputElement | null)?.value ?? "");

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["type", typeOptions[typeIndex.value]],
  ["illustrationUrl", illustrationUrl.value],
  ["imgAlt", imgAlt.value],
  ["headline", headline.value],
  ["description", description.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxButton, IfxErrorPage } from '@infineon/infineon-design-system-vue';
${'</'}script>

<template>
  <div>
    <ifx-error-page __CONTROLLED_PROPS__>
      <div slot="button">
        <ifx-button
          variant="primary"
          :full-width="true">
          Go to homepage
        </ifx-button>
      </div>
      <div slot="button">
        <ifx-button
          variant="secondary"
          :full-width="true">
          Get support
        </ifx-button>
      </div>
    </ifx-error-page>
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-error-page v-bind="controlledProps">
      <div slot="button">
        <ifx-button
          variant="primary"
          :full-width="true">
          Go to homepage
        </ifx-button>
      </div>
      <div slot="button">
        <ifx-button
          variant="secondary"
          :full-width="true">
          Get support
        </ifx-button>
      </div>
    </ifx-error-page>
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="handleTypeChange">Toggle Type</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="illustrationUrl" type="text" :value="String(illustrationUrl)" @input="handleIllustrationUrlChange(getInputValue($event))" />
        <ifx-text-field label="imgAlt" type="text" :value="String(imgAlt)" @input="handleImgAltChange(getInputValue($event))" />
        <ifx-text-field label="headline" type="text" :value="String(headline)" @input="handleHeadlineChange(getInputValue($event))" />
        <ifx-text-field label="description" type="text" :value="String(description)" @input="handleDescriptionChange(getInputValue($event))" />
    </div>

    <div class="state">
      <div><b>type:</b> {{ String(typeOptions[typeIndex]) }}</div>
      <div><b>illustrationUrl:</b> {{ String(illustrationUrl) }}</div>
      <div><b>imgAlt:</b> {{ String(imgAlt) }}</div>
      <div><b>headline:</b> {{ String(headline) }}</div>
      <div><b>description:</b> {{ String(description) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/react-example/src/generated/IfxErrorPageExample.tsx
import { useState } from 'react';
import { IfxButton, IfxErrorPage, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxErrorPageExample() {
  const typeOptions = ["403","404","503","maintenance"];
  const [typeIndex, setTypeIndex] = useState(0);
  const [illustrationUrl, setIllustrationUrl] = useState("");
  const [imgAlt, setImgAlt] = useState("");
  const [headline, setHeadline] = useState("");
  const [description, setDescription] = useState("");

  const handleTypeChange = () => setTypeIndex((i) => (i + 1) % typeOptions.length);
  const handleIllustrationUrlChange = (value: string) => setIllustrationUrl(value);
  const handleImgAltChange = (value: string) => setImgAlt(value);
  const handleHeadlineChange = (value: string) => setHeadline(value);
  const handleDescriptionChange = (value: string) => setDescription(value);

  const controlledProps = {
    "type": typeOptions[typeIndex],
    "illustrationUrl": illustrationUrl,
    "imgAlt": imgAlt,
    "headline": headline,
    "description": description,
  } as Record<string, unknown>;
  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["type", controlledProps["type"]],
    ["illustrationUrl", controlledProps["illustrationUrl"]],
    ["imgAlt", controlledProps["imgAlt"]],
    ["headline", controlledProps["headline"]],
    ["description", controlledProps["description"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxButton, IfxErrorPage } from '@infineon/infineon-design-system-react';

export function IfxErrorPageExample() {
  return (
      <IfxErrorPage __CONTROLLED_PROPS__>
        <div slot="button">
          <IfxButton
            variant="primary"
            fullWidth={true}>
            Go to homepage
          </IfxButton>
        </div>
        <div slot="button">
          <IfxButton
            variant="secondary"
            fullWidth={true}>
            Get support
          </IfxButton>
        </div>
      </IfxErrorPage>
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxErrorPage {...(controlledProps as any)}>
        <div slot="button">
          <IfxButton
            variant="primary"
            fullWidth={true}>
            Go to homepage
          </IfxButton>
        </div>
        <div slot="button">
          <IfxButton
            variant="secondary"
            fullWidth={true}>
            Get support
          </IfxButton>
        </div>
      </IfxErrorPage>
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={handleTypeChange}>Toggle Type</IfxButton>
	      </div>
	      <div className="controls controls-input">
        <IfxTextField label="illustrationUrl" type="text" value={String(illustrationUrl)} onInput={(event) => handleIllustrationUrlChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="imgAlt" type="text" value={String(imgAlt)} onInput={(event) => handleImgAltChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="headline" type="text" value={String(headline)} onInput={(event) => handleHeadlineChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="description" type="text" value={String(description)} onInput={(event) => handleDescriptionChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
	      </div>

	      <div className="state">
	          <div><b>type:</b> {String(typeOptions[typeIndex])}</div>
          <div><b>illustrationUrl:</b> {String(illustrationUrl)}</div>
          <div><b>imgAlt:</b> {String(imgAlt)}</div>
          <div><b>headline:</b> {String(headline)}</div>
          <div><b>description:</b> {String(description)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}
