// examples/angular-standalone-example/src/app/generated/ifx-footer-example/ifx-footer-example.ts
import { IfxFooter, IfxIcon, IfxLink } from '@infineon/infineon-design-system-angular/standalone';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-ifx-footer-example',
  imports: [ IfxFooter, IfxIcon, IfxLink ],
  templateUrl: './ifx-footer-example.html',
  styleUrl: './ifx-footer-example.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IfxFooterExample {
  protected readonly tsCode = `import { IfxFooter, IfxIcon, IfxLink } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component, CUSTOM_ELEMENTS_SCHEMA } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-footer-example&#039;,
  imports: [ IfxFooter, IfxIcon, IfxLink ],
  templateUrl: &#039;./ifx-footer-example.html&#039;,
  styleUrl: &#039;./ifx-footer-example.scss&#039;,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IfxFooterExample {}`;
  protected readonly htmlCode = `  &lt;ifx-footer copyright-text=&quot;© 1999 - 2024 Infineon Technologies AG&quot;&gt;
    &lt;div slot=&quot;socials&quot;&gt;
      &lt;ifx-link
        variant=&quot;title&quot;
        href=&quot;http://infineon.com&quot;
        aria-label=&quot;Go to Homepage&quot;&gt;
        &lt;ifx-icon icon=&quot;home-16&quot;&gt;&lt;/ifx-icon&gt;
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;title&quot;
        href=&quot;http://facebook.com/infineon&quot;
        aria-label=&quot;Follow us on Facebook&quot;&gt;
        &lt;ifx-icon icon=&quot;facebook&quot;&gt;&lt;/ifx-icon&gt;
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;title&quot;
        href=&quot;http://youtube.com/infineon&quot;
        aria-label=&quot;Follow us on Youtube&quot;&gt;
        &lt;ifx-icon icon=&quot;youtube&quot;&gt;&lt;/ifx-icon&gt;
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;title&quot;
        href=&quot;http://instagram.com/infineon&quot;
        aria-label=&quot;Follow us on Instagram&quot;&gt;
        &lt;ifx-icon icon=&quot;instagram&quot;&gt;&lt;/ifx-icon&gt;
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;title&quot;
        href=&quot;http://linkedin.com/infineon&quot;
        aria-label=&quot;Follow us on LinkedIn&quot;&gt;
        &lt;ifx-icon icon=&quot;linkedin&quot;&gt;&lt;/ifx-icon&gt;
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;title&quot;
        href=&quot;http://xing.com/infineon&quot;
        aria-label=&quot;Follow us on Xing&quot;&gt;
        &lt;ifx-icon icon=&quot;xing&quot;&gt;&lt;/ifx-icon&gt;
      &lt;/ifx-link&gt;
    &lt;/div&gt;
    &lt;div slot=&quot;info&quot;&gt;
      &lt;ifx-link
        variant=&quot;menu&quot;
        href=&quot;https://yourwebsite.com/terms&quot;
        target=&quot;_blank&quot;&gt;
        Terms
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;menu&quot;
        href=&quot;https://yourwebsite.com/imprint&quot;
        target=&quot;_blank&quot;&gt;
        Imprint
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;menu&quot;
        href=&quot;https://yourwebsite.com/privacy-policy&quot;
        target=&quot;_blank&quot;&gt;
        Privacy policy
      &lt;/ifx-link&gt;
      &lt;ifx-link
        variant=&quot;menu&quot;
        href=&quot;https://yourwebsite.com/glossary&quot;
        target=&quot;_blank&quot;&gt;
        Glossary
      &lt;/ifx-link&gt;
    &lt;/div&gt;
  &lt;/ifx-footer&gt;`;
}

// examples/react-example/src/generated/IfxFooterExample.tsx
import {
	IfxFooter,
	IfxIcon,
	IfxLink,
} from "@infineon/infineon-design-system-react";

export function IfxFooterExample() {
	return (
		<>
			<IfxFooter copyrightText="© 1999 - 2024 Infineon Technologies AG">
				<div slot="socials">
					<IfxLink
						variant="title"
						href="http://infineon.com"
						ariaLabel="Go to Homepage"
					>
						<IfxIcon icon="home-16" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://facebook.com/infineon"
						ariaLabel="Follow us on Facebook"
					>
						<IfxIcon icon="facebook" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://youtube.com/infineon"
						ariaLabel="Follow us on Youtube"
					>
						<IfxIcon icon="youtube" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://instagram.com/infineon"
						ariaLabel="Follow us on Instagram"
					>
						<IfxIcon icon="instagram" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://linkedin.com/infineon"
						ariaLabel="Follow us on LinkedIn"
					>
						<IfxIcon icon="linkedin" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://xing.com/infineon"
						ariaLabel="Follow us on Xing"
					>
						<IfxIcon icon="xing" />
					</IfxLink>
				</div>
				<div slot="info">
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/terms"
						target="_blank"
					>
						Terms
					</IfxLink>
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/imprint"
						target="_blank"
					>
						Imprint
					</IfxLink>
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/privacy-policy"
						target="_blank"
					>
						Privacy policy
					</IfxLink>
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/glossary"
						target="_blank"
					>
						Glossary
					</IfxLink>
				</div>
			</IfxFooter>
			<details className="code-details">
				<summary>View Code</summary>
				<pre>
					<code className="language-tsx">{codeString}</code>
				</pre>
			</details>
		</>
	);
}

const codeString = `import { IfxFooter, IfxIcon, IfxLink } from '@infineon/infineon-design-system-react';

export function IfxFooterExample() {
  return (
      <IfxFooter copyrightText="© 1999 - 2024 Infineon Technologies AG">
        <div slot="socials">
          <IfxLink
            variant="title"
            href="http://infineon.com"
            ariaLabel="Go to Homepage">
            <IfxIcon icon="home-16" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://facebook.com/infineon"
            ariaLabel="Follow us on Facebook">
            <IfxIcon icon="facebook" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://youtube.com/infineon"
            ariaLabel="Follow us on Youtube">
            <IfxIcon icon="youtube" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://instagram.com/infineon"
            ariaLabel="Follow us on Instagram">
            <IfxIcon icon="instagram" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://linkedin.com/infineon"
            ariaLabel="Follow us on LinkedIn">
            <IfxIcon icon="linkedin" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://xing.com/infineon"
            ariaLabel="Follow us on Xing">
            <IfxIcon icon="xing" />
          </IfxLink>
        </div>
        <div slot="info">
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/terms"
            target="_blank">
            Terms
          </IfxLink>
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/imprint"
            target="_blank">
            Imprint
          </IfxLink>
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/privacy-policy"
            target="_blank">
            Privacy policy
          </IfxLink>
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/glossary"
            target="_blank">
            Glossary
          </IfxLink>
        </div>
      </IfxFooter>
  );
}`;
