// examples/angular-module-example/src/app/generated/ifx-radio-button-group-example/ifx-radio-button-group-example.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-radio-button-group-example',
  templateUrl: './ifx-radio-button-group-example.html',
  styleUrl: './ifx-radio-button-group-example.scss',
  standalone: false
})
export class IfxRadioButtonGroupExample {
  protected readonly tsCode = `import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-radio-button-group-example&#039;,
  templateUrl: &#039;./ifx-radio-button-group-example.html&#039;,
  styleUrl: &#039;./ifx-radio-button-group-example.scss&#039;,
  standalone: false
})
export class IfxRadioButtonGroupExample {
  protected handleSetGroupError(event: CustomEvent) {
    console.log(&#039;setGroupError:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-radio-button-group
    alignment=&quot;vertical&quot;
    .showgrouplabel=&quot;false&quot;
    group-label-text=&quot;Group Label&quot;
    .showcaption=&quot;false&quot;
    caption-text=&quot;Caption text, description, error notification&quot;
    .showcaptionicon=&quot;false&quot;
    .required=&quot;false&quot;&gt;
    &lt;ifx-radio-button
      value=&quot;0&quot;
      .disabled=&quot;false&quot;
      .checked=&quot;false&quot;
      .error=&quot;false&quot;
      size=&quot;m&quot;&gt;
      Option 0
    &lt;/ifx-radio-button&gt;
    &lt;ifx-radio-button
      value=&quot;1&quot;
      size=&quot;m&quot;&gt;
      Option 1
    &lt;/ifx-radio-button&gt;
    &lt;ifx-radio-button
      value=&quot;2&quot;
      size=&quot;m&quot;&gt;
      Option 2
    &lt;/ifx-radio-button&gt;
  &lt;/ifx-radio-button-group&gt;`;

  protected handleSetGroupError(event: CustomEvent) {
    console.log('setGroupError:', event);
    // Add your handler logic here
  }
}

// examples/react-example/src/generated/IfxRadioButtonGroupExample.tsx
import { IfxRadioButton, IfxRadioButtonGroup } from '@infineon/infineon-design-system-react';

export function IfxRadioButtonGroupExample() {
  const handleSetGroupError = (event: CustomEvent) => {
    console.log('setGroupError:', event);
    // Add your handler logic here
  };

  return (
    <>
      <IfxRadioButtonGroup
        alignment="vertical"
        .showgrouplabel={false}
        groupLabelText="Group Label"
        .showcaption={false}
        captionText="Caption text, description, error notification"
        .showcaptionicon={false}
        .required={false}>
        <IfxRadioButton
          value={0}
          .disabled={false}
          .checked={false}
          .error={false}
          size="m">
          Option 0
        </IfxRadioButton>
        <IfxRadioButton
          value={1}
          size="m">
          Option 1
        </IfxRadioButton>
        <IfxRadioButton
          value={2}
          size="m">
          Option 2
        </IfxRadioButton>
      </IfxRadioButtonGroup>
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { IfxRadioButton, IfxRadioButtonGroup } from '@infineon/infineon-design-system-react';

export function IfxRadioButtonGroupExample() {
  const handleSetGroupError = (event: CustomEvent) => {
    console.log('setGroupError:', event);
    // Add your handler logic here
  };

  return (
      <IfxRadioButtonGroup
        alignment="vertical"
        .showgrouplabel={false}
        groupLabelText="Group Label"
        .showcaption={false}
        captionText="Caption text, description, error notification"
        .showcaptionicon={false}
        .required={false}>
        <IfxRadioButton
          value={0}
          .disabled={false}
          .checked={false}
          .error={false}
          size="m">
          Option 0
        </IfxRadioButton>
        <IfxRadioButton
          value={1}
          size="m">
          Option 1
        </IfxRadioButton>
        <IfxRadioButton
          value={2}
          size="m">
          Option 2
        </IfxRadioButton>
      </IfxRadioButtonGroup>
  );
}`;
