// examples/vue-example/src/generated/IfxRadioButtonGroupExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxRadioButton, IfxRadioButtonGroup, IfxTextField } from '@infineon/infineon-design-system-vue';

const amountOfItems = ref(3);
const alignmentOptions = ["vertical","horizontal"];
const alignmentIndex = ref(0);
const sizeOptions = ["s","m"];
const sizeIndex = ref(1);
const checked = ref(false);
const disabled = ref(false);
const error = ref(false);
const name = ref("radio-group");
const showGroupLabel = ref(false);
const groupLabelText = ref("Group Label");
const showCaption = ref(false);
const captionText = ref("Caption text, description, error notification");
const showCaptionIcon = ref(false);
const required = ref(false);

const toggleAmountOfItems = (nextValue: string) => { amountOfItems.value = Number(nextValue); };
const toggleAlignment = () => { alignmentIndex.value = (alignmentIndex.value + 1) % alignmentOptions.length; };
const toggleSize = () => { sizeIndex.value = (sizeIndex.value + 1) % sizeOptions.length; };
const toggleChecked = () => { checked.value = !checked.value; };
const toggleDisabled = () => { disabled.value = !disabled.value; };
const toggleError = () => { error.value = !error.value; };
const toggleName = (nextValue: string) => { name.value = nextValue; };
const toggleShowGroupLabel = () => { showGroupLabel.value = !showGroupLabel.value; };
const toggleGroupLabelText = (nextValue: string) => { groupLabelText.value = nextValue; };
const toggleShowCaption = () => { showCaption.value = !showCaption.value; };
const toggleCaptionText = (nextValue: string) => { captionText.value = nextValue; };
const toggleShowCaptionIcon = () => { showCaptionIcon.value = !showCaptionIcon.value; };
const toggleRequired = () => { required.value = !required.value; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "amountOfItems": amountOfItems.value,
  "alignment": alignmentOptions[alignmentIndex.value],
  "size": sizeOptions[sizeIndex.value],
  "checked": checked.value,
  "disabled": disabled.value,
  "error": error.value,
  "name": name.value,
  "showGroupLabel": showGroupLabel.value,
  "groupLabelText": groupLabelText.value,
  "showCaption": showCaption.value,
  "captionText": captionText.value,
  "showCaptionIcon": showCaptionIcon.value,
  "required": required.value,
}));

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const handleError = (event: CustomEvent) => {
  console.log('ifxError:', event);
  // Add your handler logic here
};

const getInputValue = (event: Event) => String((event.target as HTMLInputElement | null)?.value ?? "");

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["amountOfItems", amountOfItems.value],
  ["alignment", alignmentOptions[alignmentIndex.value]],
  ["size", sizeOptions[sizeIndex.value]],
  ["checked", checked.value],
  ["disabled", disabled.value],
  ["error", error.value],
  ["name", name.value],
  ["showGroupLabel", showGroupLabel.value],
  ["groupLabelText", groupLabelText.value],
  ["showCaption", showCaption.value],
  ["captionText", captionText.value],
  ["showCaptionIcon", showCaptionIcon.value],
  ["required", required.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxRadioButton, IfxRadioButtonGroup } from '@infineon/infineon-design-system-vue';

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const handleError = (event: CustomEvent) => {
  console.log('ifxError:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-radio-button-group __CONTROLLED_PROPS__>
      <ifx-radio-button
        :value="0"
        size="m"
        @ifxChange="handleChange"
        @ifxError="handleError">
        Option 0
      </ifx-radio-button>
      <ifx-radio-button
        :value="1"
        size="m">
        Option 1
      </ifx-radio-button>
      <ifx-radio-button
        :value="2"
        size="m">
        Option 2
      </ifx-radio-button>
    </ifx-radio-button-group>
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-radio-button-group v-bind="controlledProps">
      <ifx-radio-button
        :value="0"
        size="m"
        @ifxChange="handleChange"
        @ifxError="handleError">
        Option 0
      </ifx-radio-button>
      <ifx-radio-button
        :value="1"
        size="m">
        Option 1
      </ifx-radio-button>
      <ifx-radio-button
        :value="2"
        size="m">
        Option 2
      </ifx-radio-button>
    </ifx-radio-button-group>
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="toggleAlignment">Toggle Alignment</ifx-button>
        <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
        <ifx-button variant="secondary" @click="toggleChecked">Toggle Checked</ifx-button>
        <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
        <ifx-button variant="secondary" @click="toggleError">Toggle Error</ifx-button>
        <ifx-button variant="secondary" @click="toggleShowGroupLabel">Toggle ShowGroupLabel</ifx-button>
        <ifx-button variant="secondary" @click="toggleShowCaption">Toggle ShowCaption</ifx-button>
        <ifx-button variant="secondary" @click="toggleShowCaptionIcon">Toggle ShowCaptionIcon</ifx-button>
        <ifx-button variant="secondary" @click="toggleRequired">Toggle Required</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="amountOfItems" type="text" :value="String(amountOfItems)" @input="toggleAmountOfItems(getInputValue($event))" />
        <ifx-text-field label="name" type="text" :value="String(name)" @input="toggleName(getInputValue($event))" />
        <ifx-text-field label="groupLabelText" type="text" :value="String(groupLabelText)" @input="toggleGroupLabelText(getInputValue($event))" />
        <ifx-text-field label="captionText" type="text" :value="String(captionText)" @input="toggleCaptionText(getInputValue($event))" />
    </div>

    <div class="state">
      <div><b>amountOfItems:</b> {{ String(amountOfItems) }}</div>
      <div><b>alignment:</b> {{ String(alignmentOptions[alignmentIndex]) }}</div>
      <div><b>size:</b> {{ String(sizeOptions[sizeIndex]) }}</div>
      <div><b>checked:</b> {{ String(checked) }}</div>
      <div><b>disabled:</b> {{ String(disabled) }}</div>
      <div><b>error:</b> {{ String(error) }}</div>
      <div><b>name:</b> {{ String(name) }}</div>
      <div><b>showGroupLabel:</b> {{ String(showGroupLabel) }}</div>
      <div><b>groupLabelText:</b> {{ String(groupLabelText) }}</div>
      <div><b>showCaption:</b> {{ String(showCaption) }}</div>
      <div><b>captionText:</b> {{ String(captionText) }}</div>
      <div><b>showCaptionIcon:</b> {{ String(showCaptionIcon) }}</div>
      <div><b>required:</b> {{ String(required) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/react-example/src/generated/IfxRadioButtonGroupExample.tsx
import { useState } from 'react';
import { IfxButton, IfxRadioButton, IfxRadioButtonGroup, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxRadioButtonGroupExample() {
  const [amountOfItems, setAmountOfItems] = useState(3);
  const alignmentOptions = ["vertical","horizontal"];
  const [alignmentIndex, setAlignmentIndex] = useState(0);
  const sizeOptions = ["s","m"];
  const [sizeIndex, setSizeIndex] = useState(1);
  const [checked, setChecked] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [error, setError] = useState(false);
  const [name, setName] = useState("radio-group");
  const [showGroupLabel, setShowGroupLabel] = useState(false);
  const [groupLabelText, setGroupLabelText] = useState("Group Label");
  const [showCaption, setShowCaption] = useState(false);
  const [captionText, setCaptionText] = useState("Caption text, description, error notification");
  const [showCaptionIcon, setShowCaptionIcon] = useState(false);
  const [required, setRequired] = useState(false);

  const toggleAmountOfItems = (value: string) => setAmountOfItems(Number(value));
  const toggleAlignment = () => setAlignmentIndex((i) => (i + 1) % alignmentOptions.length);
  const toggleSize = () => setSizeIndex((i) => (i + 1) % sizeOptions.length);
  const toggleChecked = () => setChecked((v) => !v);
  const toggleDisabled = () => setDisabled((v) => !v);
  const toggleError = () => setError((v) => !v);
  const toggleName = (value: string) => setName(value);
  const toggleShowGroupLabel = () => setShowGroupLabel((v) => !v);
  const toggleGroupLabelText = (value: string) => setGroupLabelText(value);
  const toggleShowCaption = () => setShowCaption((v) => !v);
  const toggleCaptionText = (value: string) => setCaptionText(value);
  const toggleShowCaptionIcon = () => setShowCaptionIcon((v) => !v);
  const toggleRequired = () => setRequired((v) => !v);

  const controlledProps = {
    "amountOfItems": amountOfItems,
    "alignment": alignmentOptions[alignmentIndex],
    "size": sizeOptions[sizeIndex],
    "checked": checked,
    "disabled": disabled,
    "error": error,
    "name": name,
    "showGroupLabel": showGroupLabel,
    "groupLabelText": groupLabelText,
    "showCaption": showCaption,
    "captionText": captionText,
    "showCaptionIcon": showCaptionIcon,
    "required": required,
  } as Record<string, unknown>;
  const handleSetGroupError = (event: CustomEvent) => {
    console.log('setGroupError:', event);
    // Add your handler logic here
  };

  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["amountOfItems", controlledProps["amountOfItems"]],
    ["alignment", controlledProps["alignment"]],
    ["size", controlledProps["size"]],
    ["checked", controlledProps["checked"]],
    ["disabled", controlledProps["disabled"]],
    ["error", controlledProps["error"]],
    ["name", controlledProps["name"]],
    ["showGroupLabel", controlledProps["showGroupLabel"]],
    ["groupLabelText", controlledProps["groupLabelText"]],
    ["showCaption", controlledProps["showCaption"]],
    ["captionText", controlledProps["captionText"]],
    ["showCaptionIcon", controlledProps["showCaptionIcon"]],
    ["required", controlledProps["required"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxRadioButton, IfxRadioButtonGroup } from '@infineon/infineon-design-system-react';

export function IfxRadioButtonGroupExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  const handleError = (event: CustomEvent) => {
    console.log('ifxError:', event);
    // Add your handler logic here
  };

  return (
      <IfxRadioButtonGroup __CONTROLLED_PROPS__>
        <IfxRadioButton
          value={0}
          size="m"
          onIfxChange={handleChange}
          onIfxError={handleError}>
          Option 0
        </IfxRadioButton>
        <IfxRadioButton
          value={1}
          size="m">
          Option 1
        </IfxRadioButton>
        <IfxRadioButton
          value={2}
          size="m">
          Option 2
        </IfxRadioButton>
      </IfxRadioButtonGroup>
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxRadioButtonGroup {...(controlledProps as any)}>
        <IfxRadioButton
          value={0}
          size="m">
          Option 0
        </IfxRadioButton>
        <IfxRadioButton
          value={1}
          size="m">
          Option 1
        </IfxRadioButton>
        <IfxRadioButton
          value={2}
          size="m">
          Option 2
        </IfxRadioButton>
      </IfxRadioButtonGroup>
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={toggleAlignment}>Toggle Alignment</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={toggleChecked}>Toggle Checked</IfxButton>
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={toggleError}>Toggle Error</IfxButton>
        <IfxButton variant="secondary" onClick={toggleShowGroupLabel}>Toggle ShowGroupLabel</IfxButton>
        <IfxButton variant="secondary" onClick={toggleShowCaption}>Toggle ShowCaption</IfxButton>
        <IfxButton variant="secondary" onClick={toggleShowCaptionIcon}>Toggle ShowCaptionIcon</IfxButton>
        <IfxButton variant="secondary" onClick={toggleRequired}>Toggle Required</IfxButton>
	      </div>
	      <div className="controls controls-input">
        <IfxTextField label="amountOfItems" type="text" value={String(amountOfItems)} onInput={(event) => toggleAmountOfItems(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="name" type="text" value={String(name)} onInput={(event) => toggleName(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="groupLabelText" type="text" value={String(groupLabelText)} onInput={(event) => toggleGroupLabelText(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="captionText" type="text" value={String(captionText)} onInput={(event) => toggleCaptionText(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
	      </div>

	      <div className="state">
	          <div><b>amountOfItems:</b> {String(amountOfItems)}</div>
          <div><b>alignment:</b> {String(alignmentOptions[alignmentIndex])}</div>
          <div><b>size:</b> {String(sizeOptions[sizeIndex])}</div>
          <div><b>checked:</b> {String(checked)}</div>
          <div><b>disabled:</b> {String(disabled)}</div>
          <div><b>error:</b> {String(error)}</div>
          <div><b>name:</b> {String(name)}</div>
          <div><b>showGroupLabel:</b> {String(showGroupLabel)}</div>
          <div><b>groupLabelText:</b> {String(groupLabelText)}</div>
          <div><b>showCaption:</b> {String(showCaption)}</div>
          <div><b>captionText:</b> {String(captionText)}</div>
          <div><b>showCaptionIcon:</b> {String(showCaptionIcon)}</div>
          <div><b>required:</b> {String(required)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { IfxRadioButton, IfxRadioButtonGroup } from '@infineon/infineon-design-system-react';

export function IfxRadioButtonGroupExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  const handleError = (event: CustomEvent) => {
    console.log('ifxError:', event);
    // Add your handler logic here
  };

  return (
      <IfxRadioButtonGroup
        alignment="vertical"
        groupLabelText="Group Label"
        captionText="Caption text, description, error notification"
        size="m"
        showGroupLabel={false}
        showCaption={false}
        showCaptionIcon={false}
        required={false}>
        <IfxRadioButton
          value={0}
          size="m"
          onIfxChange={handleChange}
          onIfxError={handleError}>
          Option 0
        </IfxRadioButton>
        <IfxRadioButton
          value={1}
          size="m">
          Option 1
        </IfxRadioButton>
        <IfxRadioButton
          value={2}
          size="m">
          Option 2
        </IfxRadioButton>
      </IfxRadioButtonGroup>
  );
}`;
