// examples/vue-example/src/generated/IfxSwitchExample.vue
<script setup lang="ts">

import { IfxSwitch } from '@infineon/infineon-design-system-vue';

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-switch
      name="switch"
      value="on"
      @ifxChange="handleChange">
      Switch
    </ifx-switch>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-switch
      name="switch"
      value="on"
      @ifxChange="handleChange">
      Switch
    </ifx-switch>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/react-example/src/generated/IfxSwitchExample.tsx
import { IfxSwitch } from '@infineon/infineon-design-system-react';

export function IfxSwitchExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  return (
    <>
      <IfxSwitch
        name="switch"
        value="on"
        onIfxChange={handleChange}>
        Switch
      </IfxSwitch>
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { IfxSwitch } from '@infineon/infineon-design-system-react';

export function IfxSwitchExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  return (
      <IfxSwitch
        name="switch"
        value="on"
        onIfxChange={handleChange}>
        Switch
      </IfxSwitch>
  );
}`;
