// examples/vue-example/src/generated/IfxSelectExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxSelect, IfxTextField } from '@infineon/infineon-design-system-vue';

const sizeOptions = ["s","m"];
const sizeIndex = ref(1);
const placeholder = ref(true);
const placeholderValue = ref("Placeholder");
const error = ref(false);
const label = ref("");
const disabled = ref(false);
const caption = ref("");
const required = ref(true);
const showSearch = ref(true);
const showClearButton = ref(true);
const searchPlaceholderValue = ref("Search...");
const options = ref("[{\"value\":\"a\",\"label\":\"option a\",\"selected\":false},{\"value\":\"b\",\"label\":\"option b\",\"selected\":false},{\"value\":\"c\",\"label\":\"option c\",\"selected\":false}]");

const handleSizeChange = () => { sizeIndex.value = (sizeIndex.value + 1) % sizeOptions.length; };
const handlePlaceholderChange = () => { placeholder.value = !placeholder.value; };
const handlePlaceholderValueChange = (nextValue: string) => { placeholderValue.value = nextValue; };
const handleErrorChange = () => { error.value = !error.value; };
const handleLabelChange = (nextValue: string) => { label.value = nextValue; };
const handleDisabledChange = () => { disabled.value = !disabled.value; };
const handleCaptionChange = (nextValue: string) => { caption.value = nextValue; };
const handleRequiredChange = () => { required.value = !required.value; };
const handleShowSearchChange = () => { showSearch.value = !showSearch.value; };
const handleShowClearButtonChange = () => { showClearButton.value = !showClearButton.value; };
const handleSearchPlaceholderValueChange = (nextValue: string) => { searchPlaceholderValue.value = nextValue; };
const handleOptionsChange = (nextValue: string) => { options.value = nextValue; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "size": sizeOptions[sizeIndex.value],
  "placeholder": placeholder.value,
  "placeholderValue": placeholderValue.value,
  "error": error.value,
  "label": label.value,
  "disabled": disabled.value,
  "caption": caption.value,
  "required": required.value,
  "showSearch": showSearch.value,
  "showClearButton": showClearButton.value,
  "searchPlaceholderValue": searchPlaceholderValue.value,
  "options": options.value,
}));

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleSelect = (event: CustomEvent) => {
  console.log('ifxSelect:', event);
  // Add your handler logic here
};

const getControlInputValue = (event: Event & {
  detail?: unknown;
  target?: { value?: unknown } | null;
}) => {
  const detail = event.detail;

  if (typeof detail === 'string' || typeof detail === 'number') {
    return String(detail);
  }

  if (detail && typeof detail === 'object' && 'value' in detail) {
    return String((detail as { value?: unknown }).value ?? '');
  }

  return String(event.target?.value ?? '');
};

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["size", sizeOptions[sizeIndex.value]],
  ["placeholder", placeholder.value],
  ["placeholder-value", placeholderValue.value],
  ["error", error.value],
  ["label", label.value],
  ["disabled", disabled.value],
  ["caption", caption.value],
  ["required", required.value],
  ["show-search", showSearch.value],
  ["show-clear-button", showClearButton.value],
  ["search-placeholder-value", searchPlaceholderValue.value],
  ["options", options.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxSelect } from '@infineon/infineon-design-system-vue';

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleSelect = (event: CustomEvent) => {
  console.log('ifxSelect:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-select
      @ifxInput="handleInput"
      @ifxSelect="handleSelect"
      :size="String(controlledProps.size ?? 'm')"
      :placeholder="String(controlledProps.placeholder ?? 'true')"
      :placeholder-value="String(controlledProps.placeholderValue ?? 'Placeholder')"
      :error="String(controlledProps.error ?? 'false')"
      :label="String(controlledProps.label ?? '')"
      :disabled="String(controlledProps.disabled ?? 'false')"
      :caption="String(controlledProps.caption ?? '')"
      :required="String(controlledProps.required ?? 'true')"
      :show-search="String(controlledProps.showSearch ?? 'true')"
      :show-clear-button="String(controlledProps.showClearButton ?? 'true')"
      :search-placeholder-value="String(controlledProps.searchPlaceholderValue ?? 'Search...')"
      :options="String(controlledProps.options ?? '[object Object],[object Object],[object Object]')"
      __CONTROLLED_PROPS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-select
      @ifxInput="handleInput"
      @ifxSelect="handleSelect"
      :size="String(controlledProps.size ?? 'm')"
      :placeholder="String(controlledProps.placeholder ?? 'true')"
      :placeholder-value="String(controlledProps.placeholderValue ?? 'Placeholder')"
      :error="String(controlledProps.error ?? 'false')"
      :label="String(controlledProps.label ?? '')"
      :disabled="String(controlledProps.disabled ?? 'false')"
      :caption="String(controlledProps.caption ?? '')"
      :required="String(controlledProps.required ?? 'true')"
      :show-search="String(controlledProps.showSearch ?? 'true')"
      :show-clear-button="String(controlledProps.showClearButton ?? 'true')"
      :search-placeholder-value="String(controlledProps.searchPlaceholderValue ?? 'Search...')"
      :options="String(controlledProps.options ?? '[object Object],[object Object],[object Object]')"
      v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="handleSizeChange">Toggle Size</ifx-button>
        <ifx-button variant="secondary" @click="handlePlaceholderChange">Toggle Placeholder</ifx-button>
        <ifx-button variant="secondary" @click="handleErrorChange">Toggle Error</ifx-button>
        <ifx-button variant="secondary" @click="handleDisabledChange">Toggle Disabled</ifx-button>
        <ifx-button variant="secondary" @click="handleRequiredChange">Toggle Required</ifx-button>
        <ifx-button variant="secondary" @click="handleShowSearchChange">Toggle ShowSearch</ifx-button>
        <ifx-button variant="secondary" @click="handleShowClearButtonChange">Toggle ShowClearButton</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="placeholderValue" type="text" :value="String(placeholderValue)" @ifxInput="handlePlaceholderValueChange(getControlInputValue($event))" />
        <ifx-text-field label="label" type="text" :value="String(label)" @ifxInput="handleLabelChange(getControlInputValue($event))" />
        <ifx-text-field label="caption" type="text" :value="String(caption)" @ifxInput="handleCaptionChange(getControlInputValue($event))" />
        <ifx-text-field label="searchPlaceholderValue" type="text" :value="String(searchPlaceholderValue)" @ifxInput="handleSearchPlaceholderValueChange(getControlInputValue($event))" />
        <ifx-text-field label="options" type="text" :value="String(options)" @ifxInput="handleOptionsChange(getControlInputValue($event))" />
    </div>

    <div class="state">
      <div><b>size:</b> {{ String(sizeOptions[sizeIndex]) }}</div>
      <div><b>placeholder:</b> {{ String(placeholder) }}</div>
      <div><b>placeholderValue:</b> {{ String(placeholderValue) }}</div>
      <div><b>error:</b> {{ String(error) }}</div>
      <div><b>label:</b> {{ String(label) }}</div>
      <div><b>disabled:</b> {{ String(disabled) }}</div>
      <div><b>caption:</b> {{ String(caption) }}</div>
      <div><b>required:</b> {{ String(required) }}</div>
      <div><b>showSearch:</b> {{ String(showSearch) }}</div>
      <div><b>showClearButton:</b> {{ String(showClearButton) }}</div>
      <div><b>searchPlaceholderValue:</b> {{ String(searchPlaceholderValue) }}</div>
      <div><b>options:</b> {{ String(options) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/react-example/src/generated/IfxSelectExample.tsx
import { useState } from 'react';
import { IfxButton, IfxSelect, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxSelectExample() {
  const sizeOptions = ["s","m"];
  const [sizeIndex, setSizeIndex] = useState(1);
  const [placeholder, setPlaceholder] = useState(true);
  const [placeholderValue, setPlaceholderValue] = useState("Placeholder");
  const [error, setError] = useState(false);
  const [label, setLabel] = useState("");
  const [disabled, setDisabled] = useState(false);
  const [caption, setCaption] = useState("");
  const [required, setRequired] = useState(true);
  const [showSearch, setShowSearch] = useState(true);
  const [showClearButton, setShowClearButton] = useState(true);
  const [searchPlaceholderValue, setSearchPlaceholderValue] = useState("Search...");
  const [options, setOptions] = useState("[{\"value\":\"a\",\"label\":\"option a\",\"selected\":false},{\"value\":\"b\",\"label\":\"option b\",\"selected\":false},{\"value\":\"c\",\"label\":\"option c\",\"selected\":false}]");

  const handleSizeChange = () => setSizeIndex((i) => (i + 1) % sizeOptions.length);
  const handlePlaceholderChange = () => setPlaceholder((v) => !v);
  const handlePlaceholderValueChange = (value: string) => setPlaceholderValue(value);
  const handleErrorChange = () => setError((v) => !v);
  const handleLabelChange = (value: string) => setLabel(value);
  const handleDisabledChange = () => setDisabled((v) => !v);
  const handleCaptionChange = (value: string) => setCaption(value);
  const handleRequiredChange = () => setRequired((v) => !v);
  const handleShowSearchChange = () => setShowSearch((v) => !v);
  const handleShowClearButtonChange = () => setShowClearButton((v) => !v);
  const handleSearchPlaceholderValueChange = (value: string) => setSearchPlaceholderValue(value);
  const handleOptionsChange = (value: string) => setOptions(value);

  const controlledProps = {
    "size": sizeOptions[sizeIndex],
    "placeholder": placeholder,
    "placeholderValue": placeholderValue,
    "error": error,
    "label": label,
    "disabled": disabled,
    "caption": caption,
    "required": required,
    "showSearch": showSearch,
    "showClearButton": showClearButton,
    "searchPlaceholderValue": searchPlaceholderValue,
    "options": options,
  } as Record<string, unknown>;
  const getControlInputValue = (event: {
    detail?: unknown;
    target?: { value?: unknown } | null;
  }): string => {
    const detail = event.detail;

    if (typeof detail === "string" || typeof detail === "number") {
      return String(detail);
    }

    if (detail && typeof detail === "object" && "value" in detail) {
      return String((detail as { value?: unknown }).value ?? "");
    }

    return String(event.target?.value ?? "");
  };

  const handleInput = (event: CustomEvent) => {
    console.log('ifxInput:', event);
    // Add your handler logic here
  };

  const handleSelect = (event: CustomEvent) => {
    console.log('ifxSelect:', event);
    // Add your handler logic here
  };

  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["size", controlledProps["size"]],
    ["placeholder", controlledProps["placeholder"]],
    ["placeholderValue", controlledProps["placeholderValue"]],
    ["error", controlledProps["error"]],
    ["label", controlledProps["label"]],
    ["disabled", controlledProps["disabled"]],
    ["caption", controlledProps["caption"]],
    ["required", controlledProps["required"]],
    ["showSearch", controlledProps["showSearch"]],
    ["showClearButton", controlledProps["showClearButton"]],
    ["searchPlaceholderValue", controlledProps["searchPlaceholderValue"]],
    ["options", controlledProps["options"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxSelect } from '@infineon/infineon-design-system-react';

export function IfxSelectExample() {
  const handleInput = (event: CustomEvent) => {
    console.log('ifxInput:', event);
    // Add your handler logic here
  };

  const handleSelect = (event: CustomEvent) => {
    console.log('ifxSelect:', event);
    // Add your handler logic here
  };

  return (
      <IfxSelect
        onIfxInput={handleInput}
        onIfxSelect={handleSelect}
        size={String(controlledProps.size ?? "m")}
        placeholder={String(controlledProps.placeholder ?? "true")}
        placeholderValue={String(controlledProps.placeholderValue ?? "Placeholder")}
        error={String(controlledProps.error ?? "false")}
        label={String(controlledProps.label ?? "")}
        disabled={String(controlledProps.disabled ?? "false")}
        caption={String(controlledProps.caption ?? "")}
        required={String(controlledProps.required ?? "true")}
        showSearch={String(controlledProps.showSearch ?? "true")}
        showClearButton={String(controlledProps.showClearButton ?? "true")}
        searchPlaceholderValue={String(controlledProps.searchPlaceholderValue ?? "Search...")}
        options={String(controlledProps.options ?? "[object Object],[object Object],[object Object]")}
        __CONTROLLED_PROPS__ />
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxSelect
        onIfxInput={handleInput}
        onIfxSelect={handleSelect}
        size={String(controlledProps.size ?? "m")}
        placeholder={String(controlledProps.placeholder ?? "true")}
        placeholderValue={String(controlledProps.placeholderValue ?? "Placeholder")}
        error={String(controlledProps.error ?? "false")}
        label={String(controlledProps.label ?? "")}
        disabled={String(controlledProps.disabled ?? "false")}
        caption={String(controlledProps.caption ?? "")}
        required={String(controlledProps.required ?? "true")}
        showSearch={String(controlledProps.showSearch ?? "true")}
        showClearButton={String(controlledProps.showClearButton ?? "true")}
        searchPlaceholderValue={String(controlledProps.searchPlaceholderValue ?? "Search...")}
        options={String(controlledProps.options ?? "[object Object],[object Object],[object Object]")}
        {...(controlledProps as any)} />
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={handleSizeChange}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={handlePlaceholderChange}>Toggle Placeholder</IfxButton>
        <IfxButton variant="secondary" onClick={handleErrorChange}>Toggle Error</IfxButton>
        <IfxButton variant="secondary" onClick={handleDisabledChange}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={handleRequiredChange}>Toggle Required</IfxButton>
        <IfxButton variant="secondary" onClick={handleShowSearchChange}>Toggle ShowSearch</IfxButton>
        <IfxButton variant="secondary" onClick={handleShowClearButtonChange}>Toggle ShowClearButton</IfxButton>
	      </div>
	      <div className="controls controls-input">
        <IfxTextField label="placeholderValue" type="text" value={String(placeholderValue)} onIfxInput={(event) => handlePlaceholderValueChange(getControlInputValue(event))} />
        <IfxTextField label="label" type="text" value={String(label)} onIfxInput={(event) => handleLabelChange(getControlInputValue(event))} />
        <IfxTextField label="caption" type="text" value={String(caption)} onIfxInput={(event) => handleCaptionChange(getControlInputValue(event))} />
        <IfxTextField label="searchPlaceholderValue" type="text" value={String(searchPlaceholderValue)} onIfxInput={(event) => handleSearchPlaceholderValueChange(getControlInputValue(event))} />
        <IfxTextField label="options" type="text" value={String(options)} onIfxInput={(event) => handleOptionsChange(getControlInputValue(event))} />
	      </div>

	      <div className="state">
	          <div><b>size:</b> {String(sizeOptions[sizeIndex])}</div>
          <div><b>placeholder:</b> {String(placeholder)}</div>
          <div><b>placeholderValue:</b> {String(placeholderValue)}</div>
          <div><b>error:</b> {String(error)}</div>
          <div><b>label:</b> {String(label)}</div>
          <div><b>disabled:</b> {String(disabled)}</div>
          <div><b>caption:</b> {String(caption)}</div>
          <div><b>required:</b> {String(required)}</div>
          <div><b>showSearch:</b> {String(showSearch)}</div>
          <div><b>showClearButton:</b> {String(showClearButton)}</div>
          <div><b>searchPlaceholderValue:</b> {String(searchPlaceholderValue)}</div>
          <div><b>options:</b> {String(options)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}
