// examples/wrapper-components/vue-javascript/src/components/Switch.vue
<script setup lang="ts">
import { ref } from "vue";

const disabled = ref(false);

function toggleDisable() {
  disabled.value = !disabled.value;
}

</script>

<template>
  <div class="component">
    <h2>Switch</h2>
    <ifx-switch checked="false" name="switch" value="switch" :disabled="disabled">Switch</ifx-switch>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleDisable">Toggle Disabled</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Disabled:</b> {{ disabled }} </div>
    </div>
  </div>
</template>

// examples/wrapper-components/react-vite-js/src/components/Switch/Switch.jsx
import { useState } from 'react';
import { IfxSwitch, IfxButton } from '@infineon/infineon-design-system-react';

function Switch() {
  const [disabled, setDisabled] = useState(false);

  const toggleDisabled = () => {
    setDisabled((prev) => !prev);
  };

  return (
    <div className="component">
      <h2>Switch</h2>
      <IfxSwitch checked="false" name="switch" value="switch" disabled={disabled}> Switch </IfxSwitch>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Disabled:</b> {String(disabled)}</div>
      </div>
    </div>
  );
}

export default Switch;
