// examples/wrapper-components/react-javascript/src/App.js
import './App.css';

import Button from './components/Button/button';

import TextField from './components/TextFIeld/TextField';

import ProgressBar from './components/ProgressBar/ProgressBar';

import SearchBar from './components/SearchBar/SearchBar';
import Accordion from './components/Accordion/Accordion';


function App() {




  return (
    <div>
      <h1 className="header">Stencil Framework integration - React + JS</h1>

      <h2>Search Bar</h2>
      <SearchBar />
      <br />

      <h2>Button</h2>
      <Button />
      <br />

      <h2>Progress Bar</h2>
      <ProgressBar />
      <br />

      <h2>Text Field</h2>
      <TextField />
      <br />

      <h2>Accordion</h2>
      <Accordion />

    </div>

  )
}
export default App;

// examples/stencil-components/vue3-vite/src/App.vue
<script setup>
import Button from './components/Button.vue'
import Checkbox from './components/Checkbox.vue'
import ProgressBar from './components/ProgressBar.vue'

</script>

<template>
  <h1 class="header">Using Stencil web components in a Vue application</h1>
  <Button />
  <Checkbox />
  <ProgressBar />
</template>

<style scoped>
.header {
  text-align: center;
}
</style>
