// examples/wrapper-components/vue-javascript/src/components/CheckboxGroup.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["m", "s"];
const sizeIndex = ref(0);
const size = computed(() => sizes[sizeIndex.value]);

const alignments = ["vertical", "horizontal"];
const alignmentIndex = ref(0);
const alignment = computed(() => alignments[alignmentIndex.value]);

const disabled = ref(false);
const error = ref(false);
const label = ref(true);
const caption = ref(true);
const captionIcon = ref(true);
const required = ref(false);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleAlignment() {
  alignmentIndex.value = (alignmentIndex.value + 1) % alignments.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleError() {
  error.value = !error.value;
}

function toggleLabel() {
  label.value = !label.value;
}

function toggleCaption() {
  caption.value = !caption.value;
}

function toggleCaptionIcon() {
  captionIcon.value = !captionIcon.value;
}

function toggleRequired() {
  required.value = !required.value;
}


</script>

<template>
  <div class="component">
    <h2>Checkbox</h2>
    <ifx-checkbox-group :alignment="alignment" :showGroupLabel="label" group-label-text="Group Label"
      :showCaption="caption" caption-text="Caption text, description, error notification" :showCaptionIcon="captionIcon"
      :required="required">
      <ifx-checkbox value="0" :disabled="disabled" checked="false" :size="size" indeterminate="false"
        :error="error">Option 0</ifx-checkbox>
      <ifx-checkbox value="1" :disabled="disabled" checked="false" :size="size" indeterminate="false"
        :error="error">Option 1</ifx-checkbox>
      <ifx-checkbox value="2" :disabled="disabled" checked="false" :size="size" indeterminate="false"
        :error="error">Option 2</ifx-checkbox>
      <ifx-checkbox value="3" :disabled="disabled" checked="false" :size="size" indeterminate="false"
        :error="error">Option 3</ifx-checkbox>
    </ifx-checkbox-group>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleAlignment">Toggle Alignment</ifx-button>
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleError">Toggle Error</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleLabel">Toggle Label</ifx-button>
      <ifx-button variant="secondary" @click="toggleCaption">Toggle Caption</ifx-button>
      <ifx-button variant="secondary" @click="toggleCaptionIcon">Toggle Caption Icon</ifx-button>
      <ifx-button variant="secondary" @click="toggleRequired">Toggle Required</ifx-button>

    </div>
    <br>

    <div class="state">
      <div><b>Alignment:</b> {{ alignment }} </div>
      <div><b>Disabled:</b> {{ disabled }} </div>
      <div><b>Error:</b> {{ error }} </div>
      <div><b>Size:</b> {{ size }} </div>
      <div><b>Label:</b> {{ label }} </div>
      <div><b>Caption:</b> {{ caption }} </div>
      <div><b>Caption Icon:</b> {{ captionIcon }} </div>
      <div><b>Required:</b> {{ required }} </div>
    </div>
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/checkbox-group/checkbox-group.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-checkbox-group',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './checkbox-group.component.html',
  styleUrl: './checkbox-group.component.scss'
})
export class CheckboxGroupComponent {
  error = false;
  disabled = false;
  label = true;
  caption = true;
  captionIcon = true;
  required = false;

  alignment = "vertical";
  alignments = ["vertical", "horizontal"];
  alignmentIndex = 0;

  size = "m";
  sizes = ["m", "s"];
  sizeIndex = 0;

  toggleAlignment() {
    this.alignmentIndex = (this.alignmentIndex + 1) % this.alignments.length;
    this.alignment = this.alignments[this.alignmentIndex];
  }

  toggleDisabled() {
    this.disabled = !this.disabled;
  }

  toggleError() {
    this.error = !this.error;
  }

  toggleLabel() {
    this.label = !this.label;
  }

  toggleCaption() {
    this.caption = !this.caption;
  }

  toggleCaptionIcon() {
    this.captionIcon = !this.captionIcon;
  }

  toggleRequired() {
    this.required = !this.required;
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }
}

<h2>Checkbox Group</h2>
<ifx-checkbox-group 
  [alignment]="checkboxGroupAlignment"
  [showGroupLabel]="checkboxGroupLabel" 
  group-label-text="Group Label" 
  [showCaption]="checkboxGroupCaption" 
  caption-text="Caption text, description, error notification" 
  [showCaptionIcon]="checkboxGroupCaptionIcon"
  [required]="checkboxGroupRequired">
    <ifx-checkbox value="0" [disabled]="checkboxGroupDisabled" checked="false" [size]="checkboxGroupSize" indeterminate="false" [error]="checkboxGroupError">Option 0</ifx-checkbox>
    <ifx-checkbox value="1" [disabled]="checkboxGroupDisabled" checked="false" [size]="checkboxGroupSize" indeterminate="false" [error]="checkboxGroupError">Option 1</ifx-checkbox>
    <ifx-checkbox value="2" [disabled]="checkboxGroupDisabled" checked="false" [size]="checkboxGroupSize" indeterminate="false" [error]="checkboxGroupError">Option 2</ifx-checkbox>
    <ifx-checkbox value="3" [disabled]="checkboxGroupDisabled" checked="false" [size]="checkboxGroupSize" indeterminate="false" [error]="checkboxGroupError">Option 3</ifx-checkbox>
</ifx-checkbox-group>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupAlignment()">Toggle Alignment</ifx-button>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupDisabled()">Toggle Disabled</ifx-button>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupError()">Toggle Error</ifx-button>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupSize()">Toggle Size</ifx-button>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupLabel()">Toggle Label</ifx-button>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupCaption()">Toggle Caption</ifx-button>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupCaptionIcon()">Toggle Caption Icon</ifx-button>
<ifx-button variant="secondary" (click)="toggleCheckboxGroupRequired()">Toggle Required</ifx-button>
<br>
<br>
<span><b>Alignment:</b> {{ checkboxGroupAlignment }} </span><br>
<span><b>Disabled:</b> {{ checkboxGroupDisabled }} </span><br>
<span><b>Error:</b> {{ checkboxGroupError }} </span><br>
<span><b>Size:</b> {{ checkboxGroupSize }} </span><br>
<span><b>Label:</b> {{ checkboxGroupLabel }} </span><br>
<span><b>Caption:</b> {{ checkboxGroupCaption }} </span><br>
<span><b>Caption Icon:</b> {{ checkboxGroupCaptionIcon }} </span><br>
<span><b>Required:</b> {{ checkboxGroupRequired }} </span><br>
