// examples/wrapper-components/vue-typescript/src/components/TextInput.vue
<template>
  <div>
    <h2>Text Input</h2>
    <h3>Using v-model</h3>
    <div>
      <ifx-text-input v-model="input" error="true" disabled="false" success="false" placeholder="Placeholder"
        errorMessage="some error message">Label</ifx-text-input>

    </div>
    <p>Text field value: {{ inputValue }}</p>
    <br />
    <br />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

let inputValue = ref("");
// Computed property to retrieve the query value
const input = computed({
  get: () => inputValue.value,
  set: (newValue) => handleInput(newValue)
});

function handleInput(event: string) {
  console.log("updating  input: ", event)
  inputValue.value = event; //v-model automatically accesses event.detail
};
</script>

// src/components/text-input/text-input.tsx
import { Component, h, Element, Prop } from '@stencil/core';

@Component({
  tag: 'ifx-text-input',
  styleUrl: '../../index.scss', 
  shadow: true
})

export class TextInput {
  @Element() el;
  @Prop() placeholder: string = "Placeholder"
  @Prop() error: boolean = false;
  @Prop() errorMessage: string = ""
  @Prop() success: boolean = false;
  @Prop() disabled: boolean = false;

  render() {
    console.log('error message', this.errorMessage)
    return (
      <div class={`textInput__container ${this.disabled ? 'disabled' : ""}`}>
        <div class="textInput__top-wrapper">
          <label htmlFor="text-field">
            <slot />
          </label>
        </div>
        <div class="textInput__bottom-wrapper">
          <input 
          disabled={this.disabled}
          type="text" 
          id='text-field' 
          placeholder={this.placeholder} 
          class={`${this.error ? 'error' : ""} ${this.success ? "success" : ""}`}/>
          {this.error && 
            <div class="textInput__bottom-wrapper-error">
            {this.errorMessage}
          </div>}
        </div>
      </div>
    );
  }
}
