// examples/angular-standalone-example/src/app/generated/ifx-ai-label-example/ifx-ai-label-example.ts
import { IfxAiLabel, IfxButton } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-ai-label-example',
  imports: [ IfxAiLabel, IfxButton ],
  templateUrl: './ifx-ai-label-example.html',
	styleUrl: './ifx-ai-label-example.scss'
})
export class IfxAiLabelExample {
  protected readonly tsCode = `import { IfxAiLabel, IfxButton } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-ai-label-example&#039;,
  imports: [ IfxAiLabel, IfxButton ],
  templateUrl: &#039;./ifx-ai-label-example.html&#039;,
	styleUrl: &#039;./ifx-ai-label-example.scss&#039;
})
export class IfxAiLabelExample {}`;
  protected get htmlCode(): string {
    const controlledAttrs = [
      ["divider", this.controlledProps["divider"]],
      ["variant", this.controlledProps["variant"]],
    ]
			.map(([name, value]) => '    ' + String(name) + '=&quot;' + String(value) + '&quot;')
      .join("\n");

    return `  &lt;ifx-ai-label __CONTROLLED_ATTRS__&gt;&lt;/ifx-ai-label&gt;`.replace("__CONTROLLED_ATTRS__", controlledAttrs);
  }
  protected divider = true;
  protected readonly variantOptions = ["label","icon"];
  protected variantIndex = 0;

  protected toggleDivider() { this.divider = !this.divider; }
  protected toggleVariant() { this.variantIndex = (this.variantIndex + 1) % this.variantOptions.length; }

  protected get controlledProps(): Record<string, unknown> {
    return {
      "divider": this.divider,
      "variant": this.variantOptions[this.variantIndex],
    };
  }
}

// examples/vue-example/src/generated/IfxAiLabelExample.vue
<script setup lang="ts">

import { IfxAiLabel, IfxButton } from '@infineon/infineon-design-system-vue';

import { computed, ref } from 'vue';

const divider = ref(true);
const variantOptions = ["label","icon"];
const variantIndex = ref(0);

const toggleDivider = () => (divider.value = !divider.value);
const toggleVariant = () => (variantIndex.value = (variantIndex.value + 1) % variantOptions.length);

const controlledProps = computed(() => ({
  "divider": divider.value,
  "variant": variantOptions[variantIndex.value],
}));

const formatAttrValueForCode = (value: unknown): string => {
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  if (value === null) return "null";
  if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
    return JSON.stringify(value);
  }
  return String(value).replace(/"/g, '&quot;');
};

const controlledAttrsCode = [
  ["divider", controlledProps.value["divider"]],
  ["variant", controlledProps.value["variant"]],
]
	.map(([name, value]) => '      ' + String(name) + '="' + formatAttrValueForCode(value) + '"')
  .join("\n");

const codeString = `<script setup lang="ts">
${'</'}script>

<template>
  <div>
    <ifx-ai-label __CONTROLLED_ATTRS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_ATTRS__", controlledAttrsCode);

</script>

<template>
  <div>
    <ifx-ai-label v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <IfxButton variant="secondary" @click="toggleDivider">Toggle Divider</IfxButton>
      <IfxButton variant="secondary" @click="toggleVariant">Toggle Variant</IfxButton>
    </div>

    <div class="state">
        <div><b>divider:</b> {{ String(divider.value) }}</div>
        <div><b>variant:</b> {{ String(variantOptions[variantIndex.value]) }}</div>
    </div>

    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
