// examples/react-example/src/generated/IfxActionListExample.tsx
import { useState } from 'react';
import { IfxActionList, IfxActionListItem, IfxIcon, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxActionListExample() {
  const [listAriaLabel, setListAriaLabel] = useState("Navigation menu");

  const handleListAriaLabelChange = (value: string) => setListAriaLabel(value);

  const controlledProps = {
    "listAriaLabel": listAriaLabel,
  } as Record<string, unknown>;
  const handleActionListItemClick = (event: CustomEvent) => {
    console.log('ifxActionListItemClick:', event);
    // Add your handler logic here
  };

  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["listAriaLabel", controlledProps["listAriaLabel"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxActionList, IfxActionListItem, IfxIcon } from '@infineon/infineon-design-system-react';

export function IfxActionListExample() {
  const handleActionListItemClick = (event: CustomEvent) => {
    console.log('ifxActionListItemClick:', event);
    // Add your handler logic here
  };

  return (
      <IfxActionList __CONTROLLED_PROPS__>
        <IfxActionListItem
          itemTitle="Dashboard"
          description="View your main dashboard"
          value="dashboard"
          itemAriaLabel="Navigation item"
          onIfxActionListItemClick={handleActionListItemClick}>
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
        <IfxActionListItem
          itemTitle="Settings"
          value="settings"
          itemAriaLabel="Navigation item">
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
        <IfxActionListItem
          itemTitle="Profile"
          description="Manage your profile information"
          value="profile"
          disabled={true}
          itemAriaLabel="Navigation item">
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
        <IfxActionListItem
          itemTitle="Advanced Analytics and Reporting Dashboard with Extended Functionality"
          description="This comprehensive analytics dashboard provides detailed insights into user behavior and system performance metrics."
          value="analytics"
          itemAriaLabel="Navigation item">
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
      </IfxActionList>
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxActionList {...(controlledProps as any)}>
        <IfxActionListItem
          itemTitle="Dashboard"
          description="View your main dashboard"
          value="dashboard"
          itemAriaLabel="Navigation item"
          onIfxActionListItemClick={handleActionListItemClick}>
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
        <IfxActionListItem
          itemTitle="Settings"
          value="settings"
          itemAriaLabel="Navigation item">
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
        <IfxActionListItem
          itemTitle="Profile"
          description="Manage your profile information"
          value="profile"
          disabled={true}
          itemAriaLabel="Navigation item">
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
        <IfxActionListItem
          itemTitle="Advanced Analytics and Reporting Dashboard with Extended Functionality"
          description="This comprehensive analytics dashboard provides detailed insights into user behavior and system performance metrics."
          value="analytics"
          itemAriaLabel="Navigation item">
          <IfxIcon
            slot="trailing"
            icon="chevron-right-16" />
        </IfxActionListItem>
      </IfxActionList>
	      <h3 className="controls-title">Controls</h3>
	      
	      <div className="controls controls-input">
        <IfxTextField label="listAriaLabel" type="text" value={String(listAriaLabel)} onInput={(event) => handleListAriaLabelChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
	      </div>

	      <div className="state">
	          <div><b>listAriaLabel:</b> {String(listAriaLabel)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

// examples/vue-example/src/generated/IfxActionListExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxActionList, IfxActionListItem, IfxIcon, IfxTextField } from '@infineon/infineon-design-system-vue';

const listAriaLabel = ref("Navigation menu");

const handleListAriaLabelChange = (nextValue: string) => { listAriaLabel.value = nextValue; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "listAriaLabel": listAriaLabel.value,
}));

const handleActionListItemClick = (event: CustomEvent) => {
  console.log('ifxActionListItemClick:', event);
  // Add your handler logic here
};

const getInputValue = (event: Event) => String((event.target as HTMLInputElement | null)?.value ?? "");

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["listAriaLabel", listAriaLabel.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxActionList, IfxActionListItem, IfxIcon } from '@infineon/infineon-design-system-vue';

const handleActionListItemClick = (event: CustomEvent) => {
  console.log('ifxActionListItemClick:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-action-list __CONTROLLED_PROPS__>
      <ifx-action-list-item
        item-title="Dashboard"
        description="View your main dashboard"
        value="dashboard"
        item-aria-label="Navigation item"
        @ifxActionListItemClick="handleActionListItemClick">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
      <ifx-action-list-item
        item-title="Settings"
        value="settings"
        item-aria-label="Navigation item">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
      <ifx-action-list-item
        item-title="Profile"
        description="Manage your profile information"
        value="profile"
        :disabled="true"
        item-aria-label="Navigation item">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
      <ifx-action-list-item
        item-title="Advanced Analytics and Reporting Dashboard with Extended Functionality"
        description="This comprehensive analytics dashboard provides detailed insights into user behavior and system performance metrics."
        value="analytics"
        item-aria-label="Navigation item">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
    </ifx-action-list>
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-action-list v-bind="controlledProps">
      <ifx-action-list-item
        item-title="Dashboard"
        description="View your main dashboard"
        value="dashboard"
        item-aria-label="Navigation item"
        @ifxActionListItemClick="handleActionListItemClick">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
      <ifx-action-list-item
        item-title="Settings"
        value="settings"
        item-aria-label="Navigation item">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
      <ifx-action-list-item
        item-title="Profile"
        description="Manage your profile information"
        value="profile"
        :disabled="true"
        item-aria-label="Navigation item">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
      <ifx-action-list-item
        item-title="Advanced Analytics and Reporting Dashboard with Extended Functionality"
        description="This comprehensive analytics dashboard provides detailed insights into user behavior and system performance metrics."
        value="analytics"
        item-aria-label="Navigation item">
        <ifx-icon
          slot="trailing"
          icon="chevron-right-16" />
      </ifx-action-list-item>
    </ifx-action-list>
    <h3 class="controls-title">Controls</h3>
    
    <div class="controls controls-input">
        <ifx-text-field label="listAriaLabel" type="text" :value="String(listAriaLabel)" @input="handleListAriaLabelChange(getInputValue($event))" />
    </div>

    <div class="state">
      <div><b>listAriaLabel:</b> {{ String(listAriaLabel) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
