// examples/angular-standalone-example/src/app/generated/ifx-card-example/ifx-card-example.ts
import { IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-card-example',
  imports: [ IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText ],
  templateUrl: './ifx-card-example.html',
	styleUrl: './ifx-card-example.scss'
})
export class IfxCardExample {
  protected readonly tsCode = `import { IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-card-example&#039;,
  imports: [ IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText ],
  templateUrl: &#039;./ifx-card-example.html&#039;,
	styleUrl: &#039;./ifx-card-example.scss&#039;
})
export class IfxCardExample {
  protected handleImgPosition(event: CustomEvent) {
    console.log(&#039;imgPosition:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-card
    direction=&quot;vertical&quot;
    href=&quot;&quot;
    target=&quot;_blank&quot;
    aria-label=&quot;&quot;
    aria-label-text=&quot;Card&quot;
    [fullWidth]=&quot;false&quot;&gt;
    &lt;ifx-card-image
      position=&quot;right&quot;
      src=&quot;https://raw.githubusercontent.com/Infineon/public-assets/main/ifx-logo.png&quot;
      alt=&quot;Default&quot;
      slot=&quot;img&quot;
      (imgPosition)=&quot;handleImgPosition(\$any(\$event))&quot;&gt;&lt;/ifx-card-image&gt;
    &lt;ifx-card-overline (imgPosition)=&quot;handleImgPosition(\$any(\$event))&quot;&gt;Overline&lt;/ifx-card-overline&gt;
    &lt;ifx-card-headline (imgPosition)=&quot;handleImgPosition(\$any(\$event))&quot;&gt;Headline&lt;/ifx-card-headline&gt;
    &lt;ifx-card-text (imgPosition)=&quot;handleImgPosition(\$any(\$event))&quot;&gt;Some quick example text to build on the card title and make up the bulk of the card&#039;s content.&lt;/ifx-card-text&gt;
    &lt;ifx-card-links
      slot=&quot;buttons&quot;
      (imgPosition)=&quot;handleImgPosition(\$any(\$event))&quot;&gt;
      &lt;ifx-button variant=&quot;primary&quot;&gt;Button&lt;/ifx-button&gt;
      &lt;ifx-button variant=&quot;secondary&quot;&gt;Button&lt;/ifx-button&gt;
    &lt;/ifx-card-links&gt;
  &lt;/ifx-card&gt;`;

  protected handleImgPosition(event: CustomEvent) {
    console.log('imgPosition:', event);
    // Add your handler logic here
  }
}

// examples/vue-example/src/generated/IfxCardExample.vue
<script setup lang="ts">

import { IfxButton, IfxCard, IfxCardHeadline, IfxCardImage, IfxCardLinks, IfxCardOverline, IfxCardText } from '@infineon/infineon-design-system-vue';

const handleImgPosition = (event: CustomEvent) => {
  console.log('imgPosition:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleImgPosition = (event: CustomEvent) => {
  console.log('imgPosition:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-card
      direction="vertical"
      href=""
      target="_blank"
      aria-label=""
      aria-label-text="Card"
      :full-width="false">
      <ifx-card-image
        position="right"
        src="https://raw.githubusercontent.com/Infineon/public-assets/main/ifx-placeholder.png"
        alt="Default"
        slot="img"
        @imgPosition="handleImgPosition" />
      <ifx-card-overline @imgPosition="handleImgPosition">
        Overline
      </ifx-card-overline>
      <ifx-card-headline @imgPosition="handleImgPosition">
        Headline
      </ifx-card-headline>
      <ifx-card-text @imgPosition="handleImgPosition">
        Some quick example text to build on the card title and make up the bulk of the card's content.
      </ifx-card-text>
      <ifx-card-links
        slot="buttons"
        @imgPosition="handleImgPosition">
        <ifx-button variant="primary">
          Button
        </ifx-button>
        <ifx-button variant="secondary">
          Button
        </ifx-button>
      </ifx-card-links>
    </ifx-card>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-card
      direction="vertical"
      href=""
      target="_blank"
      aria-label=""
      aria-label-text="Card"
      :full-width="false">
      <ifx-card-image
        position="right"
        src="https://raw.githubusercontent.com/Infineon/public-assets/main/ifx-placeholder.png"
        alt="Default"
        slot="img"
        @imgPosition="handleImgPosition" />
      <ifx-card-overline @imgPosition="handleImgPosition">
        Overline
      </ifx-card-overline>
      <ifx-card-headline @imgPosition="handleImgPosition">
        Headline
      </ifx-card-headline>
      <ifx-card-text @imgPosition="handleImgPosition">
        Some quick example text to build on the card title and make up the bulk of the card's content.
      </ifx-card-text>
      <ifx-card-links
        slot="buttons"
        @imgPosition="handleImgPosition">
        <ifx-button variant="primary">
          Button
        </ifx-button>
        <ifx-button variant="secondary">
          Button
        </ifx-button>
      </ifx-card-links>
    </ifx-card>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
