// examples/react-example/src/generated/IfxCheckboxGroupExample.tsx
import { IfxCheckbox, IfxCheckboxGroup } from '@infineon/infineon-design-system-react';

export function IfxCheckboxGroupExample() {
  const handleSetGroupError = (event: CustomEvent) => {
    console.log('setGroupError:', event);
    // Add your handler logic here
  };

  return (
    <>
      <IfxCheckboxGroup
        alignment="vertical"
        groupLabelText="Group Label"
        captionText="Caption text, description, error notification">
        <IfxCheckbox
          value={0}
          size="m">
          Option 0
        </IfxCheckbox>
        <IfxCheckbox
          value={1}
          size="m">
          Option 1
        </IfxCheckbox>
        <IfxCheckbox
          value={2}
          size="m">
          Option 2
        </IfxCheckbox>
      </IfxCheckboxGroup>
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { IfxCheckbox, IfxCheckboxGroup } from '@infineon/infineon-design-system-react';

export function IfxCheckboxGroupExample() {
  const handleSetGroupError = (event: CustomEvent) => {
    console.log('setGroupError:', event);
    // Add your handler logic here
  };

  return (
      <IfxCheckboxGroup
        alignment="vertical"
        groupLabelText="Group Label"
        captionText="Caption text, description, error notification">
        <IfxCheckbox
          value={0}
          size="m">
          Option 0
        </IfxCheckbox>
        <IfxCheckbox
          value={1}
          size="m">
          Option 1
        </IfxCheckbox>
        <IfxCheckbox
          value={2}
          size="m">
          Option 2
        </IfxCheckbox>
      </IfxCheckboxGroup>
  );
}`;

// examples/vue-example/src/generated/IfxCheckboxGroupExample.vue
<script setup lang="ts">

import { IfxCheckbox, IfxCheckboxGroup } from '@infineon/infineon-design-system-vue';

const handleSetGroupError = (event: CustomEvent) => {
  console.log('setGroupError:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleSetGroupError = (event: CustomEvent) => {
  console.log('setGroupError:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-checkbox-group
      alignment="vertical"
      group-label-text="Group Label"
      caption-text="Caption text, description, error notification">
      <ifx-checkbox
        :value=0
        size="m">
        Option 0
      </ifx-checkbox>
      <ifx-checkbox
        :value=1
        size="m">
        Option 1
      </ifx-checkbox>
      <ifx-checkbox
        :value=2
        size="m">
        Option 2
      </ifx-checkbox>
    </ifx-checkbox-group>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-checkbox-group
      alignment="vertical"
      group-label-text="Group Label"
      caption-text="Caption text, description, error notification">
      <ifx-checkbox
        :value=0
        size="m">
        Option 0
      </ifx-checkbox>
      <ifx-checkbox
        :value=1
        size="m">
        Option 1
      </ifx-checkbox>
      <ifx-checkbox
        :value=2
        size="m">
        Option 2
      </ifx-checkbox>
    </ifx-checkbox-group>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
