// examples/angular-standalone-example/src/app/generated/ifx-checkbox-example/ifx-checkbox-example.ts
import { IfxCheckbox } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-checkbox-example',
  imports: [ IfxCheckbox ],
  templateUrl: './ifx-checkbox-example.html',
	styleUrl: './ifx-checkbox-example.scss'
})
export class IfxCheckboxExample {
  protected readonly tsCode = `import { IfxCheckbox } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-checkbox-example&#039;,
  imports: [ IfxCheckbox ],
  templateUrl: &#039;./ifx-checkbox-example.html&#039;,
	styleUrl: &#039;./ifx-checkbox-example.scss&#039;
})
export class IfxCheckboxExample {
  protected handleChange(event: CustomEvent) {
    console.log(&#039;ifxChange:&#039;, event);
    // Add your handler logic here
  }

  protected handleError(event: CustomEvent) {
    console.log(&#039;ifxError:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-checkbox
    [error]=&quot;false&quot;
    [disabled]=&quot;false&quot;
    [checked]=&quot;false&quot;
    size=&quot;s&quot;
    [indeterminate]=&quot;false&quot;
    name=&quot;checkbox&quot;
    (ifxChange)=&quot;handleChange(\$any(\$event))&quot;
    (ifxError)=&quot;handleError(\$any(\$event))&quot;&gt;Text&lt;/ifx-checkbox&gt;`;

  protected handleChange(event: CustomEvent) {
    console.log('ifxChange:', event);
    // Add your handler logic here
  }

  protected handleError(event: CustomEvent) {
    console.log('ifxError:', event);
    // Add your handler logic here
  }
}

// examples/vue-example/src/generated/IfxCheckboxExample.vue
<script setup lang="ts">

import { IfxCheckbox } from '@infineon/infineon-design-system-vue';

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const handleError = (event: CustomEvent) => {
  console.log('ifxError:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const handleError = (event: CustomEvent) => {
  console.log('ifxError:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-checkbox
      :error="false"
      :disabled="false"
      :checked="false"
      size="s"
      :indeterminate="false"
      name="checkbox"
      @ifxChange="handleChange"
      @ifxError="handleError">
      Text
    </ifx-checkbox>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-checkbox
      :error="false"
      :disabled="false"
      :checked="false"
      size="s"
      :indeterminate="false"
      name="checkbox"
      @ifxChange="handleChange"
      @ifxError="handleError">
      Text
    </ifx-checkbox>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
