// examples/react-example/src/generated/IfxFooterExample.tsx
import {
	IfxFooter,
	IfxIcon,
	IfxLink,
} from "@infineon/infineon-design-system-react";

export function IfxFooterExample() {
	return (
		<>
			<IfxFooter copyrightText="© 1999 - 2024 Infineon Technologies AG">
				<div slot="socials">
					<IfxLink
						variant="title"
						href="http://infineon.com"
						ariaLabel="Go to Homepage"
					>
						<IfxIcon icon="home-16" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://facebook.com/infineon"
						ariaLabel="Follow us on Facebook"
					>
						<IfxIcon icon="facebook" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://youtube.com/infineon"
						ariaLabel="Follow us on Youtube"
					>
						<IfxIcon icon="youtube" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://instagram.com/infineon"
						ariaLabel="Follow us on Instagram"
					>
						<IfxIcon icon="instagram" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://linkedin.com/infineon"
						ariaLabel="Follow us on LinkedIn"
					>
						<IfxIcon icon="linkedin" />
					</IfxLink>
					<IfxLink
						variant="title"
						href="http://xing.com/infineon"
						ariaLabel="Follow us on Xing"
					>
						<IfxIcon icon="xing" />
					</IfxLink>
				</div>
				<div slot="info">
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/terms"
						target="_blank"
					>
						Terms
					</IfxLink>
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/imprint"
						target="_blank"
					>
						Imprint
					</IfxLink>
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/privacy-policy"
						target="_blank"
					>
						Privacy policy
					</IfxLink>
					<IfxLink
						variant="menu"
						href="https://yourwebsite.com/glossary"
						target="_blank"
					>
						Glossary
					</IfxLink>
				</div>
			</IfxFooter>
			<details className="code-details">
				<summary>View Code</summary>
				<pre>
					<code className="language-tsx">{codeString}</code>
				</pre>
			</details>
		</>
	);
}

const codeString = `import { IfxFooter, IfxIcon, IfxLink } from '@infineon/infineon-design-system-react';

export function IfxFooterExample() {
  return (
      <IfxFooter copyrightText="© 1999 - 2024 Infineon Technologies AG">
        <div slot="socials">
          <IfxLink
            variant="title"
            href="http://infineon.com"
            ariaLabel="Go to Homepage">
            <IfxIcon icon="home-16" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://facebook.com/infineon"
            ariaLabel="Follow us on Facebook">
            <IfxIcon icon="facebook" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://youtube.com/infineon"
            ariaLabel="Follow us on Youtube">
            <IfxIcon icon="youtube" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://instagram.com/infineon"
            ariaLabel="Follow us on Instagram">
            <IfxIcon icon="instagram" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://linkedin.com/infineon"
            ariaLabel="Follow us on LinkedIn">
            <IfxIcon icon="linkedin" />
          </IfxLink>
          <IfxLink
            variant="title"
            href="http://xing.com/infineon"
            ariaLabel="Follow us on Xing">
            <IfxIcon icon="xing" />
          </IfxLink>
        </div>
        <div slot="info">
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/terms"
            target="_blank">
            Terms
          </IfxLink>
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/imprint"
            target="_blank">
            Imprint
          </IfxLink>
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/privacy-policy"
            target="_blank">
            Privacy policy
          </IfxLink>
          <IfxLink
            variant="menu"
            href="https://yourwebsite.com/glossary"
            target="_blank">
            Glossary
          </IfxLink>
        </div>
      </IfxFooter>
  );
}`;

// examples/vue-example/src/generated/IfxFooterExample.vue
<script setup lang="ts">
import { onMounted, nextTick } from 'vue';
import Prism from 'prismjs';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-markup-templating';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';

const codeString = `<script setup lang="ts">
<\/script>

<template>
  <div>
    <ifx-footer copyright-text="© 1999 - 2024 Infineon Technologies AG">
      <div slot="socials">
        <ifx-link
          variant="title"
          href="http://infineon.com"
          aria-label="Go to Homepage">
          <ifx-icon icon="home-16" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://facebook.com/infineon"
          aria-label="Follow us on Facebook">
          <ifx-icon icon="facebook" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://youtube.com/infineon"
          aria-label="Follow us on Youtube">
          <ifx-icon icon="youtube" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://instagram.com/infineon"
          aria-label="Follow us on Instagram">
          <ifx-icon icon="instagram" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://linkedin.com/infineon"
          aria-label="Follow us on LinkedIn">
          <ifx-icon icon="linkedin" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://xing.com/infineon"
          aria-label="Follow us on Xing">
          <ifx-icon icon="xing" />
        </ifx-link>
      </div>
      <div slot="info">
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/terms"
          target="_blank">
          Terms
        </ifx-link>
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/imprint"
          target="_blank">
          Imprint
        </ifx-link>
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/privacy-policy"
          target="_blank">
          Privacy policy
        </ifx-link>
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/glossary"
          target="_blank">
          Glossary
        </ifx-link>
      </div>
    </ifx-footer>
  </div>
<\/template>`;

onMounted(() => {
  nextTick(() => {
    Prism.highlightAll();
  });
});
</script>

<template>
  <div>
    <ifx-footer copyright-text="© 1999 - 2024 Infineon Technologies AG">
      <div slot="socials">
        <ifx-link
          variant="title"
          href="http://infineon.com"
          aria-label="Go to Homepage">
          <ifx-icon icon="home-16" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://facebook.com/infineon"
          aria-label="Follow us on Facebook">
          <ifx-icon icon="facebook" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://youtube.com/infineon"
          aria-label="Follow us on Youtube">
          <ifx-icon icon="youtube" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://instagram.com/infineon"
          aria-label="Follow us on Instagram">
          <ifx-icon icon="instagram" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://linkedin.com/infineon"
          aria-label="Follow us on LinkedIn">
          <ifx-icon icon="linkedin" />
        </ifx-link>
        <ifx-link
          variant="title"
          href="http://xing.com/infineon"
          aria-label="Follow us on Xing">
          <ifx-icon icon="xing" />
        </ifx-link>
      </div>
      <div slot="info">
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/terms"
          target="_blank">
          Terms
        </ifx-link>
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/imprint"
          target="_blank">
          Imprint
        </ifx-link>
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/privacy-policy"
          target="_blank">
          Privacy policy
        </ifx-link>
        <ifx-link
          variant="menu"
          href="https://yourwebsite.com/glossary"
          target="_blank">
          Glossary
        </ifx-link>
      </div>
    </ifx-footer>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
