// examples/react-example/src/generated/IfxIndicatorExample.tsx
import { useState } from 'react';
import { IfxButton, IfxIndicator } from '@infineon/infineon-design-system-react';

export function IfxIndicatorExample() {
  const [inverted, setInverted] = useState(false);

  const handleInvertedChange = () => setInverted((v) => !v);

  const controlledProps = {
    "inverted": inverted,
  } as Record<string, unknown>;
  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["inverted", controlledProps["inverted"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxIndicator } from '@infineon/infineon-design-system-react';

export function IfxIndicatorExample() {
  return (
      <IfxIndicator
        variant="number"
        number={1}
        inverted={String(controlledProps.inverted ?? "false")}
        __CONTROLLED_PROPS__ />
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxIndicator
        variant="number"
        number={1}
        inverted={String(controlledProps.inverted ?? "false")}
        {...(controlledProps as any)} />
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={handleInvertedChange}>Toggle Inverted</IfxButton>
	      </div>
	      

	      <div className="state">
	          <div><b>inverted:</b> {String(inverted)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

// examples/vue-example/src/generated/IfxIndicatorExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxIndicator } from '@infineon/infineon-design-system-vue';

const inverted = ref(false);

const handleInvertedChange = () => { inverted.value = !inverted.value; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "inverted": inverted.value,
}));

const getInputValue = (event: Event) => String((event.target as HTMLInputElement | null)?.value ?? "");

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["inverted", inverted.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxIndicator } from '@infineon/infineon-design-system-vue';
${'</'}script>

<template>
  <div>
    <ifx-indicator
      variant="number"
      :number="1"
      :inverted="String(controlledProps.inverted ?? "false")"
      __CONTROLLED_PROPS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-indicator
      variant="number"
      :number="1"
      :inverted="String(controlledProps.inverted ?? "false")"
      v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="handleInvertedChange">Toggle Inverted</ifx-button>
    </div>
    

    <div class="state">
      <div><b>inverted:</b> {{ String(inverted) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
