// examples/angular-standalone-example/src/app/generated/ifx-indicator-example/ifx-indicator-example.ts
import { IfxButton, IfxIndicator } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-indicator-example',
  imports: [ IfxButton, IfxIndicator ],
  templateUrl: './ifx-indicator-example.html',
	styleUrl: './ifx-indicator-example.scss'
})
export class IfxIndicatorExample {
  protected readonly tsCode = `import { IfxButton, IfxIndicator } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-indicator-example&#039;,
  imports: [ IfxButton, IfxIndicator ],
  templateUrl: &#039;./ifx-indicator-example.html&#039;,
	styleUrl: &#039;./ifx-indicator-example.scss&#039;
})
export class IfxIndicatorExample {}`;
  protected get htmlCode(): string {
    const controlledAttrs = [
      ["variant", this.controlledProps["variant"]],
    ]
			.map(([name, value]) => '    ' + String(name) + '=&quot;' + String(value) + '&quot;')
      .join("\n");

    return `  &lt;ifx-indicator
    number=&quot;1&quot;
    __CONTROLLED_ATTRS__&gt;&lt;/ifx-indicator&gt;`.replace("__CONTROLLED_ATTRS__", controlledAttrs);
  }
  protected readonly variantOptions = ["number","dot"];
  protected variantIndex = 0;

  protected toggleVariant() { this.variantIndex = (this.variantIndex + 1) % this.variantOptions.length; }

  protected get controlledProps(): Record<string, unknown> {
    return {
      "variant": this.variantOptions[this.variantIndex],
    };
  }
}

// examples/vue-example/src/generated/IfxIndicatorExample.vue
<script setup lang="ts">

import { IfxButton, IfxIndicator } from '@infineon/infineon-design-system-vue';

import { computed, ref } from 'vue';

const variantOptions = ["number","dot"];
const variantIndex = ref(0);
const inverted = ref(false);

const toggleVariant = () => (variantIndex.value = (variantIndex.value + 1) % variantOptions.length);
const toggleInverted = () => (inverted.value = !inverted.value);

const controlledProps = computed(() => ({
  "variant": variantOptions[variantIndex.value],
  "inverted": inverted.value,
}));

const formatAttrValueForCode = (value: unknown): string => {
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  if (value === null) return "null";
  if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
    return JSON.stringify(value);
  }
  return String(value).replace(/"/g, '&quot;');
};

const controlledAttrsCode = [
  ["variant", controlledProps.value["variant"]],
  ["inverted", controlledProps.value["inverted"]],
]
	.map(([name, value]) => '      ' + String(name) + '="' + formatAttrValueForCode(value) + '"')
  .join("\n");

const codeString = `<script setup lang="ts">
${'</'}script>

<template>
  <div>
    <ifx-indicator
      :number=1
      __CONTROLLED_ATTRS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_ATTRS__", controlledAttrsCode);

</script>

<template>
  <div>
    <ifx-indicator
      :number=1
      v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <IfxButton variant="secondary" @click="toggleVariant">Toggle Variant</IfxButton>
      <IfxButton variant="secondary" @click="toggleInverted">Toggle Inverted</IfxButton>
    </div>

    <div class="state">
        <div><b>variant:</b> {{ String(variantOptions[variantIndex.value]) }}</div>
        <div><b>inverted:</b> {{ String(inverted.value) }}</div>
    </div>

    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
