// examples/react-example/src/generated/IfxPaginationExample.tsx
import { useState } from 'react';
import { IfxButton, IfxPagination, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxPaginationExample() {
  const [currentPage, setCurrentPage] = useState("1");
  const [total, setTotal] = useState("50");
  const [itemsPerPage, setItemsPerPage] = useState("[{\"value\":\"10\",\"selected\":true}, {\"value\":\"20\",\"selected\":false}, {\"value\":\"30\",\"selected\":false}, {\"value\":\"all\",\"selected\":false}]");
  const [showItemsPerPage, setShowItemsPerPage] = useState(true);
  const [itemsPerPageLabel, setItemsPerPageLabel] = useState("Result per Pages");

  const toggleCurrentPage = (value: string) => setCurrentPage(value);
  const toggleTotal = (value: string) => setTotal(value);
  const toggleItemsPerPage = (value: string) => setItemsPerPage(value);
  const toggleShowItemsPerPage = () => setShowItemsPerPage((v) => !v);
  const toggleItemsPerPageLabel = (value: string) => setItemsPerPageLabel(value);

  const controlledProps = {
    "currentPage": currentPage,
    "total": total,
    "itemsPerPage": itemsPerPage,
    "showItemsPerPage": showItemsPerPage,
    "itemsPerPageLabel": itemsPerPageLabel,
  } as Record<string, unknown>;
  const handleItemsPerPageChange = (event: CustomEvent) => {
    console.log('ifxItemsPerPageChange:', event);
    // Add your handler logic here
  };

  const handlePageChange = (event: CustomEvent) => {
    console.log('ifxPageChange:', event);
    // Add your handler logic here
  };

  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["currentPage", controlledProps["currentPage"]],
    ["total", controlledProps["total"]],
    ["itemsPerPage", controlledProps["itemsPerPage"]],
    ["showItemsPerPage", controlledProps["showItemsPerPage"]],
    ["itemsPerPageLabel", controlledProps["itemsPerPageLabel"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxPagination } from '@infineon/infineon-design-system-react';

export function IfxPaginationExample() {
  const handleItemsPerPageChange = (event: CustomEvent) => {
    console.log('ifxItemsPerPageChange:', event);
    // Add your handler logic here
  };

  const handlePageChange = (event: CustomEvent) => {
    console.log('ifxPageChange:', event);
    // Add your handler logic here
  };

  return (
      <IfxPagination
        onIfxItemsPerPageChange={handleItemsPerPageChange}
        onIfxPageChange={handlePageChange}
        __CONTROLLED_PROPS__ />
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxPagination
        onIfxItemsPerPageChange={handleItemsPerPageChange}
        onIfxPageChange={handlePageChange}
        {...(controlledProps as any)} />
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={toggleShowItemsPerPage}>Toggle ShowItemsPerPage</IfxButton>
	      </div>
	      <div className="controls controls-input">
        <IfxTextField label="currentPage" type="text" value={String(currentPage)} onInput={(event) => toggleCurrentPage(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="total" type="text" value={String(total)} onInput={(event) => toggleTotal(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="itemsPerPage" type="text" value={String(itemsPerPage)} onInput={(event) => toggleItemsPerPage(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="itemsPerPageLabel" type="text" value={String(itemsPerPageLabel)} onInput={(event) => toggleItemsPerPageLabel(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
	      </div>

	      <div className="state">
	          <div><b>currentPage:</b> {String(currentPage)}</div>
          <div><b>total:</b> {String(total)}</div>
          <div><b>itemsPerPage:</b> {String(itemsPerPage)}</div>
          <div><b>showItemsPerPage:</b> {String(showItemsPerPage)}</div>
          <div><b>itemsPerPageLabel:</b> {String(itemsPerPageLabel)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

// examples/vue-example/src/generated/IfxPaginationExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxPagination, IfxTextField } from '@infineon/infineon-design-system-vue';

const currentPage = ref("1");
const total = ref("50");
const itemsPerPage = ref("[{\"value\":\"10\",\"selected\":true}, {\"value\":\"20\",\"selected\":false}, {\"value\":\"30\",\"selected\":false}, {\"value\":\"all\",\"selected\":false}]");
const showItemsPerPage = ref(true);
const itemsPerPageLabel = ref("Result per Pages");

const toggleCurrentPage = (nextValue: string) => { currentPage.value = nextValue; };
const toggleTotal = (nextValue: string) => { total.value = nextValue; };
const toggleItemsPerPage = (nextValue: string) => { itemsPerPage.value = nextValue; };
const toggleShowItemsPerPage = () => { showItemsPerPage.value = !showItemsPerPage.value; };
const toggleItemsPerPageLabel = (nextValue: string) => { itemsPerPageLabel.value = nextValue; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "currentPage": currentPage.value,
  "total": total.value,
  "itemsPerPage": itemsPerPage.value,
  "showItemsPerPage": showItemsPerPage.value,
  "itemsPerPageLabel": itemsPerPageLabel.value,
}));

const handleItemsPerPageChange = (event: CustomEvent) => {
  console.log('ifxItemsPerPageChange:', event);
  // Add your handler logic here
};

const handlePageChange = (event: CustomEvent) => {
  console.log('ifxPageChange:', event);
  // Add your handler logic here
};

const getInputValue = (event: Event) => String((event.target as HTMLInputElement | null)?.value ?? "");

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["currentPage", currentPage.value],
  ["total", total.value],
  ["itemsPerPage", itemsPerPage.value],
  ["showItemsPerPage", showItemsPerPage.value],
  ["itemsPerPageLabel", itemsPerPageLabel.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxPagination } from '@infineon/infineon-design-system-vue';

const handleItemsPerPageChange = (event: CustomEvent) => {
  console.log('ifxItemsPerPageChange:', event);
  // Add your handler logic here
};

const handlePageChange = (event: CustomEvent) => {
  console.log('ifxPageChange:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-pagination
      @ifxItemsPerPageChange="handleItemsPerPageChange"
      @ifxPageChange="handlePageChange"
      __CONTROLLED_PROPS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-pagination
      @ifxItemsPerPageChange="handleItemsPerPageChange"
      @ifxPageChange="handlePageChange"
      v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="toggleShowItemsPerPage">Toggle ShowItemsPerPage</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="currentPage" type="text" :value="String(currentPage)" @input="toggleCurrentPage(getInputValue($event))" />
        <ifx-text-field label="total" type="text" :value="String(total)" @input="toggleTotal(getInputValue($event))" />
        <ifx-text-field label="itemsPerPage" type="text" :value="String(itemsPerPage)" @input="toggleItemsPerPage(getInputValue($event))" />
        <ifx-text-field label="itemsPerPageLabel" type="text" :value="String(itemsPerPageLabel)" @input="toggleItemsPerPageLabel(getInputValue($event))" />
    </div>

    <div class="state">
      <div><b>currentPage:</b> {{ String(currentPage) }}</div>
      <div><b>total:</b> {{ String(total) }}</div>
      <div><b>itemsPerPage:</b> {{ String(itemsPerPage) }}</div>
      <div><b>showItemsPerPage:</b> {{ String(showItemsPerPage) }}</div>
      <div><b>itemsPerPageLabel:</b> {{ String(itemsPerPageLabel) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
