// examples/react-example/src/generated/IfxRadioButtonExample.tsx
import { useState } from 'react';
import { IfxButton, IfxRadioButton, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxRadioButtonExample() {
  const [error, setError] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [checked, setChecked] = useState(false);
  const sizeOptions = ["s","m"];
  const [sizeIndex, setSizeIndex] = useState(0);
  const [name, setName] = useState("radio-button");
  const [value, setValue] = useState("radio");

  const handleErrorChange = () => setError((v) => !v);
  const handleDisabledChange = () => setDisabled((v) => !v);
  const handleCheckedChange = () => setChecked((v) => !v);
  const handleSizeChange = () => setSizeIndex((i) => (i + 1) % sizeOptions.length);
  const handleNameChange = (value: string) => setName(value);
  const handleValueChange = (value: string) => setValue(value);

  const controlledProps = {
    "error": error,
    "disabled": disabled,
    "checked": checked,
    "size": sizeOptions[sizeIndex],
    "name": name,
    "value": value,
  } as Record<string, unknown>;
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  const handleError = (event: CustomEvent) => {
    console.log('ifxError:', event);
    // Add your handler logic here
  };

  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["error", controlledProps["error"]],
    ["disabled", controlledProps["disabled"]],
    ["checked", controlledProps["checked"]],
    ["size", controlledProps["size"]],
    ["name", controlledProps["name"]],
    ["value", controlledProps["value"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxRadioButton } from '@infineon/infineon-design-system-react';

export function IfxRadioButtonExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  const handleError = (event: CustomEvent) => {
    console.log('ifxError:', event);
    // Add your handler logic here
  };

  return (
      <IfxRadioButton
        onIfxChange={handleChange}
        onIfxError={handleError}
        error={String(controlledProps.error ?? "false")}
        disabled={String(controlledProps.disabled ?? "false")}
        checked={String(controlledProps.checked ?? "false")}
        size={String(controlledProps.size ?? "s")}
        name={String(controlledProps.name ?? "radio-button")}
        value={String(controlledProps.value ?? "radio")}
        __CONTROLLED_PROPS__>
        Text
      </IfxRadioButton>
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxRadioButton
        onIfxChange={handleChange}
        onIfxError={handleError}
        error={String(controlledProps.error ?? "false")}
        disabled={String(controlledProps.disabled ?? "false")}
        checked={String(controlledProps.checked ?? "false")}
        size={String(controlledProps.size ?? "s")}
        name={String(controlledProps.name ?? "radio-button")}
        value={String(controlledProps.value ?? "radio")}
        {...(controlledProps as any)}>
        Text
      </IfxRadioButton>
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={handleErrorChange}>Toggle Error</IfxButton>
        <IfxButton variant="secondary" onClick={handleDisabledChange}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={handleCheckedChange}>Toggle Checked</IfxButton>
        <IfxButton variant="secondary" onClick={handleSizeChange}>Toggle Size</IfxButton>
	      </div>
	      <div className="controls controls-input">
        <IfxTextField label="name" type="text" value={String(name)} onInput={(event) => handleNameChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="value" type="text" value={String(value)} onInput={(event) => handleValueChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
	      </div>

	      <div className="state">
	          <div><b>error:</b> {String(error)}</div>
          <div><b>disabled:</b> {String(disabled)}</div>
          <div><b>checked:</b> {String(checked)}</div>
          <div><b>size:</b> {String(sizeOptions[sizeIndex])}</div>
          <div><b>name:</b> {String(name)}</div>
          <div><b>value:</b> {String(value)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

// examples/vue-example/src/generated/IfxRadioButtonExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxRadioButton, IfxTextField } from '@infineon/infineon-design-system-vue';

const error = ref(false);
const disabled = ref(false);
const checked = ref(false);
const sizeOptions = ["s","m"];
const sizeIndex = ref(0);
const name = ref("radio-button");
const value = ref("radio");

const handleErrorChange = () => { error.value = !error.value; };
const handleDisabledChange = () => { disabled.value = !disabled.value; };
const handleCheckedChange = () => { checked.value = !checked.value; };
const handleSizeChange = () => { sizeIndex.value = (sizeIndex.value + 1) % sizeOptions.length; };
const handleNameChange = (nextValue: string) => { name.value = nextValue; };
const handleValueChange = (nextValue: string) => { value.value = nextValue; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "error": error.value,
  "disabled": disabled.value,
  "checked": checked.value,
  "size": sizeOptions[sizeIndex.value],
  "name": name.value,
  "value": value.value,
}));

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const handleError = (event: CustomEvent) => {
  console.log('ifxError:', event);
  // Add your handler logic here
};

const getInputValue = (event: Event) => String((event.target as HTMLInputElement | null)?.value ?? "");

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["error", error.value],
  ["disabled", disabled.value],
  ["checked", checked.value],
  ["size", sizeOptions[sizeIndex.value]],
  ["name", name.value],
  ["value", value.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxRadioButton } from '@infineon/infineon-design-system-vue';

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const handleError = (event: CustomEvent) => {
  console.log('ifxError:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-radio-button
      @ifxChange="handleChange"
      @ifxError="handleError"
      :error="String(controlledProps.error ?? 'false')"
      :disabled="String(controlledProps.disabled ?? 'false')"
      :checked="String(controlledProps.checked ?? 'false')"
      :size="String(controlledProps.size ?? 's')"
      :name="String(controlledProps.name ?? 'radio-button')"
      :value="String(controlledProps.value ?? 'radio')"
      __CONTROLLED_PROPS__>
      Text
    </ifx-radio-button>
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-radio-button
      @ifxChange="handleChange"
      @ifxError="handleError"
      :error="String(controlledProps.error ?? 'false')"
      :disabled="String(controlledProps.disabled ?? 'false')"
      :checked="String(controlledProps.checked ?? 'false')"
      :size="String(controlledProps.size ?? 's')"
      :name="String(controlledProps.name ?? 'radio-button')"
      :value="String(controlledProps.value ?? 'radio')"
      v-bind="controlledProps">
      Text
    </ifx-radio-button>
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="handleErrorChange">Toggle Error</ifx-button>
        <ifx-button variant="secondary" @click="handleDisabledChange">Toggle Disabled</ifx-button>
        <ifx-button variant="secondary" @click="handleCheckedChange">Toggle Checked</ifx-button>
        <ifx-button variant="secondary" @click="handleSizeChange">Toggle Size</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="name" type="text" :value="String(name)" @input="handleNameChange(getInputValue($event))" />
        <ifx-text-field label="value" type="text" :value="String(value)" @input="handleValueChange(getInputValue($event))" />
    </div>

    <div class="state">
      <div><b>error:</b> {{ String(error) }}</div>
      <div><b>disabled:</b> {{ String(disabled) }}</div>
      <div><b>checked:</b> {{ String(checked) }}</div>
      <div><b>size:</b> {{ String(sizeOptions[sizeIndex]) }}</div>
      <div><b>name:</b> {{ String(name) }}</div>
      <div><b>value:</b> {{ String(value) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
