// examples/angular-standalone-example/src/app/generated/ifx-radio-button-group-example/ifx-radio-button-group-example.ts
import { IfxRadioButton, IfxRadioButtonGroup } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-radio-button-group-example',
  imports: [ IfxRadioButton, IfxRadioButtonGroup ],
  templateUrl: './ifx-radio-button-group-example.html',
  styleUrl: './ifx-radio-button-group-example.scss'
})
export class IfxRadioButtonGroupExample {
  protected readonly tsCode = `import { IfxRadioButton, IfxRadioButtonGroup } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-radio-button-group-example&#039;,
  imports: [ IfxRadioButton, IfxRadioButtonGroup ],
  templateUrl: &#039;./ifx-radio-button-group-example.html&#039;,
  styleUrl: &#039;./ifx-radio-button-group-example.scss&#039;
})
export class IfxRadioButtonGroupExample {
  protected handleSetGroupError(event: CustomEvent) {
    console.log(&#039;setGroupError:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-radio-button-group
    alignment=&quot;vertical&quot;
    group-label-text=&quot;Group Label&quot;
    caption-text=&quot;Caption text, description, error notification&quot;&gt;
    &lt;ifx-radio-button
      value=&quot;0&quot;
      size=&quot;m&quot;&gt;Option 0&lt;/ifx-radio-button&gt;
    &lt;ifx-radio-button
      value=&quot;1&quot;
      size=&quot;m&quot;&gt;Option 1&lt;/ifx-radio-button&gt;
    &lt;ifx-radio-button
      value=&quot;2&quot;
      size=&quot;m&quot;&gt;Option 2&lt;/ifx-radio-button&gt;
  &lt;/ifx-radio-button-group&gt;`;

  protected handleSetGroupError(event: CustomEvent) {
    console.log('setGroupError:', event);
    // Add your handler logic here
  }
}

// examples/vue-example/src/generated/IfxRadioButtonGroupExample.vue
<script setup lang="ts">

import { IfxRadioButton, IfxRadioButtonGroup } from '@infineon/infineon-design-system-vue';

const handleSetGroupError = (event: CustomEvent) => {
  console.log('setGroupError:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleSetGroupError = (event: CustomEvent) => {
  console.log('setGroupError:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-radio-button-group
      alignment="vertical"
      group-label-text="Group Label"
      caption-text="Caption text, description, error notification">
      <ifx-radio-button
        :value=0
        size="m">
        Option 0
      </ifx-radio-button>
      <ifx-radio-button
        :value=1
        size="m">
        Option 1
      </ifx-radio-button>
      <ifx-radio-button
        :value=2
        size="m">
        Option 2
      </ifx-radio-button>
    </ifx-radio-button-group>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-radio-button-group
      alignment="vertical"
      group-label-text="Group Label"
      caption-text="Caption text, description, error notification">
      <ifx-radio-button
        :value=0
        size="m">
        Option 0
      </ifx-radio-button>
      <ifx-radio-button
        :value=1
        size="m">
        Option 1
      </ifx-radio-button>
      <ifx-radio-button
        :value=2
        size="m">
        Option 2
      </ifx-radio-button>
    </ifx-radio-button-group>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
