// examples/react-example/src/generated/IfxSearchFieldExample.tsx
import { useState } from 'react';
import { IfxButton, IfxSearchField, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxSearchFieldExample() {
  const [showDeleteIcon, setShowDeleteIcon] = useState(true);
  const [disabled, setDisabled] = useState(false);
  const sizeOptions = ["s","m"];
  const [sizeIndex, setSizeIndex] = useState(1);
  const [placeholder, setPlaceholder] = useState("Search...");
  const [maxlength, setMaxlength] = useState(0);
  const [value, setValue] = useState("");
  const [autocomplete, setAutocomplete] = useState("on");
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [enableHistory, setEnableHistory] = useState(true);
  const [maxSuggestions, setMaxSuggestions] = useState(10);
  const [maxHistoryItems, setMaxHistoryItems] = useState(5);
  const [historyKey, setHistoryKey] = useState("ifx-search-history");
  const [historyHeaderText, setHistoryHeaderText] = useState("Recent Searches");
  const [ariaLabelText, setAriaLabelText] = useState("Search field");
  const [ariaLabelledBy, setAriaLabelledBy] = useState("");
  const [ariaDescribedBy, setAriaDescribedBy] = useState("");
  const [deleteIconAriaLabel, setDeleteIconAriaLabel] = useState("Clear search");
  const [historyDeleteAriaLabel, setHistoryDeleteAriaLabel] = useState("Remove from history");
  const [dropdownAriaLabel, setDropdownAriaLabel] = useState("Search suggestions and history");
  const [suggestionAriaLabel, setSuggestionAriaLabel] = useState("Search suggestion");
  const [historyItemAriaLabel, setHistoryItemAriaLabel] = useState("Search history item");

  const handleShowDeleteIconChange = () => setShowDeleteIcon((v) => !v);
  const handleDisabledChange = () => setDisabled((v) => !v);
  const handleSizeChange = () => setSizeIndex((i) => (i + 1) % sizeOptions.length);
  const handlePlaceholderChange = (value: string) => setPlaceholder(value);
  const handleMaxlengthChange = (value: string) => setMaxlength(Number(value));
  const handleValueChange = (value: string) => setValue(value);
  const handleAutocompleteChange = (value: string) => setAutocomplete(value);
  const handleShowSuggestionsChange = () => setShowSuggestions((v) => !v);
  const handleEnableHistoryChange = () => setEnableHistory((v) => !v);
  const handleMaxSuggestionsChange = (value: string) => setMaxSuggestions(Number(value));
  const handleMaxHistoryItemsChange = (value: string) => setMaxHistoryItems(Number(value));
  const handleHistoryKeyChange = (value: string) => setHistoryKey(value);
  const handleHistoryHeaderTextChange = (value: string) => setHistoryHeaderText(value);
  const handleAriaLabelTextChange = (value: string) => setAriaLabelText(value);
  const handleAriaLabelledByChange = (value: string) => setAriaLabelledBy(value);
  const handleAriaDescribedByChange = (value: string) => setAriaDescribedBy(value);
  const handleDeleteIconAriaLabelChange = (value: string) => setDeleteIconAriaLabel(value);
  const handleHistoryDeleteAriaLabelChange = (value: string) => setHistoryDeleteAriaLabel(value);
  const handleDropdownAriaLabelChange = (value: string) => setDropdownAriaLabel(value);
  const handleSuggestionAriaLabelChange = (value: string) => setSuggestionAriaLabel(value);
  const handleHistoryItemAriaLabelChange = (value: string) => setHistoryItemAriaLabel(value);

  const controlledProps = {
    "showDeleteIcon": showDeleteIcon,
    "disabled": disabled,
    "size": sizeOptions[sizeIndex],
    "placeholder": placeholder,
    "maxlength": maxlength,
    "value": value,
    "autocomplete": autocomplete,
    "showSuggestions": showSuggestions,
    "enableHistory": enableHistory,
    "maxSuggestions": maxSuggestions,
    "maxHistoryItems": maxHistoryItems,
    "historyKey": historyKey,
    "historyHeaderText": historyHeaderText,
    "ariaLabelText": ariaLabelText,
    "ariaLabelledBy": ariaLabelledBy,
    "ariaDescribedBy": ariaDescribedBy,
    "deleteIconAriaLabel": deleteIconAriaLabel,
    "historyDeleteAriaLabel": historyDeleteAriaLabel,
    "dropdownAriaLabel": dropdownAriaLabel,
    "suggestionAriaLabel": suggestionAriaLabel,
    "historyItemAriaLabel": historyItemAriaLabel,
  } as Record<string, unknown>;
  const handleBlur = (event: CustomEvent) => {
    console.log('ifxBlur:', event);
    // Add your handler logic here
  };

  const handleFocus = (event: CustomEvent) => {
    console.log('ifxFocus:', event);
    // Add your handler logic here
  };

  const handleInput = (event: CustomEvent) => {
    console.log('ifxInput:', event);
    // Add your handler logic here
  };

  const handleSuggestionRequested = (event: CustomEvent) => {
    console.log('ifxSuggestionRequested:', event);
    // Add your handler logic here
  };

  const handleSuggestionSelected = (event: CustomEvent) => {
    console.log('ifxSuggestionSelected:', event);
    // Add your handler logic here
  };

  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["showDeleteIcon", controlledProps["showDeleteIcon"]],
    ["disabled", controlledProps["disabled"]],
    ["size", controlledProps["size"]],
    ["placeholder", controlledProps["placeholder"]],
    ["maxlength", controlledProps["maxlength"]],
    ["value", controlledProps["value"]],
    ["autocomplete", controlledProps["autocomplete"]],
    ["showSuggestions", controlledProps["showSuggestions"]],
    ["enableHistory", controlledProps["enableHistory"]],
    ["maxSuggestions", controlledProps["maxSuggestions"]],
    ["maxHistoryItems", controlledProps["maxHistoryItems"]],
    ["historyKey", controlledProps["historyKey"]],
    ["historyHeaderText", controlledProps["historyHeaderText"]],
    ["ariaLabelText", controlledProps["ariaLabelText"]],
    ["ariaLabelledBy", controlledProps["ariaLabelledBy"]],
    ["ariaDescribedBy", controlledProps["ariaDescribedBy"]],
    ["deleteIconAriaLabel", controlledProps["deleteIconAriaLabel"]],
    ["historyDeleteAriaLabel", controlledProps["historyDeleteAriaLabel"]],
    ["dropdownAriaLabel", controlledProps["dropdownAriaLabel"]],
    ["suggestionAriaLabel", controlledProps["suggestionAriaLabel"]],
    ["historyItemAriaLabel", controlledProps["historyItemAriaLabel"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxSearchField } from '@infineon/infineon-design-system-react';

export function IfxSearchFieldExample() {
  const handleBlur = (event: CustomEvent) => {
    console.log('ifxBlur:', event);
    // Add your handler logic here
  };

  const handleFocus = (event: CustomEvent) => {
    console.log('ifxFocus:', event);
    // Add your handler logic here
  };

  const handleInput = (event: CustomEvent) => {
    console.log('ifxInput:', event);
    // Add your handler logic here
  };

  const handleSuggestionRequested = (event: CustomEvent) => {
    console.log('ifxSuggestionRequested:', event);
    // Add your handler logic here
  };

  const handleSuggestionSelected = (event: CustomEvent) => {
    console.log('ifxSuggestionSelected:', event);
    // Add your handler logic here
  };

  return (
      <IfxSearchField
        onIfxBlur={handleBlur}
        onIfxFocus={handleFocus}
        onIfxInput={handleInput}
        onIfxSuggestionRequested={handleSuggestionRequested}
        onIfxSuggestionSelected={handleSuggestionSelected}
        __CONTROLLED_PROPS__ />
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxSearchField
        onIfxBlur={handleBlur}
        onIfxFocus={handleFocus}
        onIfxInput={handleInput}
        onIfxSuggestionRequested={handleSuggestionRequested}
        onIfxSuggestionSelected={handleSuggestionSelected}
        {...(controlledProps as any)} />
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={handleShowDeleteIconChange}>Toggle ShowDeleteIcon</IfxButton>
        <IfxButton variant="secondary" onClick={handleDisabledChange}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={handleSizeChange}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={handleShowSuggestionsChange}>Toggle ShowSuggestions</IfxButton>
        <IfxButton variant="secondary" onClick={handleEnableHistoryChange}>Toggle EnableHistory</IfxButton>
	      </div>
	      <div className="controls controls-input">
        <IfxTextField label="placeholder" type="text" value={String(placeholder)} onInput={(event) => handlePlaceholderChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="maxlength" type="text" value={String(maxlength)} onInput={(event) => handleMaxlengthChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="value" type="text" value={String(value)} onInput={(event) => handleValueChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="autocomplete" type="text" value={String(autocomplete)} onInput={(event) => handleAutocompleteChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="maxSuggestions" type="text" value={String(maxSuggestions)} onInput={(event) => handleMaxSuggestionsChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="maxHistoryItems" type="text" value={String(maxHistoryItems)} onInput={(event) => handleMaxHistoryItemsChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="historyKey" type="text" value={String(historyKey)} onInput={(event) => handleHistoryKeyChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="historyHeaderText" type="text" value={String(historyHeaderText)} onInput={(event) => handleHistoryHeaderTextChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="ariaLabelText" type="text" value={String(ariaLabelText)} onInput={(event) => handleAriaLabelTextChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="ariaLabelledBy" type="text" value={String(ariaLabelledBy)} onInput={(event) => handleAriaLabelledByChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="ariaDescribedBy" type="text" value={String(ariaDescribedBy)} onInput={(event) => handleAriaDescribedByChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="deleteIconAriaLabel" type="text" value={String(deleteIconAriaLabel)} onInput={(event) => handleDeleteIconAriaLabelChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="historyDeleteAriaLabel" type="text" value={String(historyDeleteAriaLabel)} onInput={(event) => handleHistoryDeleteAriaLabelChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="dropdownAriaLabel" type="text" value={String(dropdownAriaLabel)} onInput={(event) => handleDropdownAriaLabelChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="suggestionAriaLabel" type="text" value={String(suggestionAriaLabel)} onInput={(event) => handleSuggestionAriaLabelChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
        <IfxTextField label="historyItemAriaLabel" type="text" value={String(historyItemAriaLabel)} onInput={(event) => handleHistoryItemAriaLabelChange(String((event.target as HTMLInputElement | null)?.value ?? ""))} />
	      </div>

	      <div className="state">
	          <div><b>showDeleteIcon:</b> {String(showDeleteIcon)}</div>
          <div><b>disabled:</b> {String(disabled)}</div>
          <div><b>size:</b> {String(sizeOptions[sizeIndex])}</div>
          <div><b>placeholder:</b> {String(placeholder)}</div>
          <div><b>maxlength:</b> {String(maxlength)}</div>
          <div><b>value:</b> {String(value)}</div>
          <div><b>autocomplete:</b> {String(autocomplete)}</div>
          <div><b>showSuggestions:</b> {String(showSuggestions)}</div>
          <div><b>enableHistory:</b> {String(enableHistory)}</div>
          <div><b>maxSuggestions:</b> {String(maxSuggestions)}</div>
          <div><b>maxHistoryItems:</b> {String(maxHistoryItems)}</div>
          <div><b>historyKey:</b> {String(historyKey)}</div>
          <div><b>historyHeaderText:</b> {String(historyHeaderText)}</div>
          <div><b>ariaLabelText:</b> {String(ariaLabelText)}</div>
          <div><b>ariaLabelledBy:</b> {String(ariaLabelledBy)}</div>
          <div><b>ariaDescribedBy:</b> {String(ariaDescribedBy)}</div>
          <div><b>deleteIconAriaLabel:</b> {String(deleteIconAriaLabel)}</div>
          <div><b>historyDeleteAriaLabel:</b> {String(historyDeleteAriaLabel)}</div>
          <div><b>dropdownAriaLabel:</b> {String(dropdownAriaLabel)}</div>
          <div><b>suggestionAriaLabel:</b> {String(suggestionAriaLabel)}</div>
          <div><b>historyItemAriaLabel:</b> {String(historyItemAriaLabel)}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

// examples/vue-example/src/generated/IfxSearchFieldExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxSearchField, IfxTextField } from '@infineon/infineon-design-system-vue';

const showDeleteIcon = ref(true);
const disabled = ref(false);
const sizeOptions = ["s","m"];
const sizeIndex = ref(1);
const placeholder = ref("Search...");
const maxlength = ref(0);
const value = ref("");
const autocomplete = ref("on");
const showSuggestions = ref(false);
const enableHistory = ref(true);
const maxSuggestions = ref(10);
const maxHistoryItems = ref(5);
const historyKey = ref("ifx-search-history");
const historyHeaderText = ref("Recent Searches");
const ariaLabelText = ref("Search field");
const ariaLabelledBy = ref("");
const ariaDescribedBy = ref("");
const deleteIconAriaLabel = ref("Clear search");
const historyDeleteAriaLabel = ref("Remove from history");
const dropdownAriaLabel = ref("Search suggestions and history");
const suggestionAriaLabel = ref("Search suggestion");
const historyItemAriaLabel = ref("Search history item");

const handleShowDeleteIconChange = () => { showDeleteIcon.value = !showDeleteIcon.value; };
const handleDisabledChange = () => { disabled.value = !disabled.value; };
const handleSizeChange = () => { sizeIndex.value = (sizeIndex.value + 1) % sizeOptions.length; };
const handlePlaceholderChange = (nextValue: string) => { placeholder.value = nextValue; };
const handleMaxlengthChange = (nextValue: string) => { maxlength.value = Number(nextValue); };
const handleValueChange = (nextValue: string) => { value.value = nextValue; };
const handleAutocompleteChange = (nextValue: string) => { autocomplete.value = nextValue; };
const handleShowSuggestionsChange = () => { showSuggestions.value = !showSuggestions.value; };
const handleEnableHistoryChange = () => { enableHistory.value = !enableHistory.value; };
const handleMaxSuggestionsChange = (nextValue: string) => { maxSuggestions.value = Number(nextValue); };
const handleMaxHistoryItemsChange = (nextValue: string) => { maxHistoryItems.value = Number(nextValue); };
const handleHistoryKeyChange = (nextValue: string) => { historyKey.value = nextValue; };
const handleHistoryHeaderTextChange = (nextValue: string) => { historyHeaderText.value = nextValue; };
const handleAriaLabelTextChange = (nextValue: string) => { ariaLabelText.value = nextValue; };
const handleAriaLabelledByChange = (nextValue: string) => { ariaLabelledBy.value = nextValue; };
const handleAriaDescribedByChange = (nextValue: string) => { ariaDescribedBy.value = nextValue; };
const handleDeleteIconAriaLabelChange = (nextValue: string) => { deleteIconAriaLabel.value = nextValue; };
const handleHistoryDeleteAriaLabelChange = (nextValue: string) => { historyDeleteAriaLabel.value = nextValue; };
const handleDropdownAriaLabelChange = (nextValue: string) => { dropdownAriaLabel.value = nextValue; };
const handleSuggestionAriaLabelChange = (nextValue: string) => { suggestionAriaLabel.value = nextValue; };
const handleHistoryItemAriaLabelChange = (nextValue: string) => { historyItemAriaLabel.value = nextValue; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "showDeleteIcon": showDeleteIcon.value,
  "disabled": disabled.value,
  "size": sizeOptions[sizeIndex.value],
  "placeholder": placeholder.value,
  "maxlength": maxlength.value,
  "value": value.value,
  "autocomplete": autocomplete.value,
  "showSuggestions": showSuggestions.value,
  "enableHistory": enableHistory.value,
  "maxSuggestions": maxSuggestions.value,
  "maxHistoryItems": maxHistoryItems.value,
  "historyKey": historyKey.value,
  "historyHeaderText": historyHeaderText.value,
  "ariaLabelText": ariaLabelText.value,
  "ariaLabelledBy": ariaLabelledBy.value,
  "ariaDescribedBy": ariaDescribedBy.value,
  "deleteIconAriaLabel": deleteIconAriaLabel.value,
  "historyDeleteAriaLabel": historyDeleteAriaLabel.value,
  "dropdownAriaLabel": dropdownAriaLabel.value,
  "suggestionAriaLabel": suggestionAriaLabel.value,
  "historyItemAriaLabel": historyItemAriaLabel.value,
}));

const handleBlur = (event: CustomEvent) => {
  console.log('ifxBlur:', event);
  // Add your handler logic here
};

const handleFocus = (event: CustomEvent) => {
  console.log('ifxFocus:', event);
  // Add your handler logic here
};

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleSuggestionRequested = (event: CustomEvent) => {
  console.log('ifxSuggestionRequested:', event);
  // Add your handler logic here
};

const handleSuggestionSelected = (event: CustomEvent) => {
  console.log('ifxSuggestionSelected:', event);
  // Add your handler logic here
};

const getControlInputValue = (event: Event & {
  detail?: unknown;
  target?: { value?: unknown } | null;
}) => {
  const detail = event.detail;

  if (typeof detail === 'string' || typeof detail === 'number') {
    return String(detail);
  }

  if (detail && typeof detail === 'object' && 'value' in detail) {
    return String((detail as { value?: unknown }).value ?? '');
  }

  return String(event.target?.value ?? '');
};

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["show-delete-icon", showDeleteIcon.value],
  ["disabled", disabled.value],
  ["size", sizeOptions[sizeIndex.value]],
  ["placeholder", placeholder.value],
  ["maxlength", maxlength.value],
  ["value", value.value],
  ["autocomplete", autocomplete.value],
  ["show-suggestions", showSuggestions.value],
  ["enable-history", enableHistory.value],
  ["max-suggestions", maxSuggestions.value],
  ["max-history-items", maxHistoryItems.value],
  ["history-key", historyKey.value],
  ["history-header-text", historyHeaderText.value],
  ["aria-label-text", ariaLabelText.value],
  ["aria-labelled-by", ariaLabelledBy.value],
  ["aria-described-by", ariaDescribedBy.value],
  ["delete-icon-aria-label", deleteIconAriaLabel.value],
  ["history-delete-aria-label", historyDeleteAriaLabel.value],
  ["dropdown-aria-label", dropdownAriaLabel.value],
  ["suggestion-aria-label", suggestionAriaLabel.value],
  ["history-item-aria-label", historyItemAriaLabel.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxSearchField } from '@infineon/infineon-design-system-vue';

const handleBlur = (event: CustomEvent) => {
  console.log('ifxBlur:', event);
  // Add your handler logic here
};

const handleFocus = (event: CustomEvent) => {
  console.log('ifxFocus:', event);
  // Add your handler logic here
};

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleSuggestionRequested = (event: CustomEvent) => {
  console.log('ifxSuggestionRequested:', event);
  // Add your handler logic here
};

const handleSuggestionSelected = (event: CustomEvent) => {
  console.log('ifxSuggestionSelected:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-search-field
      @ifxBlur="handleBlur"
      @ifxFocus="handleFocus"
      @ifxInput="handleInput"
      @ifxSuggestionRequested="handleSuggestionRequested"
      @ifxSuggestionSelected="handleSuggestionSelected"
      :show-delete-icon="String(controlledProps.showDeleteIcon ?? 'true')"
      :disabled="String(controlledProps.disabled ?? 'false')"
      :size="String(controlledProps.size ?? 'm')"
      :placeholder="String(controlledProps.placeholder ?? 'Search...')"
      :maxlength="String(controlledProps.maxlength ?? '')"
      :value="String(controlledProps.value ?? '')"
      :autocomplete="String(controlledProps.autocomplete ?? 'on')"
      __CONTROLLED_PROPS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-search-field
      @ifxBlur="handleBlur"
      @ifxFocus="handleFocus"
      @ifxInput="handleInput"
      @ifxSuggestionRequested="handleSuggestionRequested"
      @ifxSuggestionSelected="handleSuggestionSelected"
      :show-delete-icon="String(controlledProps.showDeleteIcon ?? 'true')"
      :disabled="String(controlledProps.disabled ?? 'false')"
      :size="String(controlledProps.size ?? 'm')"
      :placeholder="String(controlledProps.placeholder ?? 'Search...')"
      :maxlength="String(controlledProps.maxlength ?? '')"
      :value="String(controlledProps.value ?? '')"
      :autocomplete="String(controlledProps.autocomplete ?? 'on')"
      v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="handleShowDeleteIconChange">Toggle ShowDeleteIcon</ifx-button>
        <ifx-button variant="secondary" @click="handleDisabledChange">Toggle Disabled</ifx-button>
        <ifx-button variant="secondary" @click="handleSizeChange">Toggle Size</ifx-button>
        <ifx-button variant="secondary" @click="handleShowSuggestionsChange">Toggle ShowSuggestions</ifx-button>
        <ifx-button variant="secondary" @click="handleEnableHistoryChange">Toggle EnableHistory</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="placeholder" type="text" :value="String(placeholder)" @ifxInput="handlePlaceholderChange(getControlInputValue($event))" />
        <ifx-text-field label="maxlength" type="text" :value="String(maxlength)" @ifxInput="handleMaxlengthChange(getControlInputValue($event))" />
        <ifx-text-field label="value" type="text" :value="String(value)" @ifxInput="handleValueChange(getControlInputValue($event))" />
        <ifx-text-field label="autocomplete" type="text" :value="String(autocomplete)" @ifxInput="handleAutocompleteChange(getControlInputValue($event))" />
        <ifx-text-field label="maxSuggestions" type="text" :value="String(maxSuggestions)" @ifxInput="handleMaxSuggestionsChange(getControlInputValue($event))" />
        <ifx-text-field label="maxHistoryItems" type="text" :value="String(maxHistoryItems)" @ifxInput="handleMaxHistoryItemsChange(getControlInputValue($event))" />
        <ifx-text-field label="historyKey" type="text" :value="String(historyKey)" @ifxInput="handleHistoryKeyChange(getControlInputValue($event))" />
        <ifx-text-field label="historyHeaderText" type="text" :value="String(historyHeaderText)" @ifxInput="handleHistoryHeaderTextChange(getControlInputValue($event))" />
        <ifx-text-field label="ariaLabelText" type="text" :value="String(ariaLabelText)" @ifxInput="handleAriaLabelTextChange(getControlInputValue($event))" />
        <ifx-text-field label="ariaLabelledBy" type="text" :value="String(ariaLabelledBy)" @ifxInput="handleAriaLabelledByChange(getControlInputValue($event))" />
        <ifx-text-field label="ariaDescribedBy" type="text" :value="String(ariaDescribedBy)" @ifxInput="handleAriaDescribedByChange(getControlInputValue($event))" />
        <ifx-text-field label="deleteIconAriaLabel" type="text" :value="String(deleteIconAriaLabel)" @ifxInput="handleDeleteIconAriaLabelChange(getControlInputValue($event))" />
        <ifx-text-field label="historyDeleteAriaLabel" type="text" :value="String(historyDeleteAriaLabel)" @ifxInput="handleHistoryDeleteAriaLabelChange(getControlInputValue($event))" />
        <ifx-text-field label="dropdownAriaLabel" type="text" :value="String(dropdownAriaLabel)" @ifxInput="handleDropdownAriaLabelChange(getControlInputValue($event))" />
        <ifx-text-field label="suggestionAriaLabel" type="text" :value="String(suggestionAriaLabel)" @ifxInput="handleSuggestionAriaLabelChange(getControlInputValue($event))" />
        <ifx-text-field label="historyItemAriaLabel" type="text" :value="String(historyItemAriaLabel)" @ifxInput="handleHistoryItemAriaLabelChange(getControlInputValue($event))" />
    </div>

    <div class="state">
      <div><b>showDeleteIcon:</b> {{ String(showDeleteIcon) }}</div>
      <div><b>disabled:</b> {{ String(disabled) }}</div>
      <div><b>size:</b> {{ String(sizeOptions[sizeIndex]) }}</div>
      <div><b>placeholder:</b> {{ String(placeholder) }}</div>
      <div><b>maxlength:</b> {{ String(maxlength) }}</div>
      <div><b>value:</b> {{ String(value) }}</div>
      <div><b>autocomplete:</b> {{ String(autocomplete) }}</div>
      <div><b>showSuggestions:</b> {{ String(showSuggestions) }}</div>
      <div><b>enableHistory:</b> {{ String(enableHistory) }}</div>
      <div><b>maxSuggestions:</b> {{ String(maxSuggestions) }}</div>
      <div><b>maxHistoryItems:</b> {{ String(maxHistoryItems) }}</div>
      <div><b>historyKey:</b> {{ String(historyKey) }}</div>
      <div><b>historyHeaderText:</b> {{ String(historyHeaderText) }}</div>
      <div><b>ariaLabelText:</b> {{ String(ariaLabelText) }}</div>
      <div><b>ariaLabelledBy:</b> {{ String(ariaLabelledBy) }}</div>
      <div><b>ariaDescribedBy:</b> {{ String(ariaDescribedBy) }}</div>
      <div><b>deleteIconAriaLabel:</b> {{ String(deleteIconAriaLabel) }}</div>
      <div><b>historyDeleteAriaLabel:</b> {{ String(historyDeleteAriaLabel) }}</div>
      <div><b>dropdownAriaLabel:</b> {{ String(dropdownAriaLabel) }}</div>
      <div><b>suggestionAriaLabel:</b> {{ String(suggestionAriaLabel) }}</div>
      <div><b>historyItemAriaLabel:</b> {{ String(historyItemAriaLabel) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
