// examples/angular-module-example/src/app/generated/ifx-stepper-example/ifx-stepper-example.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-stepper-example',
  templateUrl: './ifx-stepper-example.html',
  styleUrl: './ifx-stepper-example.scss',
  standalone: false
})
export class IfxStepperExample {
  protected readonly tsCode = `import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-stepper-example&#039;,
  templateUrl: &#039;./ifx-stepper-example.html&#039;,
  styleUrl: &#039;./ifx-stepper-example.scss&#039;,
  standalone: false
})
export class IfxStepperExample {
  protected handleChange(event: any) {
    console.log(&#039;ifxChange:&#039;, event.detail);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-stepper
    active-step=&quot;2&quot;
    aria-label=&quot;true&quot;
    aria-current=&quot;true&quot;
    show-step-number=&quot;false&quot;
    variant=&quot;default&quot;&gt;
    &lt;ifx-step&gt;
      Step Label 1
    &lt;/ifx-step&gt;
    &lt;ifx-step&gt;
      Step Label 2
    &lt;/ifx-step&gt;
    &lt;ifx-step&gt;
      Step Label 3
    &lt;/ifx-step&gt;
    &lt;ifx-step&gt;
      Step Label 4
    &lt;/ifx-step&gt;
    &lt;ifx-step&gt;
      Step Label 5
    &lt;/ifx-step&gt;
  &lt;/ifx-stepper&gt;`;

  protected handleChange(event: any) {
    console.log('ifxChange:', event.detail);
    // Add your handler logic here
  }
}

// examples/vue-example/src/generated/IfxStepperExample.vue
<script setup lang="ts">
import { onMounted, nextTick } from 'vue';
import Prism from 'prismjs';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-markup-templating';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';
import { IfxStep, IfxStepper } from '@infineon/infineon-design-system-vue';

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-stepper
      active-step="2"
      aria-label=""
      aria-current=""
      :show-step-number="false"
      variant="default">
      <ifx-step>
        Step Label 1
      </ifx-step>
      <ifx-step>
        Step Label 2
      </ifx-step>
      <ifx-step>
        Step Label 3
      </ifx-step>
      <ifx-step>
        Step Label 4
      </ifx-step>
      <ifx-step>
        Step Label 5
      </ifx-step>
    </ifx-stepper>
  </div>
${'</'}template>`;

onMounted(() => {
  nextTick(() => {
    Prism.highlightAll();
  });
});
</script>

<template>
  <div>
    <ifx-stepper
      active-step="2"
      aria-label=""
      aria-current=""
      :show-step-number="false"
      variant="default">
      <ifx-step>
        Step Label 1
      </ifx-step>
      <ifx-step>
        Step Label 2
      </ifx-step>
      <ifx-step>
        Step Label 3
      </ifx-step>
      <ifx-step>
        Step Label 4
      </ifx-step>
      <ifx-step>
        Step Label 5
      </ifx-step>
    </ifx-stepper>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
