// examples/react-example/src/generated/IfxStatusExample.tsx
import { useState } from 'react';
import { IfxButton, IfxStatus, IfxTextField } from '@infineon/infineon-design-system-react';

export function IfxStatusExample() {
  const [label, setLabel] = useState("text");
  const [border, setBorder] = useState(true);
  const colorOptions = ["engineering-100","engineering-200","engineering-300","engineering-400","engineering-500","engineering-600","ocean-100","ocean-200","ocean-300","ocean-400","ocean-500","ocean-600","ocean-700","red-500","red-600","red-700","orange-500","green-500","lawn-400","lawn-500","lawn-700","berry-400","berry-500","sun-400","sun-500","sand-400","sand-500"];
  const [colorIndex, setColorIndex] = useState(16);

  const handleLabelChange = (value: string) => setLabel(value);
  const handleBorderChange = () => setBorder((v) => !v);
  const handleColorChange = () => setColorIndex((i) => (i + 1) % colorOptions.length);

  const controlledProps = {
    "label": label,
    "border": border,
    "color": colorOptions[colorIndex],
  } as Record<string, unknown>;
  const getControlInputValue = (event: {
    detail?: unknown;
    target?: { value?: unknown } | null;
  }): string => {
    const detail = event.detail;

    if (typeof detail === "string" || typeof detail === "number") {
      return String(detail);
    }

    if (detail && typeof detail === "object" && "value" in detail) {
      return String((detail as { value?: unknown }).value ?? "");
    }

    return String(event.target?.value ?? "");
  };

  const formatPropValueForCode = (value: unknown): string => {
		if (typeof value === "boolean") return `{${value}}`;
		if (typeof value === "number") return `{${value}}`;
		if (value === null) return "{null}";
		if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
			return `{${JSON.stringify(value)}}`;
		}
		const escaped = String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
		return `"${escaped}"`;
	};

	const controlledPropsCode = [
    ["label", controlledProps["label"]],
    ["border", controlledProps["border"]],
    ["color", controlledProps["color"]],
	]
		.map(([name, value]) => `        ${String(name)}=${formatPropValueForCode(value)}`)
		.join("\n");

	const codeStringWithProps = `import { IfxStatus } from '@infineon/infineon-design-system-react';

export function IfxStatusExample() {
  return (
      <IfxStatus
        label={String(controlledProps.label ?? "text")}
        border={String(controlledProps.border ?? "true")}
        __CONTROLLED_PROPS__ />
  );
}`.replace("__CONTROLLED_PROPS__", controlledPropsCode);

	const codeString = codeStringWithProps;
	return (
    <>
      <IfxStatus
        label={String(controlledProps.label ?? "text")}
        border={String(controlledProps.border ?? "true")}
        {...(controlledProps as any)} />
	      <h3 className="controls-title">Controls</h3>
	      <div className="controls controls-toggle">
        <IfxButton variant="secondary" onClick={handleBorderChange}>Toggle Border</IfxButton>
        <IfxButton variant="secondary" onClick={handleColorChange}>Toggle Color</IfxButton>
	      </div>
	      <div className="controls controls-input">
        <IfxTextField label="label" type="text" value={String(label)} onIfxInput={(event) => handleLabelChange(getControlInputValue(event))} />
	      </div>

	      <div className="state">
	          <div><b>label:</b> {String(label)}</div>
          <div><b>border:</b> {String(border)}</div>
          <div><b>color:</b> {String(colorOptions[colorIndex])}</div>
	      </div>
	
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

// examples/vue-example/src/generated/IfxStatusExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxStatus, IfxTextField } from '@infineon/infineon-design-system-vue';

const label = ref("text");
const border = ref(true);
const colorOptions = ["engineering-100","engineering-200","engineering-300","engineering-400","engineering-500","engineering-600","ocean-100","ocean-200","ocean-300","ocean-400","ocean-500","ocean-600","ocean-700","red-500","red-600","red-700","orange-500","green-500","lawn-400","lawn-500","lawn-700","berry-400","berry-500","sun-400","sun-500","sand-400","sand-500"];
const colorIndex = ref(16);

const handleLabelChange = (nextValue: string) => { label.value = nextValue; };
const handleBorderChange = () => { border.value = !border.value; };
const handleColorChange = () => { colorIndex.value = (colorIndex.value + 1) % colorOptions.length; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "label": label.value,
  "border": border.value,
  "color": colorOptions[colorIndex.value],
}));

const getControlInputValue = (event: Event & {
  detail?: unknown;
  target?: { value?: unknown } | null;
}) => {
  const detail = event.detail;

  if (typeof detail === 'string' || typeof detail === 'number') {
    return String(detail);
  }

  if (detail && typeof detail === 'object' && 'value' in detail) {
    return String((detail as { value?: unknown }).value ?? '');
  }

  return String(event.target?.value ?? '');
};

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["label", label.value],
  ["border", border.value],
  ["color", colorOptions[colorIndex.value]],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxStatus } from '@infineon/infineon-design-system-vue';
${'</'}script>

<template>
  <div>
    <ifx-status
      :label="String(controlledProps.label ?? 'text')"
      :border="String(controlledProps.border ?? 'true')"
      __CONTROLLED_PROPS__ />
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-status
      :label="String(controlledProps.label ?? 'text')"
      :border="String(controlledProps.border ?? 'true')"
      v-bind="controlledProps" />
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="handleBorderChange">Toggle Border</ifx-button>
        <ifx-button variant="secondary" @click="handleColorChange">Toggle Color</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="label" type="text" :value="String(label)" @ifxInput="handleLabelChange(getControlInputValue($event))" />
    </div>

    <div class="state">
      <div><b>label:</b> {{ String(label) }}</div>
      <div><b>border:</b> {{ String(border) }}</div>
      <div><b>color:</b> {{ String(colorOptions[colorIndex]) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>
