// examples/wrapper-components/vue-javascript/src/components/Dropdown.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["m", "s"];
const sizeIndex = ref(0);
const size = computed(() => sizes[sizeIndex.value]);

const variants = ["primary", "secondary", "tertiary"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const placements = ["bottom-start", "auto", "auto-start", "auto-end", "top", "top-start", "top-end", "bottom", "bottom-end", "right", "right-start", "right-end", "left", "left-start", "left-end"];
const placementIndex = ref(0);
const placement = computed(() => placements[placementIndex.value]);

const disabled = ref(false);
const noCloseOnOutsideClick = ref(false);
const noCloseOnMenuClick = ref(false);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function togglePlacement() {
  placementIndex.value = (placementIndex.value + 1) % placements.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleNoCloseOnOutsideClick() {
  noCloseOnOutsideClick.value = !noCloseOnOutsideClick.value;
}

function toggleNoCloseOnMenuClick() {
  noCloseOnMenuClick.value = !noCloseOnMenuClick.value;
}

</script>

<template>
  <div class="component">
    <h2>Dropdown</h2>
    <div>
      <ifx-dropdown :placement="placement" :disabled="disabled" default-open="false"
        :noCloseOnOutsideClick="noCloseOnOutsideClick" :noCloseOnMenuClick="noCloseOnMenuClick"
        no-append-to-body="false">
        <ifx-dropdown-trigger-button :variant="variant">
          Dropdown
        </ifx-dropdown-trigger-button>

        <ifx-dropdown-menu :size="size">
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
        </ifx-dropdown-menu>
      </ifx-dropdown>
    </div>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size of Dropdown Items</ifx-button>
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="togglePlacement">Toggle Placement</ifx-button>
      <ifx-button variant="secondary" @click="toggleNoCloseOnOutsideClick">Toggle No Close on Outside Click</ifx-button>
      <ifx-button variant="secondary" @click="toggleNoCloseOnMenuClick">Toggle No Close on Menu Click</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Disabled:</b> {{ disabled }} </div>
      <div><b>Variant:</b> {{ variant }} </div>
      <div><b>Size of dropdown items:</b> {{ size }} </div>
      <div><b>Placement:</b> {{ placement }} </div>
      <div><b>No Close on Outside Click:</b> {{ noCloseOnOutsideClick }} </div>
      <div><b>No Close on Menu Click:</b> {{ noCloseOnMenuClick }} </div>
    </div>
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/dropdown/dropdown.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-dropdown',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './dropdown.component.html',
  styleUrl: './dropdown.component.scss'
})
export class DropdownComponent {
  disabled = false;
  dropdownNoCloseOnOutsideClick = false;
  dropdownNoCloseOnMenuClick = false;

  dropdownSize = "m";
  dropdownSizes = ["m", "s"];
  dropdownSizeIndex = 0;

  variant = "primary";
  variants = ["primary", "secondary", "tertiary"];
  variantIndex = 0;

  placement = "bottom-start";
  placements = ["bottom-start", "auto", "auto-start", "auto-end", "top", "top-start", "top-end", "bottom", "bottom-end", "right", "right-start", "right-end", "left", "left-start", "left-end"];
  placementIndex = 0;

  toggleSize() {
    this.dropdownSizeIndex = (this.dropdownSizeIndex + 1) % this.dropdownSizes.length;
    this.dropdownSize = this.dropdownSizes[this.dropdownSizeIndex];
  }

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }

  togglePlacement() {
    this.placementIndex = (this.placementIndex + 1) % this.placements.length;
    this.placement = this.placements[this.placementIndex];
  }

  toggleDisabled() {
    this.disabled = !this.disabled;
  }

  toggleNoCloseOnOutsideClick() {
    this.dropdownNoCloseOnOutsideClick = !this.dropdownNoCloseOnOutsideClick;
  }

  toggleNoCloseOnMenuClick() {
    this.dropdownNoCloseOnMenuClick = !this.dropdownNoCloseOnMenuClick;
  }

}

<h2>Dropdown</h2>
<div><ifx-dropdown [placement]="dropdownPlacement" [disabled]="dropdownDisabled" default-open="false"
    [noCloseOnOutsideClick]="dropdownNoCloseOnOutsideClick" [noCloseOnMenuClick]="dropdownNoCloseOnMenuClick"
    no-append-to-body="false">
    <ifx-dropdown-trigger-button [variant]="dropdownVariant">
      Dropdown
    </ifx-dropdown-trigger-button>

    <ifx-dropdown-menu [size]="dropdownSize">
      <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
      <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
      <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
      <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
      <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
    </ifx-dropdown-menu>
  </ifx-dropdown></div>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleDropdownDisabled()">Toggle Disabled</ifx-button>
<ifx-button variant="secondary" (click)="toggleDropdownSize()">Toggle Size of Dropdown Items</ifx-button>
<ifx-button variant="secondary" (click)="toggleDropdownVariant()">Toggle Variant</ifx-button>
<ifx-button variant="secondary" (click)="toggleDropdownPlacement()">Toggle Placement</ifx-button>
<ifx-button variant="secondary" (click)="toggleDropdownNoCloseOnOutsideClick()">Toggle No Close on Outside
  Click</ifx-button>
<ifx-button variant="secondary" (click)="toggleDropdownNoCloseOnMenuClick()">Toggle No Close on Menu Click</ifx-button>
<br>
<br>
<span><b>Disabled:</b> {{ dropdownDisabled }} </span><br>
<span><b>Variant:</b> {{ dropdownVariant }} </span><br>
<span><b>Size of dropdown items:</b> {{ dropdownSize }} </span><br>
<span><b>Placement:</b> {{ dropdownPlacement }} </span><br>
<span><b>No Close on Outside Click:</b> {{ dropdownNoCloseOnOutsideClick }} </span><br>
<span><b>No Close on Menu Click:</b> {{ dropdownNoCloseOnMenuClick }} </span><br>
