// examples/wrapper-components/vue-javascript/src/components/Tooltip.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["compact", "dismissible", "extended"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const positions = ["auto", "bottom-start", "top-start", "left", "bottom-end", "top-end", "right", "bottom", "top"];
const positionIndex = ref(0);
const position = computed(() => positions[positionIndex.value]);

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function togglePosition() {
  positionIndex.value = (positionIndex.value + 1) % positions.length;
}

</script>

<template>
  <div class="component">
    <h2>Tooltip</h2>
    <ifx-tooltip text="Hi, I'm a tooltip" :variant="variant" :position="position" icon="arrowLeft16"
      aria-label="Tooltip with important information">
      I'm the tooltip reference element - Please hover me
    </ifx-tooltip>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="togglePosition">Toggle Position</ifx-button>
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Position:</b> {{ position }} </div>
      <div><b>Variant:</b> {{ variant }} </div>
    </div>
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/tooltip/tooltip.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';


@Component({
  selector: 'app-tooltip',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './tooltip.component.html',
  styleUrl: './tooltip.component.scss'
})
export class TooltipComponent {
  position = "auto";
  positions = ["auto", "bottom-start", "top-start", "left", "bottom-end", "top-end", "right", "bottom", "top"];
  positionIndex = 0;

  variant = "compact";
  variants = ["compact", "dismissible", "extended"];
  variantIndex = 0;

  togglePosition() {
    this.positionIndex = (this.positionIndex + 1) % this.positions.length;
    this.position = this.positions[this.positionIndex];
  }

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }
}

<h2>Tooltip</h2>
<ifx-tooltip 
text="Hi, I'm a tooltip" 
[variant]="variant" 
[position]="position" 
icon="arrowLeft16" 
aria-label="Tooltip with important information">
I'm the tooltip reference element - Please hover me
</ifx-tooltip>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="togglePosition()">Toggle Position</ifx-button>
<ifx-button variant="secondary" (click)="toggleVariant()">Toggle Variant</ifx-button>
<br>
<br>
<span><b>Position:</b> {{ position }} </span><br>
<span><b>Variant:</b> {{ variant}} </span><br>
