// examples/wrapper-components/vue-javascript/src/components/SegmentedControls.vue
<template>
    <div>
      <h2>Segmented Controls</h2>
      <ifx-segmented-control-group caption='Caption text to describe the controls' group-label='Group Label' size='regular'>
        <ifx-segmented-control selected='true' icon='star-16' value='value1'> Label </ifx-segmented-control>
        <ifx-segmented-control icon='star-16' value='value2'> Label </ifx-segmented-control>
        <ifx-segmented-control icon='star-16' value='value3'> Label </ifx-segmented-control>
        <ifx-segmented-control icon='star-16' value='value4'> Label </ifx-segmented-control>
      </ifx-segmented-control-group>
      <br />
      <br />
    </div>
</template>
  
  <style scoped></style>

// examples/wrapper-components/react-vite-js/src/components/SegmentedControls/SegmentedControls.jsx
import { IfxSegmentedControlGroup, IfxSegmentedControl } from '@infineon/infineon-design-system-react';
import React from 'react';

function SegmentedControls() {
    return (
        <div>
            <IfxSegmentedControlGroup caption='Caption text to describe the controls' groupLabel='Group Label' size='regular'>
                <IfxSegmentedControl selected={true} icon='star16' value='value1'> Label </IfxSegmentedControl>
                <IfxSegmentedControl icon='star16' value='value2'> Label </IfxSegmentedControl>
                <IfxSegmentedControl icon='star16' value='value3'> Label </IfxSegmentedControl>
                <IfxSegmentedControl icon='star16' value='value4'> Label </IfxSegmentedControl>
            </IfxSegmentedControlGroup>
        </div>
    )
}

export default SegmentedControls;
