// examples/wrapper-components/vue-javascript/src/components/Status.vue
<script setup lang="ts">
import { ref } from "vue";

const border = ref(true);
const color = ref<string>("ocean-500");

function toggleBorder() {
  border.value = !border.value;
}

function setColor(newColor: string) {
  color.value = newColor;
}

</script>

<template>
  <div class="component">
    <h2>Status</h2>
    <ifx-status label="text" :color="color" :border="border" />
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleBorder">Toggle Border</ifx-button>
      <ifx-dropdown placement="bottom-start">
        <ifx-dropdown-trigger-button variant="secondary">
          Change Color
        </ifx-dropdown-trigger-button>
        <ifx-dropdown-menu size="s">
          <ifx-dropdown-item target="_self" @click="setColor('green-500')">Green-500</ifx-dropdown-item>
          <ifx-dropdown-item target="_self" @click="setColor('orange-500')">Orange-500</ifx-dropdown-item>
          <ifx-dropdown-item target="_self" @click="setColor('ocean-500')">Ocean-500</ifx-dropdown-item>
          <ifx-dropdown-item target="_self" @click="setColor('red-500')">Red-500</ifx-dropdown-item>
          <ifx-dropdown-item target="_self" @click="setColor('lawn-500')">Lawn-500</ifx-dropdown-item>
          <ifx-dropdown-item target="_self" @click="setColor('berry-500')">Berry-500</ifx-dropdown-item>
        </ifx-dropdown-menu>
      </ifx-dropdown>
    </div>
    <br>

    <div class="state">
      <div><b>Border:</b> {{ border }} </div>
    </div>
  </div>
</template>

// packages/components-angular/projects/my-app/src/app/components/status/status.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-status',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './status.component.html',
  styleUrl: './status.component.scss'
})
export class StatusComponent {

}

<h2>Status</h2>
<ifx-status label="text" [color]="color" [border]="border" />
<br>
<br>

<h3 class="controls-title">Controls</h3>
<div class="controls">
  <ifx-button variant="secondary" (click)="toggleBorder()">Toggle Border</ifx-button>
  <ifx-dropdown placement="bottom-start">
    <ifx-dropdown-trigger-button variant="secondary">
      Change Color
    </ifx-dropdown-trigger-button>
    <ifx-dropdown-menu size="s">
      <ifx-dropdown-item target="_self" (click)="setColor('green-500')">Green-500</ifx-dropdown-item>
      <ifx-dropdown-item target="_self" (click)="setColor('orange-500')">Orange-500</ifx-dropdown-item>
      <ifx-dropdown-item target="_self" (click)="setColor('ocean-500')">Ocean-500</ifx-dropdown-item>
      <ifx-dropdown-item target="_self" (click)="setColor('red-500')">Red-500</ifx-dropdown-item>
      <ifx-dropdown-item target="_self" (click)="setColor('lawn-500')">Lawn-500</ifx-dropdown-item>
      <ifx-dropdown-item target="_self" (click)="setColor('berry-500')">Berry-500</ifx-dropdown-item>
    </ifx-dropdown-menu>
  </ifx-dropdown>
</div>
<br>

<div class="state">
  <div><b>Border:</b> {{ border }} </div>
</div>
