// examples/wrapper-components/vue-javascript/src/components/MultiSelect.vue


<template>
  <div>
    <h2>MultiSelect</h2>
    <ifx-multiselect :options="options" @ifxSelect="handleMultiSelectChange" size="medium (40px)" :error="error"
      :erroMessage="errorMessage" error-message="Some error" label="" :disabled="disabled"></ifx-multiselect>
    <div>
      <ifx-button variant="outline" color="primary" @click="toggleDisabled">Toggle Disabled</ifx-button>

      <ifx-button variant="outline" color="primary" @click="toggleError">Toggle Error</ifx-button>
    </div>
    <br />
    <br />
  </div>
</template>



<script setup>
import { ref } from 'vue';

let disabled = ref(false);
let error = ref(false);
let errorMessage = ref("Some error");

let options = ref([{
  value: "a",
  label: "option a",
  selected: false
},
{
  value: "b",
  label: "option b",
  selected: false
},
{
  value: "c",
  label: "option c",
  selected: false,
  children: [
    {
      value: "c1",
      label: "option c1",
      selected: false
    },
    {
      value: "c2",
      label: "option c2",
      selected: false
    }
  ]
}]);


function handleMultiSelectChange(event) {
  console.log("emitting multiselect selected options: ", event.detail)
};



const toggleDisabled = () => {
  disabled.value = !disabled.value;
};

const toggleError = () => {
  error.value = !error.value;
};

</script>

// examples/wrapper-components/react-javascript/src/components/MultiSelect/MultiSelect.js
import React, { useState } from 'react';
import { IfxMultiselect, IfxButton } from '@infineon/infineon-design-system-react';


function App() {
  const [disabled, setDisabled] = useState(false);
  const [error, setError] = useState(false);
  const [options] = useState([{
    value: "a",
    label: "option a",
    selected: false
  },
  {
    value: "b",
    label: "option b",
    selected: false
  },
  {
    value: "c",
    label: "option c",
    selected: false,
    children: [
      {
        value: "c1",
        label: "option c1",
        selected: false
      },
      {
        value: "c2",
        label: "option c2",
        selected: false
      }
    ]
  }]);


  const handleIfxSelect = (e) => {
    console.log('ifxSelect event emitted with value:', e.detail);
  }


  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  const toggleError = () => {
    setError(prevError => !prevError);
  }


  return (
    <div>
      <IfxMultiselect options={options}
        size="medium (40px)" onIfxSelect={handleIfxSelect} disabled={disabled} error={error} error-message="Some error" label="" ></IfxMultiselect>
      <div>
        <IfxButton variant="outline" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
        <IfxButton variant="outline" onClick={toggleError}>Toggle Error</IfxButton>
      </div>
      <br />
    </div>
  );
}

export default App;
