// examples/stencil-components/vue3-vite/src/App.vue
<script setup>
import Button from './components/Button.vue'
import Checkbox from './components/Checkbox.vue'
import ProgressBar from './components/ProgressBar.vue'

</script>

<template>
  <h1 class="header">Using Stencil web components in a Vue application</h1>
  <Button />
  <Checkbox />
  <ProgressBar />
</template>

<style scoped>
.header {
  text-align: center;
}
</style>

// examples/react/src/App.js
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>
          Using Stencil web components in a React application
        </p>

        <ifx-button variant="solid" icon="" position="left" href="" target="_blank" color="primary" size="m" disabled="false">
          Button
        </ifx-button>
      </header>
    </div>
  );
}

export default App;
