// examples/wrapper-components/react-javascript/src/components/SearchField/SearchField.js
import React from 'react';
import { IfxSearchField } from '@infineon/infineon-design-system-react';

function SearchField() {
  const handleSearch = (event) => {
    console.log("handling input: ", event.detail)
  };

  return (
    <div  >
      <IfxSearchField disabled="false" size='m' show-delete-icon="true" onIfxInput={handleSearch}></IfxSearchField>
    </div>
  )
}

export default SearchField;

// packages/components-angular/projects/my-app/src/app/components/search-field/search-field.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-search-field',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './search-field.component.html',
  styleUrl: './search-field.component.scss'
})
export class SearchFieldComponent {
  searchFieldValue = '';

  handleSearchField(event: any) {
    console.log("searchField value change: ", event.detail)
    this.searchFieldValue = event.detail;
  }
}

<h2>Search Field</h2>
  <ifx-search-field size="m" disabled="false" show-delete-icon="true"
    (ifxInput)="handleSearchField($event)"></ifx-search-field>
