// examples/wrapper-components/vue-javascript/src/components/Modal.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const variants = ["default", "alert-brand", "alert-danger"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const sizes = ["s", "m", "l"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const closeButton = ref(true);
const modalRef = ref<HTMLElement | null>(null);
  function openModal() {
  if (modalRef.value) {
    (modalRef.value as any).opened = true;
  }
}

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleCloseButton() {
  closeButton.value = !closeButton.value;
}

</script>

<template>
  <div class="component">
    <h2>Modal</h2>
    <div>
      <ifx-modal ref="modalRef" caption="Modal Title" caption-aria-label="Additional information for caption"
        close-button-aria-label="Close modal" :variant="variant" close-on-overlay-click="false"
        :showCloseButton="closeButton" :size="size">
        <div slot="content">
          <div>Modal content</div>
        </div>
        <div slot="buttons">
          <ifx-button variant="secondary">Cancel</ifx-button>
          <ifx-button>OK</ifx-button>
        </div>
      </ifx-modal>
      <ifx-button id="open" @click="openModal">Open Modal</ifx-button>
    </div>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleCloseButton">Toggle Close Button</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Variant:</b> {{ variant }} </div>
      <div><b>Size:</b> {{ size }}</div>
      <div><b>Close Button:</b> {{ closeButton }}</div>
    </div>
  </div>
</template>

// examples/wrapper-components/react-vite-js/src/components/Modal/Modal.jsx
import { useRef, useState } from "react";
import { IfxModal, IfxButton } from "@infineon/infineon-design-system-react";

function Modal() {
  const modalRef = useRef(null);
  const [closeButton, setCloseButton] = useState(true);

  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ["default", "alert-brand", "alert-danger"];

  const [sizeIndex, setSizeIndex] = useState(0);
  const sizes = ["s", "m", "l"];

  const openModal = () => {
    modalRef.current.opened = true;
  };

  const toggleVariant = () => {
    const next = (variantIndex + 1) % variants.length;
    setVariantIndex(next);
    modalRef.current.variant = variants[next];
  };

  const toggleSize = () => {
    const next = (sizeIndex + 1) % sizes.length;
    setSizeIndex(next);
    modalRef.current.size = sizes[next];
  };

  const toggleCloseButton = () => {
    const next = !closeButton;
    setCloseButton(next);
    modalRef.current.showCloseButton = next;
  };

  return (
    <div className="component">
      <h2>Modal</h2>
      <IfxModal
        ref={modalRef}
        caption="Modal Title"
        caption-aria-label="Additional information for caption"
        close-button-aria-label="Close modal"
        close-on-overlay-click={false}
      >
        <div slot="content">
          <div>Modal content</div>
        </div>
        <div slot="buttons">
          <IfxButton
            variant="secondary"
            onClick={() => console.log("modal button 1 click")}
          >
            Cancel
          </IfxButton>
          <IfxButton
            onClick={() => console.log("modal button 2 click")}
          >
            OK
          </IfxButton>
        </div>
      </IfxModal>
      <IfxButton onClick={openModal}>Open Modal</IfxButton>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={toggleCloseButton}>Toggle Close Button</IfxButton>
      </div>
      <br />

      <div class="state">
        <b>Variant:</b> {variants[variantIndex]} <br />
        <b>Size:</b> {sizes[sizeIndex]} <br />
        <b>Close Button:</b> {String(closeButton)}
      </div >
    </div >
  );
}

export default Modal;
