// packages/components-angular/projects/my-app/src/app/components/modal/modal.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './modal.component.html',
  styleUrl: './modal.component.scss'
})
export class ModalComponent {
  handleModalButton1Click() {
    console.log("modal button 1 click ")
  }

  handleModalButton2Click() {
    console.log("modal button 2 click ")
  }

  handleModalOpen() {
    const modal = document.querySelector('ifx-modal') as HTMLIfxModalElement;
    console.log("modal open btn click ")
    modal.opened = true;
  }

  variant = "default";
  variants = ["default", "alert-brand", "alert-danger"];
  variantIndex = 0;

  size = "s";
  sizes = ["s", "m", "l"];
  sizeIndex = 0;

  closeButton = true;

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }

  toggleCloseButton() {
    this.closeButton = !this.closeButton;
  }
}

<h2>Modal</h2>
<div>
  <ifx-modal caption="Modal Title" caption-aria-label="Additional information for caption" close-button-aria-label="Close modal" [variant]="variant" close-on-overlay-click="false" [showCloseButton]="closeButton" [size]="size">
    <div slot="content">
    <span>Modal content</span>
    </div>
    <div slot="buttons">
      <ifx-button variant="secondary" (click)="handleModalButton1Click()">Cancel</ifx-button>
      <ifx-button (click)="handleModalButton2Click()">OK</ifx-button>
    </div>
  </ifx-modal>
  <ifx-button id="open" (click)="handleModalOpen()">Open Modal</ifx-button>
</div>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleVariant()">Toggle Variant</ifx-button>
<ifx-button variant="secondary" (click)="toggleSize()">Toggle Size</ifx-button>
<ifx-button variant="secondary" (click)="toggleCloseButton()">Toggle Close Button</ifx-button>
<br>
<br>
<span><b>Variant:</b> {{ variant }} </span><br>
<span><b>Size:</b> {{ size }}</span><br>
<span><b>Close Button:</b> {{ closeButton }}</span><br>

// examples/wrapper-components/react-vite-js/src/components/Modal/Modal.jsx
import { useRef, useState } from "react";
import { IfxModal, IfxButton } from "@infineon/infineon-design-system-react";

function Modal() {
  const modalRef = useRef(null);
  const [closeButton, setCloseButton] = useState(true);

  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ["default", "alert-brand", "alert-danger"];

  const [sizeIndex, setSizeIndex] = useState(0);
  const sizes = ["s", "m", "l"];

  const openModal = () => {
    modalRef.current.opened = true;
  };

  const toggleVariant = () => {
    const next = (variantIndex + 1) % variants.length;
    setVariantIndex(next);
    modalRef.current.variant = variants[next];
  };

  const toggleSize = () => {
    const next = (sizeIndex + 1) % sizes.length;
    setSizeIndex(next);
    modalRef.current.size = sizes[next];
  };

  const toggleCloseButton = () => {
    const next = !closeButton;
    setCloseButton(next);
    modalRef.current.showCloseButton = next;
  };

  return (
    <div className="component">
      <h2>Modal</h2>
      <IfxModal
        ref={modalRef}
        caption="Modal Title"
        caption-aria-label="Additional information for caption"
        close-button-aria-label="Close modal"
        close-on-overlay-click={false}
      >
        <div slot="content">
          <span>Modal content</span>
        </div>
        <div slot="buttons">
          <IfxButton
            variant="secondary"
            onClick={() => console.log("modal button 1 click")}
          >
            Cancel
          </IfxButton>
          <IfxButton
            onClick={() => console.log("modal button 2 click")}
          >
            OK
          </IfxButton>
        </div>
      </IfxModal>
      <IfxButton onClick={openModal}>Open Modal</IfxButton>
      <br />
      <br />
      <h3 style={{ textDecoration: "underline" }}>Controls</h3>
      <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
      <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
      <IfxButton variant="secondary" onClick={toggleCloseButton}>Toggle Close Button</IfxButton>
      <br />
      <br />
      <b>Variant:</b> {variants[variantIndex]} <br />
      <b>Size:</b> {sizes[sizeIndex]} <br />
      <b>Close Button:</b> {String(closeButton)}
    </div>
  );
}

export default Modal;
