// packages/components-angular/projects/my-app/src/app/components/accordion/accordion.component.ts
import { Component, ViewChild } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';
import { IfxAccordionItem } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-accordion',
  standalone: true,
  imports: [
    ComponentLibraryModule,
  ],
  templateUrl: './accordion.component.html',
  styleUrl: './accordion.component.scss'
})
export class AccordionComponent {
  @ViewChild('ifxAccordionItem') ifxAccordionItemRef: IfxAccordionItem | undefined;

  handleAccordionItemOpen(event: any) {
    console.log("An accordion item was opened. Event details:", event);
  };

  handleAccordionItemClose(event: any) {
    console.log("An accordion item was closed. Event details:", event);
  };

  handleAccordionButtonClick() {
    console.log("accordion item open btn click ")
    const accordionItem = document.querySelector('ifx-accordion-item') as HTMLIfxAccordionItemElement;

    if (this.ifxAccordionItemRef) {
      console.log("accordion item: ", accordionItem);
      this.ifxAccordionItemRef.open = !this.ifxAccordionItemRef.open;
    }
  }
}

<h2>Accordion</h2>
  <ifx-accordion (ifxClose)="handleAccordionItemClose($event)" (ifxOpen)="handleAccordionItemOpen($event)"
    auto-collapse="true">
    <ifx-accordion-item open="true" caption="Label" #ifxAccordionItem>
      Content for Item #1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam
      bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
      cursus ipsum, nec egestas odio sapien eget neque.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
      cursus ipsum, nec egestas odio sapien eget neque.

    </ifx-accordion-item><ifx-accordion-item open="false" caption="Label">

      Content for Item #2. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam
      bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
      cursus ipsum, nec egestas odio sapien eget neque.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
      cursus ipsum, nec egestas odio sapien eget neque.

    </ifx-accordion-item><ifx-accordion-item open="false" caption="Label">

      Content for Item #3. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam
      bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
      cursus ipsum, nec egestas odio sapien eget neque.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
      cursus ipsum, nec egestas odio sapien eget neque.

    </ifx-accordion-item></ifx-accordion>
  <ifx-button (click)="handleAccordionButtonClick()">Open/Close the first accordion item</ifx-button>

// examples/wrapper-components/react-javascript/src/components/Accordion/Accordion.js
import React, { useRef } from 'react';
import { IfxAccordion, IfxButton } from '@infineon/infineon-design-system-react';
import { IfxAccordionItem } from '@infineon/infineon-design-system-react';

function Accordion() {
  const handleItems = (event) => {
    console.log("An accordion item was opened. Event details:", event);
  };

  const accordionItemRef = useRef();

  async function handleButtonClick() {
    // Get a reference to the ifx-accordion-item component instance
    const accordionItem = accordionItemRef.current;
    accordionItem.open = !accordionItem.open;
    console.log("accordion item: ", accordionItem)
  }



  return (
    <div>
      <IfxAccordion auto-collapse={true} onIfxItemOpen={handleItems}>
        <IfxAccordionItem initial-collapse={false} open={false} caption="Label" ref={accordionItemRef}>
          Content for Item #1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxAccordionItem>
        <IfxAccordionItem open={false} caption="Label">
          Content for Item #2. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxAccordionItem>
        <IfxAccordionItem open={false} caption="Label">
          Content for Item #3. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxAccordionItem>
      </IfxAccordion>
      <br />
      <IfxButton onClick={handleButtonClick}>Open/Close the first accordion item</IfxButton>


    </div>
  )
}




export default Accordion;
