// examples/wrapper-components/vue-javascript/src/components/Accordion.vue
<template>
  <div class="component">
    <h2>Accordion</h2>
    <ifx-accordion @ifxOpen="handleItems" auto-collapse="true">
      <ifx-accordion-item
        ref="accordionItemRef"
        initial-collapse="false"
        open="false"
        caption="Label"
      >
        <div>{{ content }}</div> </ifx-accordion-item
      ><ifx-accordion-item caption="Label">
        Content for Item #2. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas
        odio sapien eget neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas
        odio sapien eget neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas
        odio sapien eget neque. </ifx-accordion-item
      ><ifx-accordion-item caption="Label">
        Content for Item #3. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas
        odio sapien eget neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas
        odio sapien eget neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas
        odio sapien eget neque.
      </ifx-accordion-item></ifx-accordion
    >
    <br />
    <ifx-button @click="handleButtonClick"
      >Open/Close the first accordion item</ifx-button
    >
    <ifx-button @click="updateContent">Change Content dynamically</ifx-button>
    <br />
    <br />
  </div>
</template>

<script setup>
import { ref } from "vue";
const accordionItemRef = ref();
const content = ref("Short content");

function handleItems(event) {
  console.log("An accordion item was opened. Event details:", event);
}

async function handleButtonClick() {
  const accordionItem = accordionItemRef.value;
  accordionItem.open = !accordionItem.open;
  console.log("accordion item: ", accordionItem);
}

async function updateContent() {
  content.value = `   Content for Item #3. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam
        bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
        cursus ipsum, nec egestas odio sapien eget neque.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl
        cursus ipsum, nec egestas odio sapien eget neque.`;
}
</script>

// examples/wrapper-components/react-javascript/src/components/Accordion/Accordion.js
import React, { useRef, useState } from 'react';
import { IfxAccordion, IfxAccordionItem, IfxButton } from '@infineon/infineon-design-system-react';

function Accordion() {

  const [content, setContent] = useState('Short content')


  const handleItems = (event) => {
    console.log("An accordion item was opened. Event details:", event);
  };

  const accordionItemRef = useRef();

  async function handleButtonClick() {
    const accordionItem = accordionItemRef.current;
    accordionItem.open = !accordionItem.open;
    console.log("accordion item: ", accordionItem)
  }

  const updateContent = () => {
    setContent(`Content for Item #2. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.`)
  }

  return (
    <div>
      <IfxAccordion auto-collapse={true} onIfxOpen={handleItems}>
        <IfxAccordionItem initial-collapse={false} open={false} key={content} caption="Label" ref={accordionItemRef}>
          <div>{content}</div>
        </IfxAccordionItem>
        <IfxAccordionItem open={false} caption="Label">
          Content for Item #2. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxAccordionItem>
        <IfxAccordionItem open={false} caption="Label">
          Content for Item #3. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent volutpat, ligula eu aliquam bibendum, orci nisl cursus ipsum, nec egestas odio sapien eget neque.
        </IfxAccordionItem>
      </IfxAccordion>
      <br />
      <IfxButton onClick={handleButtonClick}>Open/Close the first accordion item</IfxButton>
      <IfxButton onClick={updateContent}>Change Content dynamically</IfxButton>


    </div>
  )
}




export default Accordion;
