// examples/react-example/src/generated/IfxCheckboxExample.tsx
import { IfxCheckbox } from '@infineon/infineon-design-system-react';

export function IfxCheckboxExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  const handleError = (event: CustomEvent) => {
    console.log('ifxError:', event);
    // Add your handler logic here
  };

  return (
    <>
      <IfxCheckbox
        disabled={false}
        readOnly={false}
        checked={false}
        size="s"
        indeterminate={false}
        name="checkbox"
        error={false}
        onIfxChange={handleChange}
        onIfxError={handleError}>
        Text
      </IfxCheckbox>
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { IfxCheckbox } from '@infineon/infineon-design-system-react';

export function IfxCheckboxExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  const handleError = (event: CustomEvent) => {
    console.log('ifxError:', event);
    // Add your handler logic here
  };

  return (
      <IfxCheckbox
        disabled={false}
        readOnly={false}
        checked={false}
        size="s"
        indeterminate={false}
        name="checkbox"
        error={false}
        onIfxChange={handleChange}
        onIfxError={handleError}>
        Text
      </IfxCheckbox>
  );
}`;

// examples/angular-module-example/src/app/generated/ifx-checkbox-example/ifx-checkbox-example.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-checkbox-example',
  templateUrl: './ifx-checkbox-example.html',
  styleUrl: './ifx-checkbox-example.scss',
  standalone: false
})
export class IfxCheckboxExample {
  protected readonly tsCode = `import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-checkbox-example&#039;,
  templateUrl: &#039;./ifx-checkbox-example.html&#039;,
  styleUrl: &#039;./ifx-checkbox-example.scss&#039;,
  standalone: false
})
export class IfxCheckboxExample {
  protected handleChange(event: CustomEvent) {
    console.log(&#039;ifxChange:&#039;, event);
    // Add your handler logic here
  }

  protected handleError(event: CustomEvent) {
    console.log(&#039;ifxError:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-checkbox
    error=&quot;false&quot;
    disabled=&quot;false&quot;
    checked=&quot;false&quot;
    size=&quot;s&quot;
    indeterminate=&quot;false&quot;
    name=&quot;checkbox&quot;
    (ifxChange)=&quot;handleChange(\$any(\$event))&quot;
    (ifxError)=&quot;handleError(\$any(\$event))&quot;&gt;Text&lt;/ifx-checkbox&gt;`;

  protected handleChange(event: CustomEvent) {
    console.log('ifxChange:', event);
    // Add your handler logic here
  }

  protected handleError(event: CustomEvent) {
    console.log('ifxError:', event);
    // Add your handler logic here
  }
}
