// examples/wrapper-components/vue-typescript/src/components/SearchField.vue
<template>
  <div>
    <h2>Search Field</h2>

    <ifx-search-field v-model="searchInput" disabled="false" size='m' show-delete-icon="true"></ifx-search-field>
    <br />
    <br />
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'
const searchInput = ref('');

onMounted(() => {
  updateSearchBarAndSearchInput();
  setInterval(updateSearchBarAndSearchInput, 10000);
})


function updateSearchBarAndSearchInput() {
  console.log("updating search field")
  searchInput.value = searchInput.value + "+1";
}
</script>

<style scoped></style>

// examples/wrapper-components/react-vite-js/src/components/SearchField/SearchField.jsx
import { IfxSearchField } from '@infineon/infineon-design-system-react';

function SearchField() {
  const handleSearch = (event) => {
    console.log("handling input: ", event.detail)
  };

  return (
    <div  >
      <h2>Search Field</h2>
      <IfxSearchField disabled="false" size='m' show-delete-icon="true" onIfxInput={handleSearch}></IfxSearchField>
    </div>
  )
}

export default SearchField;
