// examples/wrapper-components/react-vite-js/src/components/SearchBar/SearchBar.jsx
import { useState } from 'react';
import { IfxSearchBar, IfxButton } from '@infineon/infineon-design-system-react';

function SearchBar() {
  const [searchBarOpen, setSearchBarOpen] = useState(true);
  const [searchBarDisabled, setSearchBarDisabled] = useState(false);

  const toggleSearchBarOpen = () => {
    setSearchBarOpen((prev) => !prev);
  };

  const toggleSearchBarDisabled = () => {
    setSearchBarDisabled((prev) => !prev);
  };

  const handleSearch = (event) => {
    console.log('handling search:', event.detail);
  };

  return (
    <div>
      <h2>Search Bar</h2>

      <IfxSearchBar
        isOpen={searchBarOpen}
        disabled={searchBarDisabled}
        autocomplete="on"
        onIfxInput={handleSearch}
      ></IfxSearchBar>

      <br />
      <br />
      <h3 style={{ textDecoration: 'underline' }}>Controls</h3>
      <IfxButton variant="secondary" onClick={toggleSearchBarDisabled}>Toggle Disabled</IfxButton>
      <IfxButton variant="secondary" onClick={toggleSearchBarOpen}>Toggle Open</IfxButton>
      <br />
      <br />
      <span><b>Disabled:</b> {String(searchBarDisabled)}</span><br />
      <span><b>Open:</b> {String(searchBarOpen)}</span><br />
    </div>
  );
}

export default SearchBar;

// packages/components-angular/projects/my-app/src/app/components/search-bar/search-bar.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-search-bar',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './search-bar.component.html',
  styleUrl: './search-bar.component.scss'
})
export class SearchBarComponent {
  searchBarValue = '';

  handleSearchBar(event: any) {
    console.log("searchBar value change: ", event.detail)
    this.searchBarValue = event.detail;
  }
}

<h2>Search Bar</h2>
<ifx-search-bar [isOpen]="searchBarOpen" [disabled]="searchBarDisabled" value="" autocomplete="on"></ifx-search-bar>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleSerchBarDisabled()">Toggle Disabled</ifx-button>
<ifx-button variant="secondary" (click)="toggleSearchBarOpen()">Toggle Open</ifx-button>
<br>
<br>
<span><b>Disabled:</b> {{ searchBarDisabled }} </span><br>
<span><b>Open:</b> {{ searchBarOpen }} </span><br>
