// examples/wrapper-components/vue-javascript/src/components/ProgressBar.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["s", "m"];
const sizeIndex = ref(1);
const size = computed(() => sizes[sizeIndex.value]);

const showLabel = ref(true);
const progressValue = ref(10);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleShowLabel() {
  showLabel.value = !showLabel.value;
}

function updateProgressOnClick() {
  if (progressValue.value < 100) {
    progressValue.value += 10;
  } else {
    progressValue.value = 10;
  }
}

</script>

<template>
  <div class="component">
    <h2>Progress Bar</h2>
    <ifx-progress-bar :value="progressValue" :size="size" :showLabel="showLabel"></ifx-progress-bar>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="updateProgressOnClick">Update progress</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size</ifx-button>
      <ifx-button variant="secondary" @click="toggleShowLabel">Toggle Label</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Size:</b> {{ size }} </div>
      <div><b>ShowLabel:</b> {{ showLabel }}</div>
    </div>
  </div>
</template>

// examples/wrapper-components/react-vite-js/src/components/ProgressBar/ProgressBar.jsx
import { useState } from 'react';
import { IfxProgressBar, IfxButton } from '@infineon/infineon-design-system-react';

function ProgressBar() {
  const [progressValue, setProgressValue] = useState(10);

  const [sizeIndex, setSizeIndex] = useState(1);
  const sizes = ['s', 'm'];

  const [showLabel, setShowLabel] = useState(true);

  const updateProgressOnClick = () => {
    setProgressValue((currentValue) => {
      if (currentValue < 100) {
        return currentValue + 10;
      } else {
        return 10;
      }
    });
  };

  const toggleSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  };

  const toggleShowLabel = () => {
    setShowLabel((prev) => !prev);
  };

  return (
    <div className="component">
      <h2>Progress Bar</h2>

      <IfxProgressBar value={progressValue} size={sizes[sizeIndex]} showLabel={showLabel}></IfxProgressBar>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={updateProgressOnClick}>Update progress</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={toggleShowLabel}>Toggle Label</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Size:</b> {sizes[sizeIndex]}</div>
        <div><b>ShowLabel:</b> {String(showLabel)}</div>
      </div>
    </div>
  );
}

export default ProgressBar;
