// packages/components-angular/projects/my-app/src/app/components/card/card.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-card',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './card.component.html',
  styleUrl: './card.component.scss'
})
export class CardComponent {
  direction = "horizontal";
  directions = ["horizontal", "vertical"];
  directionIndex = 0;

  toggleDirection() {
    this.directionIndex = (this.directionIndex + 1) % this.directions.length;
    this.direction = this.directions[this.directionIndex];
  }

}

<h2>Card</h2>
<ifx-card [direction]="direction" href="" target="_blank" aria-label="Card">
  <ifx-card-image position="undefined"
    src="https://upload.wikimedia.org/wikipedia/commons/e/e4/Latte_and_dark_coffee.jpg" alt="Coffee"
    slot="img"></ifx-card-image>
  <ifx-card-overline>
    Overline
  </ifx-card-overline>
  <ifx-card-headline>
    Headline
  </ifx-card-headline>
  <ifx-card-text>
    Some quick example text to build on the card title and make up the bulk of the card's content.
  </ifx-card-text>
  <ifx-card-links slot="buttons">
    <ifx-button variant="primary">Button</ifx-button>
    <ifx-button variant="secondary">Button</ifx-button>
  </ifx-card-links>
</ifx-card>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleDirection()">Toggle Direction</ifx-button>
<br>
<br>
<span><b>Direction:</b> {{ direction }} </span><br>

// examples/wrapper-components/react-vite-js/src/components/Card/Card.jsx
import { useState } from 'react';
import { IfxCard, IfxCardHeadline, IfxButton, IfxCardOverline, IfxCardText, IfxCardImage, IfxCardLinks } from '@infineon/infineon-design-system-react';

function Card() {

  const [directionIndex, setDirectionIndex] = useState(0);
  const directions = ["horizontal", "vertical"];

  const toggleDirection = () => {
    setDirectionIndex((index) => (index + 1) % directions.length);
  }

  return (
    <div>
      <h2>Card</h2>
      <IfxCard href="http://google.com" target="_blank" direction={directions[directionIndex]} aria-label="Card">
        <IfxCardImage position="right" src="https://upload.wikimedia.org/wikipedia/commons/e/e4/Latte_and_dark_coffee.jpg" alt="" slot="img"></IfxCardImage>
        <IfxCardOverline>Overline</IfxCardOverline>
        <IfxCardHeadline>Headline</IfxCardHeadline>
        <IfxCardText>
          Some quick example text to build on the card title and make up the bulk of the card's content
        </IfxCardText>
        <IfxCardLinks slot="buttons">
          <IfxButton variant="primary">Button</IfxButton>
          <IfxButton variant="secondary">Button</IfxButton>
        </IfxCardLinks>
      </IfxCard>
      <br />
      <br />
      <h3 style={{ textDecoration: "underline" }}>Controls</h3>
      <IfxButton variant="secondary" onClick={toggleDirection}>Toggle Direction</IfxButton>
      <br />
      <br />
      <span><b>Direction:</b> {directions[directionIndex]}</span><br />
    </div>
  );
}

export default Card;
