// examples/react-example/src/generated/IfxSwitchExample.tsx
import { IfxSwitch } from '@infineon/infineon-design-system-react';

export function IfxSwitchExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  return (
    <>
      <IfxSwitch
        name="switch"
        value="on"
        checked={false}
        disabled={false}
        readOnly={false}
        onIfxChange={handleChange}>
        Switch
      </IfxSwitch>
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { IfxSwitch } from '@infineon/infineon-design-system-react';

export function IfxSwitchExample() {
  const handleChange = (event: CustomEvent) => {
    console.log('ifxChange:', event);
    // Add your handler logic here
  };

  return (
      <IfxSwitch
        name="switch"
        value="on"
        checked={false}
        disabled={false}
        readOnly={false}
        onIfxChange={handleChange}>
        Switch
      </IfxSwitch>
  );
}`;

// examples/angular-standalone-example/src/app/generated/ifx-switch-example/ifx-switch-example.ts
import { IfxSwitch } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-switch-example',
  imports: [ IfxSwitch ],
  templateUrl: './ifx-switch-example.html',
	styleUrl: './ifx-switch-example.scss'
})
export class IfxSwitchExample {
  protected readonly tsCode = `import { IfxSwitch } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-switch-example&#039;,
  imports: [ IfxSwitch ],
  templateUrl: &#039;./ifx-switch-example.html&#039;,
	styleUrl: &#039;./ifx-switch-example.scss&#039;
})
export class IfxSwitchExample {
  protected handleChange(event: CustomEvent) {
    console.log(&#039;ifxChange:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-switch
    name=&quot;switch&quot;
    value=&quot;on&quot;
    [checked]=&quot;false&quot;
    [disabled]=&quot;false&quot;
    [readOnly]=&quot;false&quot;
    (ifxChange)=&quot;handleChange(\$any(\$event))&quot;&gt;Switch&lt;/ifx-switch&gt;`;

  protected handleChange(event: CustomEvent) {
    console.log('ifxChange:', event);
    // Add your handler logic here
  }
}
