// examples/wrapper-components/react-typescript/src/components/Footer/Footer.tsx

import { IfxFooter, IfxLink, IfxIcon, IfxFooterColumn } from '@infineon/infineon-design-system-react';

function Footer() {
  return (
    <IfxFooter variant="large">
      <IfxFooterColumn slot="col">
        <h5 slot="title">Title</h5>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
      </IfxFooterColumn>
      <IfxFooterColumn slot="col">
        <h5 slot="title">Title</h5>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
      </IfxFooterColumn>
      <IfxFooterColumn slot="col">
        <h5 slot="title">Title</h5>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
      </IfxFooterColumn>
      <IfxFooterColumn slot="col">
        <h5 slot="title">Title</h5>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
        <IfxLink bold="false" slot="link">Footer Link</IfxLink>
      </IfxFooterColumn>
      <div slot="socials">
        <IfxLink href="http://facebook.com/infineon">
          <IfxIcon icon="c-info-16"></IfxIcon>
        </IfxLink>
        <IfxLink href="http://youtube.com/infineon">
          <IfxIcon icon="c-info-16"></IfxIcon>
        </IfxLink>
        <IfxLink href="http://instagram.com/infineon">
          <IfxIcon icon="c-info-16"></IfxIcon>
        </IfxLink>
        <IfxLink href="http://linkedin.com/infineon">
          <IfxIcon icon="c-info-16"></IfxIcon>
        </IfxLink>
        <IfxLink href="http://twitter.com/infineon">
          <IfxIcon icon="c-info-16"></IfxIcon>
        </IfxLink>
        <IfxLink href="http://xing.com/infineon">
          <IfxIcon icon="c-info-16"></IfxIcon>
        </IfxLink>
      </div>
  </IfxFooter>
  );
}

export default Footer;

// examples/wrapper-components/vue-typescript/src/components/Footer.vue
<template>
  <div>
    <h2>Footer</h2>
    <ifx-footer variant="large">
  <ifx-footer-column slot="col">
    <h5 slot="title">Title</h5>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
  </ifx-footer-column>
  <ifx-footer-column slot="col">
    <h5 slot="title">Title</h5>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
  </ifx-footer-column>
  <ifx-footer-column slot="col">
    <h5 slot="title">Title</h5>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link href="#" variant="underlined" slot="link">Footer Link</ifx-link>
  </ifx-footer-column>
  <ifx-footer-column slot="col">
    <h5 slot="title">Title</h5>
    <ifx-link variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link variant="underlined" slot="link">Footer Link</ifx-link>
    <ifx-link variant="underlined" slot="link">Footer Link</ifx-link>
  </ifx-footer-column>
  <div slot="socials">
    <ifx-link variant="title" href="http://facebook.com/infineon">
      <ifx-icon icon="facebook"></ifx-icon>
    </ifx-link>
    <ifx-link variant="title" href="http://youtube.com/infineon">
      <ifx-icon icon="youtube"></ifx-icon>
    </ifx-link>
    <ifx-link variant="title" href="http://instagram.com/infineon">
      <ifx-icon icon="instagram"></ifx-icon>
    </ifx-link>
    <ifx-link variant="title" href="http://linkedin.com/infineon">
      <ifx-icon icon="linkedin"></ifx-icon>
    </ifx-link>
    <ifx-link variant="title" href="http://twitter.com/infineon">
      <ifx-icon icon="twitter"></ifx-icon>
    </ifx-link>
    <ifx-link variant="title" href="http://xing.com/infineon">
      <ifx-icon icon="xing"></ifx-icon>
    </ifx-link>
  </div>
</ifx-footer>
  </div>
</template>

<script setup>

</script>
