// examples/wrapper-components/react-typescript/src/components/ProgressBar/ProgressBar.tsx
import React, { useState } from 'react';
import { IfxProgressBar, IfxButton } from '@infineon/infineon-design-system-react';

function ProgressBar() {
  const [progressValue, setProgressValue] = useState(25);

  // Define your methods here
  const updateProgressOnClick = () => {
    setProgressValue((currentValue) => {
      console.log("updating progress-bar value ", progressValue)
      if (currentValue < 100) {
        return currentValue + 10;
      } else {
        return 10;
      }
    });
  };

  return (
    <div>
      <IfxProgressBar value={progressValue} showLabel={true}></IfxProgressBar>
      <IfxButton onClick={updateProgressOnClick} variant="outline" href="" target="_blank" color="primary" size="s"
        disabled={false} icon={false}>
        Update Progress
      </IfxButton>
    </div >
  );
}

export default ProgressBar;

// examples/wrapper-components/vue-typescript/src/components/ProgressBar.vue


<template>
  <div>
    <h2>Progress bar</h2>

    <h3>Using v-model</h3>
    <ifx-progress-bar v-model="progress" size="m" show-label="true"></ifx-progress-bar>
    <br />
    <ifx-button @click="updateProgress" variant="outline" href="" target="_blank" color="primary" size="s"
      disabled="false" icon="false">
      Update Progress
    </ifx-button>
    <br />
    <br />
  </div>
</template>

<script lang="ts" setup>

import { computed, onMounted, ref } from 'vue'

const progressValue = ref(50);



onMounted(() => {
  updateProgress();
  setInterval(updateProgress, 50000);
})

const progress = computed(() => {
  return progressValue.value;
});

function updateProgress() {
  console.log("updating progress")
  progressValue.value < 100 ? progressValue.value += 10 : progressValue.value = 10;
}

</script>
