// packages/components-angular/projects/my-app/src/app/components/notification/notification.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-notification',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './notification.component.html',
  styleUrl: './notification.component.scss'
})
export class NotificationComponent {

}

<h2>Notification</h2>
  <ifx-notification icon="c-check-16" variant="success" link-text="Link" link-href="https://www.example.com">Success
    notification</ifx-notification>
  <br />
  <ifx-notification icon="lock-16" variant="locked" link-text="Link" link-href="https://www.example.com">Locked
    notification</ifx-notification>
  <br />
  <ifx-notification icon="c-check-16" variant="error" link-text="Link" link-href="https://www.example.com">Error
    notification</ifx-notification>

// examples/wrapper-components/react-vite-js/src/components/Notification/Notification.jsx
import { IfxNotification } from '@infineon/infineon-design-system-react';

function Notification() {
  return (
    <div>
      <h2>Notification</h2>
      <IfxNotification icon="c-check-16" variant="success" link-text="Link" link-href="https://www.example.com">Success notification</IfxNotification>
      <br />
      <IfxNotification icon="lock-16" variant="locked" link-text="Link" link-href="https://www.example.com">Locked notification</IfxNotification>
      <br />
      <IfxNotification icon="c-check-16" variant="error" link-text="Link" link-href="https://www.example.com">Error notification</IfxNotification>
    </div>
  );
}

export default Notification;
