// examples/vue-example/src/generated/IfxStepperExample.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import { IfxButton, IfxStep, IfxStepper, IfxTextField } from '@infineon/infineon-design-system-vue';

const activeStep = ref(2);
const indicatorPositionOptions = ["left","right"];
const indicatorPositionIndex = ref(0);
const showStepNumber = ref(false);
const variantOptions = ["default","compact","vertical"];
const variantIndex = ref(0);
const ariaLabelText = ref("");
const ariaCurrentText = ref("");

const handleActiveStepChange = (nextValue: string) => { activeStep.value = Number(nextValue); };
const handleIndicatorPositionChange = () => { indicatorPositionIndex.value = (indicatorPositionIndex.value + 1) % indicatorPositionOptions.length; };
const handleShowStepNumberChange = () => { showStepNumber.value = !showStepNumber.value; };
const handleVariantChange = () => { variantIndex.value = (variantIndex.value + 1) % variantOptions.length; };
const handleAriaLabelTextChange = (nextValue: string) => { ariaLabelText.value = nextValue; };
const handleAriaCurrentTextChange = (nextValue: string) => { ariaCurrentText.value = nextValue; };

const controlledProps = computed<Record<string, unknown>>(() => ({
  "activeStep": activeStep.value,
  "indicatorPosition": indicatorPositionOptions[indicatorPositionIndex.value],
  "showStepNumber": showStepNumber.value,
  "variant": variantOptions[variantIndex.value],
  "ariaLabelText": ariaLabelText.value,
  "ariaCurrentText": ariaCurrentText.value,
}));

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};

const getInputValue = (event: Event) => String((event.target as HTMLInputElement | null)?.value ?? "");

const formatPropValueForCode = (name: string, value: unknown): string => {
  if (typeof value === 'boolean') return ':' + name + '="' + String(value) + '"';
  if (typeof value === 'number') return ':' + name + '="' + String(value) + '"';
  if (value === null) return ':' + name + '="null"';
  if (Array.isArray(value) || (typeof value === 'object' && value !== null)) {
    const escaped = JSON.stringify(value).replace(/'/g, "\\'");
    return ":" + name + "='" + escaped + "'";
  }
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return name + '="' + escaped + '"';
};

const controlledPropsCode = computed(() => [
  ["activeStep", activeStep.value],
  ["indicatorPosition", indicatorPositionOptions[indicatorPositionIndex.value]],
  ["showStepNumber", showStepNumber.value],
  ["variant", variantOptions[variantIndex.value]],
  ["ariaLabelText", ariaLabelText.value],
  ["ariaCurrentText", ariaCurrentText.value],
]
  .map(([name, value]) => '        ' + formatPropValueForCode(String(name), value))
  .join('\n'));

const codeTemplate = computed(() => `<script setup lang="ts">
import { IfxStep, IfxStepper } from '@infineon/infineon-design-system-vue';

const handleChange = (event: CustomEvent) => {
  console.log('ifxChange:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-stepper
      @ifxChange="handleChange"
      __CONTROLLED_PROPS__>
      <ifx-step>
        Step Label 1
      </ifx-step>
      <ifx-step>
        Step Label 2
      </ifx-step>
      <ifx-step>
        Step Label 3
      </ifx-step>
      <ifx-step>
        Step Label 4
      </ifx-step>
      <ifx-step>
        Step Label 5
      </ifx-step>
    </ifx-stepper>
  </div>
${'</'}template>`.replace("__CONTROLLED_PROPS__", controlledPropsCode.value));

const codeString = codeTemplate;
</script>

<template>
  <div>
    <ifx-stepper
      @ifxChange="handleChange"
      v-bind="controlledProps">
      <ifx-step>
        Step Label 1
      </ifx-step>
      <ifx-step>
        Step Label 2
      </ifx-step>
      <ifx-step>
        Step Label 3
      </ifx-step>
      <ifx-step>
        Step Label 4
      </ifx-step>
      <ifx-step>
        Step Label 5
      </ifx-step>
    </ifx-stepper>
    <h3 class="controls-title">Controls</h3>
    <div class="controls controls-toggle">
        <ifx-button variant="secondary" @click="handleIndicatorPositionChange">Toggle IndicatorPosition</ifx-button>
        <ifx-button variant="secondary" @click="handleShowStepNumberChange">Toggle ShowStepNumber</ifx-button>
        <ifx-button variant="secondary" @click="handleVariantChange">Toggle Variant</ifx-button>
    </div>
    <div class="controls controls-input">
        <ifx-text-field label="activeStep" type="text" :value="String(activeStep)" @input="handleActiveStepChange(getInputValue($event))" />
        <ifx-text-field label="ariaLabelText" type="text" :value="String(ariaLabelText)" @input="handleAriaLabelTextChange(getInputValue($event))" />
        <ifx-text-field label="ariaCurrentText" type="text" :value="String(ariaCurrentText)" @input="handleAriaCurrentTextChange(getInputValue($event))" />
    </div>

    <div class="state">
      <div><b>activeStep:</b> {{ String(activeStep) }}</div>
      <div><b>indicatorPosition:</b> {{ String(indicatorPositionOptions[indicatorPositionIndex]) }}</div>
      <div><b>showStepNumber:</b> {{ String(showStepNumber) }}</div>
      <div><b>variant:</b> {{ String(variantOptions[variantIndex]) }}</div>
      <div><b>ariaLabelText:</b> {{ String(ariaLabelText) }}</div>
      <div><b>ariaCurrentText:</b> {{ String(ariaCurrentText) }}</div>
    </div>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-standalone-example/src/app/generated/ifx-stepper-example/ifx-stepper-example.ts
import { IfxButton, IfxStep, IfxStepper, IfxTextField } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';
@Component({
  selector: 'app-ifx-stepper-example',
  imports: [ IfxButton, IfxStep, IfxStepper, IfxTextField ],
  templateUrl: './ifx-stepper-example.html',
  styleUrl: './ifx-stepper-example.scss'
})
export class IfxStepperExample {
  protected readonly tsCode = `import { IfxButton, IfxStep, IfxStepper, IfxTextField } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';
@Component({
  selector: 'app-ifx-stepper-example',
  imports: [ IfxButton, IfxStep, IfxStepper, IfxTextField ],
  templateUrl: './ifx-stepper-example.html',
  styleUrl: './ifx-stepper-example.scss'
})
export class IfxStepperExample {

  protected activeStep = 2;
  protected readonly indicatorPositionOptions = ["left","right"];
  protected indicatorPositionIndex = 0;
  protected showStepNumber = false;
  protected readonly variantOptions = ["default","compact","vertical"];
  protected variantIndex = 0;
  protected ariaLabelText = "";
  protected ariaCurrentText = "";

  protected updateActiveStep(value: string) {
    this.activeStep = Number(value);
  }

  protected handleIndicatorPositionChange() {
    this.indicatorPositionIndex = (this.indicatorPositionIndex + 1) % this.indicatorPositionOptions.length;
  }

  protected handleShowStepNumberChange() {
    this.showStepNumber = !this.showStepNumber;
  }

  protected handleVariantChange() {
    this.variantIndex = (this.variantIndex + 1) % this.variantOptions.length;
  }

  protected updateAriaLabelText(value: string) {
    this.ariaLabelText = value;
  }

  protected updateAriaCurrentText(value: string) {
    this.ariaCurrentText = value;
  }

  protected getControlInputValue(event: Event | CustomEvent): string {
    const target = event.target as (HTMLInputElement & { value?: unknown }) | null;
    return String(target?.value ?? '');
  }

  protected stringifyValue(value: unknown): string {
    if (value === null || value === undefined) return '';
    if (typeof value === 'string') return value;
    if (typeof value === 'object') {
      try {
        return JSON.stringify(value);
      } catch {
        return String(value);
      }
    }
    return String(value);
  }

  protected handleChange(event: CustomEvent) {
    console.log('ifxChange:', event);
    // Add your handler logic here
  }

}`;
  protected readonly htmlCode = `  &lt;ifx-stepper
    [activeStep]=&quot;activeStep&quot;
    [ariaLabelText]=&quot;ariaLabelText&quot;
    [ariaCurrentText]=&quot;ariaCurrentText&quot;
    [showStepNumber]=&quot;showStepNumber&quot;
    [variant]=&quot;variantOptions[variantIndex]&quot;
    [indicatorPosition]=&quot;indicatorPositionOptions[indicatorPositionIndex]&quot;&gt;
    &lt;ifx-step&gt;Step Label 1&lt;/ifx-step&gt;
    &lt;ifx-step&gt;Step Label 2&lt;/ifx-step&gt;
    &lt;ifx-step&gt;Step Label 3&lt;/ifx-step&gt;
    &lt;ifx-step&gt;Step Label 4&lt;/ifx-step&gt;
    &lt;ifx-step&gt;Step Label 5&lt;/ifx-step&gt;
  &lt;/ifx-stepper&gt;`;

  protected activeStep = 2;
  protected readonly indicatorPositionOptions = ["left","right"];
  protected indicatorPositionIndex = 0;
  protected showStepNumber = false;
  protected readonly variantOptions = ["default","compact","vertical"];
  protected variantIndex = 0;
  protected ariaLabelText = "";
  protected ariaCurrentText = "";

  protected updateActiveStep(value: string) {
    this.activeStep = Number(value);
  }

  protected handleIndicatorPositionChange() {
    this.indicatorPositionIndex = (this.indicatorPositionIndex + 1) % this.indicatorPositionOptions.length;
  }

  protected handleShowStepNumberChange() {
    this.showStepNumber = !this.showStepNumber;
  }

  protected handleVariantChange() {
    this.variantIndex = (this.variantIndex + 1) % this.variantOptions.length;
  }

  protected updateAriaLabelText(value: string) {
    this.ariaLabelText = value;
  }

  protected updateAriaCurrentText(value: string) {
    this.ariaCurrentText = value;
  }

  protected getControlInputValue(event: Event | CustomEvent): string {
    const target = event.target as (HTMLInputElement & { value?: unknown }) | null;
    return String(target?.value ?? '');
  }

  protected stringifyValue(value: unknown): string {
    if (value === null || value === undefined) return '';
    if (typeof value === 'string') return value;
    if (typeof value === 'object') {
      try {
        return JSON.stringify(value);
      } catch {
        return String(value);
      }
    }
    return String(value);
  }

  protected handleChange(event: CustomEvent) {
    console.log('ifxChange:', event);
    // Add your handler logic here
  }

}
