// packages/components-angular/projects/my-app/src/app/components/indicator/indicator.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-indicator',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './indicator.component.html',
  styleUrl: './indicator.component.scss'
})
export class IndicatorComponent {
  variant = "number";
  variants = ["number", "dot"];
  variantIndex = 0;

  inverted = false;

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }

  toggleInverted() {
    this.inverted = !this.inverted;
  }
}

<h2>Indicator</h2>
<ifx-indicator [variant]="variant" number="1" [inverted]="inverted" />
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleVariant()">Toggle Variant</ifx-button>
<ifx-button variant="secondary" (click)="toggleInverted()">Toggle Inverted</ifx-button>
<br>
<br>
<span><b>Variant:</b> {{ variant }} </span><br>
<span><b>Inverted:</b> {{ inverted }} </span><br>

// examples/wrapper-components/react-vite-js/src/components/Indicator/Indicator.jsx
import { useState } from 'react';
import { IfxIndicator, IfxButton } from '@infineon/infineon-design-system-react';

function Indicator() {
  const [inverted, setInverted] = useState(false);

  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ["number", "dot",];

  const toggleInverted = () => {
    setInverted(prevInverted => !prevInverted);
  }

  const toggleVariant = () => {
    setVariantIndex((index) => (index + 1) % variants.length);
  }

  return (
    <div>
      <h2>Indicator</h2>
      <IfxIndicator variant={variants[variantIndex]} number="1" inverted={inverted} />
      <br />
      <br />
      <h3 style={{textDecoration: "underline"}}>Controls</h3>
      <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
      <IfxButton variant="secondary" onClick={toggleInverted}>Toggle Inverted</IfxButton>
      <br />
      <br />
      <span><b>Variant:</b> {variants[variantIndex]}</span><br />
      <span><b>Inverted:</b> {String(inverted)}</span><br />
    </div>
  );
}

export default Indicator;
