// examples/vue-example/src/generated/IfxErrorPageExample.vue
<script setup lang="ts">

import { IfxButton, IfxErrorPage } from '@infineon/infineon-design-system-vue';

const codeString = `<script setup lang="ts">
${'</'}script>

<template>
  <div>
    <ifx-error-page
      alt=""
      :type=403
      headline=""
      description=""
      illustration-url="">
      <div slot="button">
        <ifx-button
          slot="button"
          variant="primary"
          :full-width="true">
          Button Custom 1
        </ifx-button>
      </div>
      <div slot="button">
        <ifx-button
          slot="button"
          variant="secondary"
          :full-width="true">
          Button Custom 2
        </ifx-button>
      </div>
    </ifx-error-page>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-error-page
      alt=""
      :type=403
      headline=""
      description=""
      illustration-url="">
      <div slot="button">
        <ifx-button
          slot="button"
          variant="primary"
          :full-width="true">
          Button Custom 1
        </ifx-button>
      </div>
      <div slot="button">
        <ifx-button
          slot="button"
          variant="secondary"
          :full-width="true">
          Button Custom 2
        </ifx-button>
      </div>
    </ifx-error-page>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-module-example/src/app/generated/ifx-error-page-example/ifx-error-page-example.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-error-page-example',
  templateUrl: './ifx-error-page-example.html',
  styleUrl: './ifx-error-page-example.scss',
  standalone: false
})
export class IfxErrorPageExample {
  protected readonly tsCode = `import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-error-page-example&#039;,
  templateUrl: &#039;./ifx-error-page-example.html&#039;,
  styleUrl: &#039;./ifx-error-page-example.scss&#039;,
  standalone: false
})
export class IfxErrorPageExample {}`;
  protected readonly htmlCode = `  &lt;ifx-error-page
    alt=&quot;&quot;
    type=&quot;403&quot;
    headline=&quot;&quot;
    description=&quot;&quot;
    illustration-url=&quot;&quot;&gt;
    &lt;div slot=&quot;button&quot;&gt;
      &lt;ifx-button
        slot=&quot;button&quot;
        variant=&quot;primary&quot;
        [fullWidth]=&quot;true&quot;&gt;Button Custom 1&lt;/ifx-button&gt;
    &lt;/div&gt;
    &lt;div slot=&quot;button&quot;&gt;
      &lt;ifx-button
        slot=&quot;button&quot;
        variant=&quot;secondary&quot;
        [fullWidth]=&quot;true&quot;&gt;Button Custom 2&lt;/ifx-button&gt;
    &lt;/div&gt;
  &lt;/ifx-error-page&gt;`;
}
