// examples/vue-example/src/manual/ModalExample.vue
<template>
  <div>
    <ifx-modal
      caption="Modal Title"
      caption-aria-label="Additional information for caption"
      close-button-aria-label="Close modal"
      variant="default"
      :close-on-overlay-click="false"
      :show-close-button="true"
      size="s"
      v-model="opened"
      @ifxOpen="handleOpen"
      @ifxClose="handleClose">
      <div slot="content">
        <span>Modal content</span>
      </div>
      <div slot="buttons">
        <ifx-button variant="secondary">Cancel</ifx-button>
        <ifx-button>OK</ifx-button>
      </div>
    </ifx-modal>
    <ifx-button @click="openModal">Open Modal</ifx-button>

    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeExample }}</code></pre>
    </details>
  </div>
</template>

<script setup lang="ts">
import { IfxModal } from '@infineon/infineon-design-system-vue';

import { ref } from 'vue';

const opened = ref(false);

const openModal = () => {
  opened.value = true;
};

const handleOpen = (event: CustomEvent) => {
  console.log('ifxOpen:', event.detail);
};

const handleClose = (event: CustomEvent) => {
  console.log('ifxClose:', event.detail);
};

const codeExample = `<template>
  <div>
    <ifx-modal
      caption="Modal Title"
      caption-aria-label="Additional information for caption"
      close-button-aria-label="Close modal"
      variant="default"
      :close-on-overlay-click="false"
      :show-close-button="true"
      size="s"
      v-model="opened"
      @ifxOpen="handleOpen"
      @ifxClose="handleClose">
      <div slot="content">
        <span>Modal content</span>
      </div>
      <div slot="buttons">
        <ifx-button variant="secondary">Cancel</ifx-button>
        <ifx-button>OK</ifx-button>
      </div>
    </ifx-modal>
    <ifx-button @click="openModal">Open Modal</ifx-button>
  </div>
</template>

<script setup lang="ts">
import { IfxModal } from '@infineon/infineon-design-system-vue';
import { ref } from 'vue';

const opened = ref(false);

const openModal = () => {
  opened.value = true;
};

const handleOpen = (event: CustomEvent) => {
  console.log('ifxOpen:', event.detail);
};

const handleClose = (event: CustomEvent) => {
  console.log('ifxClose:', event.detail);
};
<\/script>`;
</script>

// examples/react-example/src/manual/ModalExample.tsx
import { useRef } from 'react';
import { IfxButton, IfxModal } from '@infineon/infineon-design-system-react';

export function ModalExample() {
  const modalRef = useRef<HTMLIfxModalElement>(null);

  const openModal = () => {
    if (modalRef.current) {
      modalRef.current.opened = true;
    }
  };

  const handleOpen = (event: CustomEvent) => {
    console.log('ifxOpen:', event.detail);
  };

  const handleClose = (event: CustomEvent) => {
    console.log('ifxClose:', event.detail);
  };

  return (
    <>
      <IfxModal
        ref={modalRef}
        caption="Modal Title"
        captionAriaLabel="Additional information for caption"
        closeButtonAriaLabel="Close modal"
        variant="default"
        closeOnOverlayClick={false}
        showCloseButton={true}
        size="s"
        onIfxOpen={handleOpen}
        onIfxClose={handleClose}>
        <div slot="content">
          <span>Modal content</span>
        </div>
        <div slot="buttons">
          <IfxButton variant="secondary">Cancel</IfxButton>
          <IfxButton>OK</IfxButton>
        </div>
      </IfxModal>
      <IfxButton onClick={openModal}>Open Modal</IfxButton>

      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = `import { useRef } from 'react';
import { IfxButton, IfxModal } from '@infineon/infineon-design-system-react';

export function ModalExample() {
  const modalRef = useRef<HTMLIfxModalElement>(null);

  const openModal = () => {
    if (modalRef.current) {
      modalRef.current.opened = true;
    }
  };

  const handleOpen = (event: CustomEvent) => {
    console.log('ifxOpen:', event.detail);
  };

  const handleClose = (event: CustomEvent) => {
    console.log('ifxClose:', event.detail);
  };

  return (
    <>
      <IfxModal
        ref={modalRef}
        caption="Modal Title"
        captionAriaLabel="Additional information for caption"
        closeButtonAriaLabel="Close modal"
        variant="default"
        closeOnOverlayClick={false}
        showCloseButton={true}
        size="s"
        onIfxOpen={handleOpen}
        onIfxClose={handleClose}>
        <div slot="content">
          <span>Modal content</span>
        </div>
        <div slot="buttons">
          <IfxButton variant="secondary">Cancel</IfxButton>
          <IfxButton>OK</IfxButton>
        </div>
      </IfxModal>
      <IfxButton onClick={openModal}>Open Modal</IfxButton>
    </>
  );
}`;
