// example-generator/src/formatters/react-formatter.ts
import type { ComponentInfo, ComponentStructure } from '../types.js';
import type { ICodeFormatter, FormatOptions } from '../interfaces.js';
import { 
  toPascalCase, 
  toCamelCase, 
  toReactEventName, 
  toHandlerFunctionName,
  escapeForTemplateLiteral
} from '../utils/string-utils.js';

/**
 * Formats components into React/JSX code
 */
export class ReactCodeFormatter implements ICodeFormatter {
  /**
   * Format component structure to React JSX
   */
  formatComponent(component: ComponentInfo, options: FormatOptions): string {
    const { indent = '      ' } = options;
    const isFirstOfType = new Map<string, boolean>();
    
    return this.structureToJSX(component.structure, component, indent, isFirstOfType);
  }

  /**
   * Format event handlers for React
   */
  formatEventHandlers(component: ComponentInfo, options: FormatOptions): string {
    if (component.events.length === 0) return '';

    return component.events.map(event => {
      const handlerName = toHandlerFunctionName(event.name);
      return `  const ${handlerName} = (event: CustomEvent) => {
    console.log('${event.name}:', event.detail);
    // Add your handler logic here
  };`;
    }).join('\n\n');
  }

  /**
   * Format imports for React
   */
  formatImports(component: ComponentInfo): string {
    const componentTags = this.collectComponentTags(component.structure);
    // Only import Infineon components (starting with ifx-), not native HTML elements
    const imports = Array.from(componentTags)
      .filter(tag => tag.startsWith('ifx-'))
      .map(tag => toPascalCase(tag))
      .sort()
      .join(', ');
    
    return `import { ${imports} } from '@infineon/infineon-design-system-react';`;
  }

  /**
   * Generate complete React component file content
   */
  formatComponentFile(component: ComponentInfo): string {
    const componentName = toPascalCase(component.component);
    const storyNameSuffix = component.storyName && component.storyName !== 'Default' 
      ? component.storyName.replace(/\s+/g, '') 
      : '';
    const componentClassName = `${componentName}${storyNameSuffix}Example`;
    const imports = this.formatImports(component);
    const eventHandlers = this.formatEventHandlers(component, { indent: '  ' });
    const jsx = this.formatComponent(component, { indent: '      ' });

    // Generate the code string for display
    const codeForDisplay = this.generateCodeForDisplay(component, eventHandlers, jsx);
    
    // Escape for safe embedding in a template literal
    const escapedCodeForDisplay = escapeForTemplateLiteral(codeForDisplay);

    return `${imports}

export function ${componentClassName}() {
${eventHandlers ? eventHandlers + '\n\n' : ''}  return (
    <>
${jsx}
      <details className="code-details">
        <summary>View Code</summary>
        <pre><code className="language-tsx">{codeString}</code></pre>
      </details>
    </>
  );
}

const codeString = \`${escapedCodeForDisplay}\`;
`;
  }

  /**
   * Generate code string for display in the details section
   */
  private generateCodeForDisplay(component: ComponentInfo, eventHandlers: string, jsx: string): string {
    const componentName = toPascalCase(component.component);
    const imports = this.formatImports(component);
    
    // Build the display code without the details section
    let displayCode = `${imports}

export function ${componentName}Example() {`;
    
    if (eventHandlers) {
      displayCode += `\n${eventHandlers}\n`;
    }
    
    displayCode += `\n  return (\n${jsx}\n  );\n}`;
    
    return displayCode;
  }

  /**
   * Convert component structure to React JSX
   */
  private structureToJSX(
    struct: ComponentStructure,
    componentInfo: ComponentInfo,
    indent: string,
    isFirstOfType: Map<string, boolean>
  ): string {
    // Use PascalCase for Infineon components (ifx-*), lowercase for native HTML
    const componentName = struct.tag.startsWith('ifx-') 
      ? toPascalCase(struct.tag) 
      : struct.tag;
    
    // Track if this is the first occurrence of this tag type (for events)
    const isFirst = !isFirstOfType.has(struct.tag);
    if (isFirst) {
      isFirstOfType.set(struct.tag, true);
    }
    
    // Convert attributes to React props
    const propEntries = Object.entries(struct.attributes)
      .map(([key, value]) => {
        const propName = toCamelCase(key);
        const propValue = this.toReactPropValue(value, key);
        return propValue ? [propName, propValue] : null;
      })
      .filter(Boolean) as [string, string][];
    
    // Check if this specific element type should have event handlers
    const shouldAddEvents = componentInfo.events.length > 0 && 
      (struct.children && struct.children.length > 0 ? 
        struct.tag !== componentInfo.component : 
        struct.tag.includes(componentInfo.component));
    
    // Add event handlers for children elements only on first occurrence
    const eventProps: [string, string][] = [];
    if (shouldAddEvents && isFirst) {
      componentInfo.events.forEach(event => {
        const reactEventName = toReactEventName(event.name);
        const handlerName = toHandlerFunctionName(event.name);
        eventProps.push([reactEventName, `{${handlerName}}`]);
      });
    }
    
    const allProps = [...propEntries, ...eventProps];
    
    // Format opening tag with props
    const openTag = this.formatOpeningTag(componentName, allProps, indent);
    
    // Handle children
    if (struct.children && struct.children.length > 0) {
      const childrenJSX = struct.children
        .map((child) => this.structureToJSX(child, componentInfo, indent + '  ', isFirstOfType))
        .join('\n');
      return `${openTag}>\n${childrenJSX}\n${indent}</${componentName}>`;
    }
    
    // Handle text content
    if (struct.textContent) {
      const trimmedText = struct.textContent.trim();
      return `${openTag}>\n${indent}  ${trimmedText}\n${indent}</${componentName}>`;
    }
    
    // Self-closing tag
    return `${openTag} />`;
  }

  /**
   * Format opening tag with props
   */
  private formatOpeningTag(
    componentName: string,
    props: [string, string][],
    indent: string
  ): string {
    if (props.length === 0) {
      return `${indent}<${componentName}`;
    } else if (props.length === 1) {
      const [name, value] = props[0];
      return `${indent}<${componentName} ${name}=${value}`;
    } else {
      const propsString = props
        .map(([name, value]) => `${indent}  ${name}=${value}`)
        .join('\n');
      return `${indent}<${componentName}\n${propsString}`;
    }
  }

  /**
   * Convert attribute value to React prop value
   */
  private toReactPropValue(value: string, attrName: string): string | null {
    // Skip undefined values
    if (value === 'undefined') return null;
    
    // Boolean values
    if (value === 'true') return '{true}';
    if (value === 'false') return '{false}';
    
    // Numeric values
    if (!isNaN(Number(value)) && value !== '' && value !== 'null') {
      return `{${value}}`;
    }
    
    // Null
    if (value === 'null') return null;
    
    // String values - if contains quotes, use JSX expression with template literal
    if (value.includes('"') || value.includes("'")) {
      // Escape backslashes, backticks and dollar signs for template literals
      const escapedValue = escapeForTemplateLiteral(value);
      return `{\`${escapedValue}\`}`;
    }
    
    return `"${value}"`;
  }

  /**
   * Collect all unique component tags from structure (for imports)
   */
  private collectComponentTags(struct: ComponentStructure, tags = new Set<string>()): Set<string> {
    tags.add(struct.tag);
    
    if (struct.children && struct.children.length > 0) {
      struct.children.forEach((child) => this.collectComponentTags(child, tags));
    }
    
    return tags;
  }
}

// packages/dds-tooling/src/formatters/angular-formatter.ts
import type { ICodeFormatter, FormatOptions } from "../formatter-interface.js";
import type { ComponentInfo, ComponentStructure } from "../types.js";
import {
	escapeForSingleQuotedAttr,
	escapeForTemplateLiteral,
	toAngularEventName,
	toCamelCase,
	toHandlerFunctionName,
	toPascalCase,
} from "../utils/string-utils.js";

/**
 * Formats components into Angular standalone component code
 */
export class AngularCodeFormatter implements ICodeFormatter {
	/**
	 * Format component structure to Angular template HTML
	 */
	formatComponent(component: ComponentInfo, options: FormatOptions): string {
		const { indent = "    " } = options;
		const isFirstOfType = new Map<string, boolean>();

		return this.structureToHTML(
			component.structure,
			component,
			indent,
			isFirstOfType,
		);
	}

	/**
	 * Format event handlers for Angular
	 */
	formatEventHandlers(
		component: ComponentInfo,
		_options: FormatOptions,
	): string {
		if (component.events.length === 0) return "";

		return component.events
			.map((event) => {
				const handlerName = toHandlerFunctionName(event.name);
				return `  protected ${handlerName}(event: CustomEvent) {
    console.log('${event.name}:', event);
    // Add your handler logic here
  }`;
			})
			.join("\n\n");
	}

	/**
	 * Format imports for Angular
	 */
	formatImports(component: ComponentInfo): string {
		const componentTags = this.collectComponentTags(component.structure);
		// Only import Infineon components (starting with ifx-), not native HTML elements
		const imports = Array.from(componentTags)
			.filter((tag) => tag.startsWith("ifx-"))
			.map((tag) => toPascalCase(tag))
			.sort()
			.join(", ");

		return `import { ${imports} } from '@infineon/infineon-design-system-angular/standalone';`;
	}

	/**
	 * Generate complete Angular component TypeScript file content
	 */
	formatComponentTypeScript(component: ComponentInfo): string {
		const componentName = toPascalCase(component.component);
		const storyNameSuffix =
			component.storyName && component.storyName !== "Default"
				? component.storyName.replace(/\s+/g, "")
				: "";
		const componentClassName = `${componentName}${storyNameSuffix}Example`;
		const selectorSuffix =
			component.storyName && component.storyName !== "Default"
				? `-${component.storyName.toLowerCase().replace(/\s+/g, "-")}`
				: "";
		const componentSelector = `${component.component}-example${selectorSuffix}`;

		const imports = this.formatImports(component);
		const eventHandlers = this.formatEventHandlers(component, { indent: "  " });

		const componentTags = this.collectComponentTags(component.structure);
		// Only import Infineon components (starting with ifx-), not native HTML elements
		const componentImports = Array.from(componentTags)
			.filter((tag) => tag.startsWith("ifx-"))
			.map((tag) => toPascalCase(tag))
			.sort()
			.join(", ");

		// Generate the code strings for display
		const html = this.structureToHTML(
			component.structure,
			component,
			"  ",
			new Map(),
		);
		const tsCode = this.generateTypeScriptCode(
			component,
			componentImports,
			eventHandlers,
		);
		const htmlCode = this.escapeHtml(html);

		return `${imports}
import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentSelector}',
  imports: [ ${componentImports} ],
  templateUrl: './${componentSelector}.html',
	styleUrl: './${componentSelector}.scss'
})
export class ${componentClassName} {
  protected readonly tsCode = \`${this.escapeBackticks(tsCode)}\`;
  protected readonly htmlCode = \`${this.escapeBackticks(htmlCode)}\`;
${eventHandlers ? `\n${eventHandlers}\n` : ""}}
`;
	}

	/**
	 * Generate complete Angular component template HTML file content
	 */
	formatComponentTemplate(component: ComponentInfo): string {
		const html = this.formatComponent(component, { indent: "  " });
		const selectorSuffix =
			component.storyName && component.storyName !== "Default"
				? `-${component.storyName.toLowerCase().replace(/\s+/g, "-")}`
				: "";
		const componentSelector = `${component.component}-example${selectorSuffix}`;

		return `${html}

<details class="code-details">
  <summary>View Code</summary>
  <div class="code-blocks">
    <h3>${componentSelector}.ts</h3>
    <pre><code class="language-typescript" [innerHTML]="tsCode"></code></pre>
    
    <h3>${componentSelector}.html</h3>
    <pre><code class="language-markup" [innerHTML]="htmlCode"></code></pre>
  </div>
</details>
`;
	}

	/**
	 * Generate component SCSS file content
	 */
	formatComponentStyles(): string {
		return `// Add component-specific styles here
`;
	}

	/**
	 * Generate TypeScript code for display
	 */
	private generateTypeScriptCode(
		component: ComponentInfo,
		componentImports: string,
		eventHandlers: string,
	): string {
		const imports = this.formatImports(component);
		const componentName = toPascalCase(component.component);
		const storyNameSuffix =
			component.storyName && component.storyName !== "Default"
				? component.storyName.replace(/\s+/g, "")
				: "";
		const componentClassName = `${componentName}${storyNameSuffix}Example`;
		const selectorSuffix =
			component.storyName && component.storyName !== "Default"
				? `-${component.storyName.toLowerCase().replace(/\s+/g, "-")}`
				: "";
		const componentSelector = `${component.component}-example${selectorSuffix}`;

		let tsCode = `${imports}
import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentSelector}',
  imports: [ ${componentImports} ],
  templateUrl: './${componentSelector}.html',
	styleUrl: './${componentSelector}.scss'
})
export class ${componentClassName} {`;

		if (eventHandlers) {
			tsCode += `\n${eventHandlers}\n`;
		}

		tsCode += `}`;

		return this.escapeHtml(tsCode);
	}

	/**
	 * Escape backticks for template literal
	 */
	private escapeBackticks(str: string): string {
		// First escape backslashes, then backticks and dollar signs.
		// This avoids introducing escape sequences that could break the surrounding
		// template literal when the input already contains backslashes.
		return escapeForTemplateLiteral(str);
	}

	/**
	 * Escape HTML for display in code block
	 */
	private escapeHtml(html: string): string {
		return html
			.replace(/&/g, "&amp;")
			.replace(/</g, "&lt;")
			.replace(/>/g, "&gt;")
			.replace(/"/g, "&quot;")
			.replace(/'/g, "&#039;");
	}

	/**
	 * Convert component structure to Angular template HTML
	 */
	private structureToHTML(
		struct: ComponentStructure,
		componentInfo: ComponentInfo,
		indent: string,
		isFirstOfType: Map<string, boolean>,
	): string {
		const tag = struct.tag;

		// Track if this is the first occurrence of this tag type (for events)
		const isFirst = !isFirstOfType.has(tag);
		if (isFirst) {
			isFirstOfType.set(tag, true);
		}

		// Convert attributes from the actual story DOM only
		const attrs = Object.entries(struct.attributes)
			.map(([key, value]) => this.toAngularAttribute(key, value, componentInfo, tag))
			.filter((attr): attr is string => attr !== null);

		// Check if this specific element type should have event handlers
		const shouldAddEvents =
			componentInfo.events.length > 0 &&
			(struct.children && struct.children.length > 0
				? tag !== componentInfo.component
				: tag.includes(componentInfo.component));

		// Add event handlers for children elements only on first occurrence
		if (shouldAddEvents && isFirst) {
			componentInfo.events.forEach((event) => {
				const angularEventName = toAngularEventName(event.name);
				const handlerName = toHandlerFunctionName(event.name);
				attrs.push(`(${angularEventName})="${handlerName}($any($event))"`);
			});
		}

		// Format opening tag with attributes
		const openTag = this.formatOpeningTag(tag, attrs, indent);

		// Handle children
		if (struct.children && struct.children.length > 0) {
			const childrenHTML = struct.children
				.map((child) =>
					this.structureToHTML(
						child,
						componentInfo,
						`${indent}  `,
						isFirstOfType,
					),
				)
				.join("\n");
			return `${openTag}>\n${childrenHTML}\n${indent}</${tag}>`;
		}

		// Handle text content
		if (struct.textContent) {
			// Don't add extra whitespace - Angular hydration is sensitive to exact text nodes
			// Normalize all whitespace to single spaces
			const trimmedText = struct.textContent.trim().replace(/\s+/g, " ");
			return `${openTag}>${trimmedText}</${tag}>`;
		}

		// Self-closing tag
		return `${openTag}></${tag}>`;
	}

	/**
	 * Format opening tag with attributes
	 */
	private formatOpeningTag(
		tag: string,
		attrs: string[],
		indent: string,
	): string {
		if (attrs.length === 0) {
			return `${indent}<${tag}`;
		} else if (attrs.length === 1) {
			return `${indent}<${tag} ${attrs[0]}`;
		} else {
			const attrsString = attrs.map((attr) => `${indent}  ${attr}`).join("\n");
			return `${indent}<${tag}\n${attrsString}`;
		}
	}

	/**
	 * Convert attribute to Angular template syntax
	 */
	private toAngularAttribute(
		name: string,
		value: string,
		componentInfo: ComponentInfo,
		tag: string,
	): string | null {
		// Skip undefined values
		if (value === "undefined") return null;

		// Normalize Angular-style property binding syntax on custom elements: [prop]="..."
		// We convert these into plain attributes so the web component receives string values reliably.
		let attrName = name;
		let attrValue = value;
		const isBracketBinding = attrName.startsWith("[") && attrName.endsWith("]");
		if (isBracketBinding) {
			attrName = attrName.slice(1, -1); // strip brackets
			// If value is quoted Angular expression like `'text'`, strip quotes
			const m = attrValue.match(/^['"]([\s\S]*)['"]$/);
			if (m) attrValue = m[1];
		}

		if (attrValue.startsWith("__JSON__")) {
			attrValue = attrValue.replace(/^__JSON__/, "");
		}

		const isBooleanProp = this.isBooleanProp(attrName, tag, componentInfo);
		const bindingName = toCamelCase(attrName);
		// Boolean values
		if (attrValue === "true") {
			return isBooleanProp
				? `[${bindingName}]="true"`
				: `${attrName}="true"`;
		}
		if (attrValue === "false") {
			return isBooleanProp
				? `[${bindingName}]="false"`
				: `${attrName}="false"`;
		}
		if (attrValue === "") {
			return isBooleanProp ? `[${bindingName}]="true"` : null;
		}

		// Numeric values
		if (
			!Number.isNaN(Number(attrValue)) &&
			attrValue !== "" &&
			attrValue !== "null"
		) {
			return `${attrName}="${attrValue}"`;
		}

		// Null
		if (attrValue === "null") return null;

		// JSON arrays or objects (contain { or [ at start) - use property binding
		// Some DOM attributes coerce arrays/objects to "[object Object]"; prefer defaultArgs when available
		if (
			attrValue.startsWith("[") ||
			attrValue.startsWith("{") ||
			attrValue.includes("[object Object")
		) {
			const camelName = toCamelCase(attrName);
			const original = (
				componentInfo?.defaultArgs as Record<string, unknown>
			)?.[camelName];
			let jsonString = attrValue;
			if (original !== undefined && typeof original === "object") {
				try {
					jsonString = JSON.stringify(original);
				} catch {
					// keep existing value if stringify fails
				}
			}
			const escapedValue = escapeForSingleQuotedAttr(jsonString);
			// Bind as string attribute (web components commonly parse JSON from attribute string)
			return `${attrName}='${escapedValue}'`;
		}

		// String values
		return `${attrName}="${attrValue}"`;
	}

private isBooleanProp(name: string, tag: string, componentInfo: ComponentInfo): boolean {
		const typeText = componentInfo.propTypes[tag]?.[name];
		return typeText === "boolean";
	}

	/**
	 * Collect all unique component tags from structure (for imports)
	 */
	private collectComponentTags(
		struct: ComponentStructure,
		tags = new Set<string>(),
	): Set<string> {
		tags.add(struct.tag);

		if (struct.children && struct.children.length > 0) {
			struct.children.forEach((child) => {
				this.collectComponentTags(child, tags);
			});
		}

		return tags;
	}
}
