// packages/components-angular/projects/my-app/src/app/components/button/button.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './button.component.html',
  styleUrl: './button.component.scss'
})
export class ButtonComponent {
  variant = "primary";
  variants = ["primary", "secondary", "tertiary"];
  variantIndex = 0;

  theme = "default";
  themes = ["default", "danger", "inverse"];
  themeIndex = 0;

  size = "m";
  sizes = ["xs", "s", "m", "l"];
  sizeIndex = 0;

  icon = "";
  icons = ["", "fileMpg16"];
  iconIndex = 0;

  fullWidth = false;
  disabled = false;

  toggleVariant() {
    this.variantIndex = (this.variantIndex + 1) % this.variants.length;
    this.variant = this.variants[this.variantIndex];
  }

  toggleTheme() {
    this.themeIndex = (this.themeIndex + 1) % this.themes.length;
    this.theme = this.themes[this.themeIndex];
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }

  toggleIcon() {
    this.iconIndex = (this.iconIndex + 1) % this.icons.length;
    this.icon = this.icons[this.iconIndex];
  }

  toggleFullWidth() {
    this.fullWidth = !this.fullWidth;
  }

  toggleDisabled() {
    this.disabled = !this.disabled;
  }

}

<h2>Button</h2>

<ifx-button type="button" aria-label="Button" [disabled]="buttonDisabled" [variant]="buttonVariant" [size]="buttonSize"
  target="_blank" [theme]="buttonTheme" [fullWidth]="buttonFullWidth">
  <ifx-icon [icon]="buttonIcon"></ifx-icon>Button
</ifx-button>
<br>
<br>
<h3 style="text-decoration: underline;">Controls</h3>
<ifx-button variant="secondary" (click)="toggleButtonVariant()">Toggle Variant</ifx-button>
<ifx-button variant="secondary" (click)="toggleButtonTheme()">Toggle Theme</ifx-button>
<ifx-button variant="secondary" (click)="toggleButtonSize()">Toggle Size</ifx-button>
<ifx-button variant="secondary" (click)="toggleButtonFullWidth()">Toggle Full Width</ifx-button>
<ifx-button variant="secondary" (click)="toggleButtonDisabled()">Toggle Disabled</ifx-button>
<ifx-button variant="secondary" (click)="toggleButtonIcon()">Toggle Icon</ifx-button>
<br>
<br>
<span><b>Variant:</b> {{ buttonVariant }} </span><br>
<span><b>Theme:</b> {{ buttonTheme }} </span><br>
<span><b>Size:</b> {{ buttonSize }}</span><br>
<span><b>Full Width:</b> {{ buttonFullWidth }}</span><br>
<span><b>Disabled:</b> {{ buttonDisabled }}</span><br>
<span><b>Icon:</b> {{ buttonIcon }}</span><br>

// examples/wrapper-components/react-vite-js/src/components/Button/button.jsx
import{ useState } from 'react';
import { IfxButton, IfxIcon } from '@infineon/infineon-design-system-react';

function Button() {

  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ["primary", "secondary", "tertiary"];

  const [themeIndex, setThemeIndex] = useState(0);
  const themes = ["default", "danger", "inverse"];

  const [sizeIndex, setSizeIndex] = useState(2);
  const sizes = ["xs", "s", "m", "l"];

  const [fullWidth, setFullWidth] = useState(false);
  const [disabled, setDisabled] = useState(false);

  const [iconIndex, setIconIndex] = useState(0);
  const icons = ["", "fileMpg16"];

  const toggleVariant = () => {
    setVariantIndex((index) => (index + 1) % variants.length);
  }

  const toggleTheme = () => {
    setThemeIndex((index) => (index + 1) % themes.length);
  }

  const toggleSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  }

  const toggleFullWidth = () => {
    setFullWidth(prevFullWidth => !prevFullWidth);
  }

  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  const toggleIcon = () => {
    setIconIndex((index) => (index + 1) % icons.length);
  }

  return (
    <div >
      <h2>Button</h2>
      <IfxButton type="button" aria-label="Button" disabled={disabled} variant={variants[variantIndex]} size={sizes[sizeIndex]} target="_blank" theme={themes[themeIndex]}  full-width={fullWidth}>
        <IfxIcon icon={icons[iconIndex]}></IfxIcon> Button 
      </IfxButton>
      <br />
      <br />
      <h3 style={{textDecoration: "underline"}}>Controls</h3>
      <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
      <IfxButton variant="secondary" onClick={toggleTheme}>Toggle Theme</IfxButton>
      <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
      <IfxButton variant="secondary" onClick={toggleFullWidth}>Toggle Full Width</IfxButton>
      <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
      <IfxButton variant="secondary" onClick={toggleIcon}>Toggle Icon</IfxButton>
      <br />
      <br />
      <span><b>Variant:</b> {variants[variantIndex]}</span><br />
      <span><b>Theme:</b> {themes[themeIndex]}</span><br />
      <span><b>Size:</b> {sizes[sizeIndex]}</span><br />
      <span><b>Full Width:</b> {String(fullWidth)}</span><br />
      <span><b>Disabled:</b> {String(disabled)}</span><br />
      <span><b>Icon:</b> {icons[iconIndex]}</span><br />
    </div>
  )
}

export default Button;
