// examples/vue-example/src/generated/IfxNavbarExample.vue
<script setup lang="ts">

import { IfxNavbar, IfxNavbarItem, IfxNavbarProfile, IfxSearchBar } from '@infineon/infineon-design-system-vue';

const handleNavbarMobileMenuIsOpen = (event: CustomEvent) => {
  console.log('ifxNavbarMobileMenuIsOpen:', event);
  // Add your handler logic here
};

const handleNavItem = (event: CustomEvent) => {
  console.log('ifxNavItem:', event);
  // Add your handler logic here
};

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleOpen = (event: CustomEvent) => {
  console.log('ifxOpen:', event);
  // Add your handler logic here
};

const codeString = `<script setup lang="ts">
const handleNavbarMobileMenuIsOpen = (event: CustomEvent) => {
  console.log('ifxNavbarMobileMenuIsOpen:', event);
  // Add your handler logic here
};

const handleNavItem = (event: CustomEvent) => {
  console.log('ifxNavItem:', event);
  // Add your handler logic here
};

const handleInput = (event: CustomEvent) => {
  console.log('ifxInput:', event);
  // Add your handler logic here
};

const handleOpen = (event: CustomEvent) => {
  console.log('ifxOpen:', event);
  // Add your handler logic here
};
${'</'}script>

<template>
  <div>
    <ifx-navbar
      :show-logo-and-appname="true"
      application-name="Application name"
      :fixed="false"
      logo-href="http://google.com"
      logo-href-target="_self"
      @ifxNavbarMobileMenuIsOpen="handleNavbarMobileMenuIsOpen">
      <ifx-navbar-item
        icon=""
        slot="left-item"
        target="_self"
        href=""
        :hide-on-mobile="true"
        @ifxNavItem="handleNavItem">
        <ifx-navbar-item icon="">
          <ifx-navbar-item>
            <ifx-navbar-item
              href="http://google.com"
              target="_blank">
              Link Layer 3 Nested Item 1
            </ifx-navbar-item>
            <ifx-navbar-item>
              Layer 3 Nested Item 2
            </ifx-navbar-item>
            <ifx-navbar-item>
              Layer 3 Nested Item 3
            </ifx-navbar-item>
            <ifx-navbar-item>
              Layer 3 Nested Item 4
            </ifx-navbar-item>
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Nested Item 3
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Nested Item 4
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Nested Item 5
          </ifx-navbar-item>
        </ifx-navbar-item>
        <ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Item 1
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Item 2
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Item 3
          </ifx-navbar-item>
        </ifx-navbar-item>
        <ifx-navbar-item>
          Nested Item 3
        </ifx-navbar-item>
        <ifx-navbar-item>
          <ifx-navbar-item>
            Nested Item 4
          </ifx-navbar-item>
        </ifx-navbar-item>
      </ifx-navbar-item>
      <ifx-navbar-item
        href=""
        target="_self"
        slot="left-item"
        icon=""
        :show-label="true">
        Menu Item
      </ifx-navbar-item>
      <ifx-navbar-item slot="left-item">
        <ifx-navbar-item>
          Item1
        </ifx-navbar-item>
        <ifx-navbar-item>
          Item2
        </ifx-navbar-item>
      </ifx-navbar-item>
      <ifx-search-bar
        slot="search-bar-left"
        :is-open="false"
        @ifxInput="handleInput"
        @ifxOpen="handleOpen" />
      <ifx-navbar-item
        number-indicator=""
        slot="right-item"
        target="_blank"
        href="http://google.com"
        hide-on-mobile=""
        :show-label="false"
        icon="image-16" />
      <ifx-navbar-item
        :dot-indicator="false"
        slot="right-item"
        hide-on-mobile=""
        :show-label="false"
        icon="image-16" />
      <ifx-navbar-profile
        user-name=""
        slot="right-item"
        image-url=""
        :show-label="true"
        href=""
        target="_self"
        alt="profile image" />
    </ifx-navbar>
  </div>
${'</'}template>`;

</script>

<template>
  <div>
    <ifx-navbar
      :show-logo-and-appname="true"
      application-name="Application name"
      :fixed="false"
      logo-href="http://google.com"
      logo-href-target="_self"
      @ifxNavbarMobileMenuIsOpen="handleNavbarMobileMenuIsOpen">
      <ifx-navbar-item
        icon=""
        slot="left-item"
        target="_self"
        href=""
        :hide-on-mobile="true"
        @ifxNavItem="handleNavItem">
        <ifx-navbar-item icon="">
          <ifx-navbar-item>
            <ifx-navbar-item
              href="http://google.com"
              target="_blank">
              Link Layer 3 Nested Item 1
            </ifx-navbar-item>
            <ifx-navbar-item>
              Layer 3 Nested Item 2
            </ifx-navbar-item>
            <ifx-navbar-item>
              Layer 3 Nested Item 3
            </ifx-navbar-item>
            <ifx-navbar-item>
              Layer 3 Nested Item 4
            </ifx-navbar-item>
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Nested Item 3
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Nested Item 4
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Nested Item 5
          </ifx-navbar-item>
        </ifx-navbar-item>
        <ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Item 1
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Item 2
          </ifx-navbar-item>
          <ifx-navbar-item>
            Layer 2 Item 3
          </ifx-navbar-item>
        </ifx-navbar-item>
        <ifx-navbar-item>
          Nested Item 3
        </ifx-navbar-item>
        <ifx-navbar-item>
          <ifx-navbar-item>
            Nested Item 4
          </ifx-navbar-item>
        </ifx-navbar-item>
      </ifx-navbar-item>
      <ifx-navbar-item
        href=""
        target="_self"
        slot="left-item"
        icon=""
        :show-label="true">
        Menu Item
      </ifx-navbar-item>
      <ifx-navbar-item slot="left-item">
        <ifx-navbar-item>
          Item1
        </ifx-navbar-item>
        <ifx-navbar-item>
          Item2
        </ifx-navbar-item>
      </ifx-navbar-item>
      <ifx-search-bar
        slot="search-bar-left"
        :is-open="false"
        @ifxInput="handleInput"
        @ifxOpen="handleOpen" />
      <ifx-navbar-item
        number-indicator=""
        slot="right-item"
        target="_blank"
        href="http://google.com"
        hide-on-mobile=""
        :show-label="false"
        icon="image-16" />
      <ifx-navbar-item
        :dot-indicator="false"
        slot="right-item"
        hide-on-mobile=""
        :show-label="false"
        icon="image-16" />
      <ifx-navbar-profile
        user-name=""
        slot="right-item"
        image-url=""
        :show-label="true"
        href=""
        target="_self"
        alt="profile image" />
    </ifx-navbar>
    <details class="code-details">
      <summary>View Code</summary>
      <pre><code class="language-markup">{{ codeString }}</code></pre>
    </details>
  </div>
</template>

// examples/angular-standalone-example/src/app/generated/ifx-navbar-example/ifx-navbar-example.ts
import { IfxNavbar, IfxNavbarItem, IfxNavbarProfile, IfxSearchBar } from '@infineon/infineon-design-system-angular/standalone';
import { Component } from '@angular/core';

@Component({
  selector: 'app-ifx-navbar-example',
  imports: [ IfxNavbar, IfxNavbarItem, IfxNavbarProfile, IfxSearchBar ],
  templateUrl: './ifx-navbar-example.html',
	styleUrl: './ifx-navbar-example.scss'
})
export class IfxNavbarExample {
  protected readonly tsCode = `import { IfxNavbar, IfxNavbarItem, IfxNavbarProfile, IfxSearchBar } from &#039;@infineon/infineon-design-system-angular/standalone&#039;;
import { Component } from &#039;@angular/core&#039;;

@Component({
  selector: &#039;app-ifx-navbar-example&#039;,
  imports: [ IfxNavbar, IfxNavbarItem, IfxNavbarProfile, IfxSearchBar ],
  templateUrl: &#039;./ifx-navbar-example.html&#039;,
	styleUrl: &#039;./ifx-navbar-example.scss&#039;
})
export class IfxNavbarExample {
  protected handleNavbarMobileMenuIsOpen(event: CustomEvent) {
    console.log(&#039;ifxNavbarMobileMenuIsOpen:&#039;, event);
    // Add your handler logic here
  }

  protected handleNavItem(event: CustomEvent) {
    console.log(&#039;ifxNavItem:&#039;, event);
    // Add your handler logic here
  }

  protected handleInput(event: CustomEvent) {
    console.log(&#039;ifxInput:&#039;, event);
    // Add your handler logic here
  }

  protected handleOpen(event: CustomEvent) {
    console.log(&#039;ifxOpen:&#039;, event);
    // Add your handler logic here
  }
}`;
  protected readonly htmlCode = `  &lt;ifx-navbar
    [showLogoAndAppname]=&quot;true&quot;
    application-name=&quot;Application name&quot;
    [fixed]=&quot;false&quot;
    logo-href=&quot;http://google.com&quot;
    logo-href-target=&quot;_self&quot;&gt;
    &lt;ifx-navbar-item
      icon=&quot;&quot;
      slot=&quot;left-item&quot;
      target=&quot;_self&quot;
      href=&quot;&quot;
      [hideOnMobile]=&quot;true&quot;
      (ifxNavbarMobileMenuIsOpen)=&quot;handleNavbarMobileMenuIsOpen(\$any(\$event))&quot;
      (ifxNavItem)=&quot;handleNavItem(\$any(\$event))&quot;
      (ifxInput)=&quot;handleInput(\$any(\$event))&quot;
      (ifxOpen)=&quot;handleOpen(\$any(\$event))&quot;&gt;
      &lt;ifx-navbar-item icon=&quot;&quot;&gt;
        &lt;ifx-navbar-item&gt;
          &lt;ifx-navbar-item
            href=&quot;http://google.com&quot;
            target=&quot;_blank&quot;&gt;Link Layer 3 Nested Item 1&lt;/ifx-navbar-item&gt;
          &lt;ifx-navbar-item&gt;Layer 3 Nested Item 2&lt;/ifx-navbar-item&gt;
          &lt;ifx-navbar-item&gt;Layer 3 Nested Item 3&lt;/ifx-navbar-item&gt;
          &lt;ifx-navbar-item&gt;Layer 3 Nested Item 4&lt;/ifx-navbar-item&gt;
        &lt;/ifx-navbar-item&gt;
        &lt;ifx-navbar-item&gt;Layer 2 Nested Item 3&lt;/ifx-navbar-item&gt;
        &lt;ifx-navbar-item&gt;Layer 2 Nested Item 4&lt;/ifx-navbar-item&gt;
        &lt;ifx-navbar-item&gt;Layer 2 Nested Item 5&lt;/ifx-navbar-item&gt;
      &lt;/ifx-navbar-item&gt;
      &lt;ifx-navbar-item&gt;
        &lt;ifx-navbar-item&gt;Layer 2 Item 1&lt;/ifx-navbar-item&gt;
        &lt;ifx-navbar-item&gt;Layer 2 Item 2&lt;/ifx-navbar-item&gt;
        &lt;ifx-navbar-item&gt;Layer 2 Item 3&lt;/ifx-navbar-item&gt;
      &lt;/ifx-navbar-item&gt;
      &lt;ifx-navbar-item&gt;Nested Item 3&lt;/ifx-navbar-item&gt;
      &lt;ifx-navbar-item&gt;
        &lt;ifx-navbar-item&gt;Nested Item 4&lt;/ifx-navbar-item&gt;
      &lt;/ifx-navbar-item&gt;
    &lt;/ifx-navbar-item&gt;
    &lt;ifx-navbar-item
      href=&quot;&quot;
      target=&quot;_self&quot;
      slot=&quot;left-item&quot;
      icon=&quot;&quot;
      [showLabel]=&quot;true&quot;&gt;Menu Item&lt;/ifx-navbar-item&gt;
    &lt;ifx-navbar-item slot=&quot;left-item&quot;&gt;
      &lt;ifx-navbar-item&gt;Item1&lt;/ifx-navbar-item&gt;
      &lt;ifx-navbar-item&gt;Item2&lt;/ifx-navbar-item&gt;
    &lt;/ifx-navbar-item&gt;
    &lt;ifx-search-bar slot=&quot;search-bar-left&quot;&gt;&lt;/ifx-search-bar&gt;
    &lt;ifx-navbar-item
      number-indicator=&quot;&quot;
      slot=&quot;right-item&quot;
      target=&quot;_blank&quot;
      href=&quot;http://google.com&quot;
      [hideOnMobile]=&quot;true&quot;
      [showLabel]=&quot;false&quot;
      icon=&quot;image-16&quot;&gt;&lt;/ifx-navbar-item&gt;
    &lt;ifx-navbar-item
      [dotIndicator]=&quot;false&quot;
      slot=&quot;right-item&quot;
      [hideOnMobile]=&quot;true&quot;
      [showLabel]=&quot;false&quot;
      icon=&quot;image-16&quot;&gt;&lt;/ifx-navbar-item&gt;
    &lt;ifx-navbar-profile
      user-name=&quot;&quot;
      slot=&quot;right-item&quot;
      image-url=&quot;&quot;
      [showLabel]=&quot;true&quot;
      href=&quot;&quot;
      target=&quot;_self&quot;
      alt=&quot;profile image&quot;
      (ifxNavbarMobileMenuIsOpen)=&quot;handleNavbarMobileMenuIsOpen(\$any(\$event))&quot;
      (ifxNavItem)=&quot;handleNavItem(\$any(\$event))&quot;
      (ifxInput)=&quot;handleInput(\$any(\$event))&quot;
      (ifxOpen)=&quot;handleOpen(\$any(\$event))&quot;&gt;&lt;/ifx-navbar-profile&gt;
  &lt;/ifx-navbar&gt;`;

  protected handleNavbarMobileMenuIsOpen(event: CustomEvent) {
    console.log('ifxNavbarMobileMenuIsOpen:', event);
    // Add your handler logic here
  }

  protected handleNavItem(event: CustomEvent) {
    console.log('ifxNavItem:', event);
    // Add your handler logic here
  }

  protected handleInput(event: CustomEvent) {
    console.log('ifxInput:', event);
    // Add your handler logic here
  }

  protected handleOpen(event: CustomEvent) {
    console.log('ifxOpen:', event);
    // Add your handler logic here
  }
}
