// examples/wrapper-components/react-javascript/src/components/Breadcrumb/Breadcrumb.js
import React from 'react';
import { IfxBreadcrumb, IfxBreadcrumbItem, IfxBreadcrumbItemLabel } from '@infineon/infineon-design-system-react';


function Breadcrumb() {
    return (
        <div>
            <IfxBreadcrumb>
                <IfxBreadcrumbItem>
                    <IfxBreadcrumbItemLabel slot='label' icon='share12'>Breadcrumb1</IfxBreadcrumbItemLabel>
                        <ifxdropdown-menu>
                            <ifx-dropdown-item url="http://google.com">Google</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://bing.com">Bing</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://yahoo.com">Yahoo</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://naver.com">Naver</ifx-dropdown-item>
                        </ifxdropdown-menu>           
                </IfxBreadcrumbItem>

                <IfxBreadcrumbItem>
                    <IfxBreadcrumbItemLabel slot='label' icon='share12'>Breadcrumb2</IfxBreadcrumbItemLabel>
                        <ifxdropdown-menu>
                            <ifx-dropdown-item url="http://google.com">Google</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://bing.com">Bing</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://yahoo.com">Yahoo</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://naver.com">Naver</ifx-dropdown-item>
                        </ifxdropdown-menu>  
                </IfxBreadcrumbItem> 

                <IfxBreadcrumbItem>
                    <IfxBreadcrumbItemLabel slot='label' icon='share12'>Breadcrumb3aaaaaaaa</IfxBreadcrumbItemLabel>
                        <ifxdropdown-menu>
                            <ifx-dropdown-item url="http://google.com">Google</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://bing.com">Bing</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://yahoo.com">Yahoo</ifx-dropdown-item>
                            <ifx-dropdown-item url="http://naver.com">Naver</ifx-dropdown-item>
                        </ifxdropdown-menu>  
                </IfxBreadcrumbItem>
            </IfxBreadcrumb>
        </div>
    );
}

export default Breadcrumb;

// packages/components-angular/projects/my-app/src/app/components/breadcrumb/breadcrumb.component.ts
import { Component } from '@angular/core';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-breadcrumb',
  standalone: true,
  imports: [
    ComponentLibraryModule
  ],
  templateUrl: './breadcrumb.component.html',
  styleUrl: './breadcrumb.component.scss'
})
export class BreadcrumbComponent {

}

<h2>Breadcrumb</h2>
  <div>
    <ifx-breadcrumb>
      <ifx-breadcrumb-item>
        <ifx-breadcrumb-item-label slot="label" icon="">Breadcrumb 1</ifx-breadcrumb-item-label>
        <ifx-dropdown-menu>
          <ifx-dropdown-item url="http://google.com">Google</ifx-dropdown-item>
          <ifx-dropdown-item url="http://bing.com">Bing</ifx-dropdown-item>
          <ifx-dropdown-item url="http://yahoo.com">Yahoo</ifx-dropdown-item>
          <ifx-dropdown-item url="http://naver.com">Naver</ifx-dropdown-item>
        </ifx-dropdown-menu>
      </ifx-breadcrumb-item>

      <ifx-breadcrumb-item>
        <ifx-breadcrumb-item-label slot="label" icon="">Breadcrumb 2</ifx-breadcrumb-item-label>
        <ifx-dropdown-menu>
          <ifx-dropdown-item url="http://google.com">Google</ifx-dropdown-item>
          <ifx-dropdown-item url="http://bing.com">Bing</ifx-dropdown-item>
          <ifx-dropdown-item url="http://yahoo.com">Yahoo</ifx-dropdown-item>
          <ifx-dropdown-item url="http://naver.com">Naver</ifx-dropdown-item>
        </ifx-dropdown-menu>
      </ifx-breadcrumb-item>

      <ifx-breadcrumb-item>
        <ifx-breadcrumb-item-label slot="label" icon="chipAi16" url="http://google.com">Breadcrumb 3</ifx-breadcrumb-item-label>
      </ifx-breadcrumb-item>
    </ifx-breadcrumb>
  </div>
