// examples/wrapper-components/vue-javascript/src/components/RadioButtonGroup.vue

<template>
  <div>
    <h2>Radio Button Group</h2>
    <ifx-radio-button-group alignment="vertical" show-group-label="false" group-label-text="Group Label" show-caption="false" caption-text="Caption text, description, error notification" show-caption-icon="false">
        <ifx-radio-button value="0" disabled="false" checked="false" size="m" error="false">Option 0</ifx-radio-button>
        <ifx-radio-button value="1" size="m">Option 1</ifx-radio-button>
        <ifx-radio-button value="2" size="m">Option 2</ifx-radio-button>
    </ifx-radio-button-group>
    <br />
    <br />
  </div>
</template>

<script setup>


</script>

// examples/wrapper-components/react-vite-js/src/components/RadioButtonGroup/RadioButtonGroup.jsx
import { IfxRadioButtonGroup, IfxRadioButton } from '@infineon/infineon-design-system-react';

function RadioButtonGroup() {

  return (
    <div>
      <IfxRadioButtonGroup alignment="vertical" show-group-label="true" group-label-text="Group Label" show-caption="true" caption-text="Caption text, description, error notification" show-caption-icon="true">
          <IfxRadioButton value="0" disabled="false" checked="false" size="m" error="false">Option 0</IfxRadioButton>
          <IfxRadioButton value="1" disabled="false" checked="false" size="m" error="false">Option 1</IfxRadioButton>
          <IfxRadioButton value="2" disabled="false" checked="false" size="m" error="false">Option 2</IfxRadioButton>
          <IfxRadioButton value="3" disabled="false" checked="false" size="m" error="false">Option 3</IfxRadioButton>
      </IfxRadioButtonGroup>
    </div>
  );
}

export default RadioButtonGroup;
