// examples/wrapper-components/vue-javascript/src/components/Modal.vue


<template>
  <div>
    <h2>Modal</h2>
    <div>
      <ifx-modal ref="modalRef" caption=" Modal Title" variant="default" close-on-overlay-click="false">
        <div slot="content">
          <span>Hello. Welcome. What a pleasure it is to have you.</span>
        </div>
        <div slot="buttons">
          <ifx-button variant="secondary" @click="handleModalBtnClick()">Console output</ifx-button>
          <ifx-button @click="handleCloseModal()">Close</ifx-button>
        </div>
      </ifx-modal>
      <ifx-button @click="handleOpenModal()">Open Modal</ifx-button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
const modalRef = ref();

const modal = computed(() => {
  return modalRef.value;
});

const handleModalBtnClick = () => {
  console.log("modal button clicked")
};

const handleCloseModal = () => {
  if (modal) {
    modal.value.close();
  }
};

const handleOpenModal = () => {
  if (modal) {
    modal.value.open();
  }
};


</script>

// examples/wrapper-components/react-typescript/src/components/Modal/Modal.tsx
import { IfxModal, IfxButton } from '@infineon/infineon-design-system-react';
import { useRef } from 'react';

function Modal() {
  const modalRef = useRef();

  const handleCloseModal = () => {
    modalRef.current.close();
  };

  const handleModalBtnClick = () => {
    console.log("modal button clicked")
  };


  return (
    <div>
      <IfxModal ref={modalRef} caption="Modal Title" variant="default" close-on-overlay-click="false">
        <div slot="content">
          <span>Hello. Welcome. What a pleasure it is to have you.</span>
        </div>
        <div slot="buttons">
          <IfxButton variant="secondary" onClick={handleModalBtnClick}>Console output</IfxButton>
          <IfxButton onClick={handleCloseModal}>Close</IfxButton>
        </div>
      </IfxModal>
      <ifx-button onClick={() => modalRef.current.open()}>Open Modal</ifx-button>
    </div>
  );
}

export default Modal;
