// examples/wrapper-components/vue-javascript/src/components/Chip.vue
<template>
  <div class="component">
    <h2>Chip</h2>
    <ifx-chip placeholder="Label" size="large" variant="multi" read-only="false">
      <ifx-chip-item value="Item Value 0" selected="true">Item Label 0</ifx-chip-item>
      <ifx-chip-item value="Item Value 1">Item Label 1</ifx-chip-item>
      <ifx-chip-item value="Item Value 2">Item Label 2</ifx-chip-item>
      <ifx-chip-item value="Item Value 3">Item Label 3</ifx-chip-item>
    </ifx-chip>
    <br />
    <br />
  </div>
</template>

// examples/wrapper-components/react-javascript/src/components/Chip/Chip.js

import React from 'react';

import { IfxChip, IfxChipItem } from '@infineon/infineon-design-system-react';

function Chip() {

  return (
    <div>
      <IfxChip size='small' variant='multi' placeholder='Label'>
          <IfxChipItem value='O1'> Option 1 </IfxChipItem>
          <IfxChipItem value='O2'> Option 2 </IfxChipItem>
          <IfxChipItem value='O3'> Option 3 </IfxChipItem>
          <IfxChipItem value='O4'> Option 4 </IfxChipItem>
      </IfxChip>
      <IfxChip placeholder='Label'>
          <IfxChipItem value='O1'> Option 1 </IfxChipItem>
          <IfxChipItem value='O2'> Option 2 </IfxChipItem>
          <IfxChipItem value='O3'> Option 3 </IfxChipItem>
          <IfxChipItem value='O4'> Option 4 </IfxChipItem>
      </IfxChip>
    </div>
  );
}

export default Chip;
