// examples/wrapper-components/vue-typescript/src/components/Checkbox.vue
<template>
  <div class="app">
    <h2>Checkbox</h2>
    <h3>Using v-model</h3>

    <form @submit.prevent="handleSubmit">
      <ifx-checkbox :disabled="disabled" v-model="value" :error="error" name="name"
        @ifxChange="handleIfxChange">label</ifx-checkbox>
      <br />

      <ifx-button type="submit">Submit</ifx-button>
    </form>
    <br />
    <div>
      <ifx-button variant="outline" @click="toggleDisabled">Toggle Disabled</ifx-button>

      <ifx-button variant="outline" @click="toggleError">Toggle Error</ifx-button>

      <ifx-button variant="outline" @click="toggleValue">Toggle Value</ifx-button>

    </div>
    <br />
    <span>Disabled: {{ disabled }} </span>
    <span>Error: {{ error }} </span>
    <span>Value: {{ value }}</span>
    <br />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const disabled = ref(false)
const value = ref(false)
const error = ref(false)

const handleIfxChange = (e: CustomEvent) => {
  console.log('ifxChange event emitted with value:', e.detail);
  value.value = e.detail;
}

const handleSubmit = () => {
  console.log('Form submitted. Checkbox value:', value.value);
}

const toggleDisabled = () => {
  disabled.value = !disabled.value;
}

const toggleError = () => {
  error.value = !error.value;
}

const toggleValue = () => {
  value.value = !value.value;
}
</script>

<style scoped>
.app {
  text-align: center;
  flex-direction: column;
  display: flex;
  align-items: center;
}
</style>

// examples/wrapper-components/react-javascript/src/components/Checkbox/Checkbox.js

import React, { useState } from 'react';

import { IfxCheckbox, IfxButton } from '@infineon/infineon-design-system-react';

function App() {
  const [disabled, setDisabled] = useState(false);
  const [value, setValue] = useState(false);
  const [error, setError] = useState(false);

  const handleIfxChange = (e) => {
    console.log('ifxChange event emitted with value:', e.detail);
    setValue(e.detail);
  }

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log('Form submitted. Checkbox value:', value);
  }

  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  const toggleError = () => {
    setError(prevError => !prevError);
  }

  const toggleValue = () => {
    setValue(prevValue => !prevValue);
  }

  return (
    <div>

      <form onSubmit={handleSubmit}>
        <IfxCheckbox disabled={disabled} value={value} error={error} name="name"
          onIfxChange={handleIfxChange}>label</IfxCheckbox>
        <br />

        <IfxButton type="submit">Submit</IfxButton>
      </form>
      <br />
      <div>
        <IfxButton variant="outline" onClick={toggleDisabled}>Toggle Disabled</IfxButton>

        <IfxButton variant="outline" onClick={toggleError}>Toggle Error</IfxButton>

        <IfxButton variant="outline" onClick={toggleValue}>Toggle Value</IfxButton>

      </div>
      <br />
      <span>Disabled: {String(disabled)} </span>
      <span>Error: {String(error)} </span>
      <span>Value: {String(value)}</span>
      <br />
    </div>
  );
}

export default App;
