// examples/wrapper-components/react-vite-js/src/components/SingleSelect/SingleSelect.jsx
import { useState } from 'react';
import { IfxSelect, IfxButton } from '@infineon/infineon-design-system-react';

function SingleSelect() {
  const [sizeIndex, setSizeIndex] = useState(1);
  const sizes = ['s', 'm'];

  const [disabled, setDisabled] = useState(false);
  const [required, setRequired] = useState(true);
  const [error, setError] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [showClearButton, setShowClearButton] = useState(false);

  const toggleSize = () => {
    setSizeIndex(index => (index + 1) % sizes.length);
  };

  const toggleDisabled = () => {
    setDisabled(prev => !prev);
  };

  const toggleRequired = () => {
    setRequired(prev => !prev);
  };

  const toggleError = () => {
    setError(prev => !prev);
  };

  const toggleShowSearch = () => {
    setShowSearch(prev => !prev);
  };

  const toggleShowClearButton = () => {
    setShowClearButton(prev => !prev);
  };

  return (
    <div className="component">
      <h2>Single Select</h2>

      <IfxSelect
        size={sizes[sizeIndex]}
        placeholder="true"
        show-clear-button={showClearButton}
        show-search={showSearch}
        search-placeholder-value="Search..."
        disabled={disabled}
        required={required}
        error={error}
        label="Label"
        caption="Caption"
        placeholder-value="Placeholder"
        options='[{"value":"a","label":"option a","selected":false}, {"value":"b","label":"option b","selected":false}, {"value":"c","label":"option c","selected":false}]'>
      </IfxSelect>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size</IfxButton>
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={toggleRequired}>Toggle Required</IfxButton>
        <IfxButton variant="secondary" onClick={toggleError}>Toggle Error</IfxButton>
        <IfxButton variant="secondary" onClick={toggleShowSearch}>Toggle Search</IfxButton>
        <IfxButton variant="secondary" onClick={toggleShowClearButton}>Toggle Clear Button</IfxButton>
      </div>
      <br />
      
      <div class="state">
        <div><b>Size:</b> {sizes[sizeIndex]}</div>
        <div><b>Disabled:</b> {String(disabled)}</div>
        <div><b>Required:</b> {String(required)}</div>
        <div><b>Error:</b> {String(error)}</div>
        <div><b>Show Search:</b> {String(showSearch)}</div>
        <div><b>Show Clear Button:</b> {String(showClearButton)}</div>
      </div>
    </div>
  );
}

export default SingleSelect;

// packages/components-angular/projects/my-app/src/app/components/single-select/single-select.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ComponentLibraryModule } from '@infineon/infineon-design-system-angular';

@Component({
  selector: 'app-single-select',
  standalone: true,
  imports: [
    ComponentLibraryModule,
    CommonModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './single-select.component.html',
  styleUrl: './single-select.component.scss'
})
export class SingleSelectComponent {
  disabled = false;
  required = true;
  error = false;
  showSearch = true;
  showClearButton = false;

  sizes = ['s', 'm'];
  sizeIndex = 1;
  size = this.sizes[this.sizeIndex];

  toggleDisabled() {
    this.disabled = !this.disabled;
  }

  toggleRequired() {
    this.required = !this.required;
  }

  toggleError() {
    this.error = !this.error;
  }

  toggleShowSearch() {
    this.showSearch = !this.showSearch;
  }

  toggleShowClearButton() {
    this.showClearButton = !this.showClearButton;
  }

  toggleSize() {
    this.sizeIndex = (this.sizeIndex + 1) % this.sizes.length;
    this.size = this.sizes[this.sizeIndex];
  }
}
<h2>Single Select</h2>

<ifx-select [size]="size" placeholder="true" [showClearButton]="showClearButton"
  [showSearch]="showSearch" search-placeholder-value="Search..." [disabled]="disabled"
  [required]="required" [error]="error" label="Label" caption="Caption" placeholder-value="Placeholder"
  options='[{"value":"a","label":"option a","selected":false}, {"value":"b","label":"option b","selected":false}, {"value":"c","label":"option c","selected":false}]'>
</ifx-select>
<br />
<br />

<h3 class="controls-title">Controls</h3>
<div class="controls">
  <ifx-button variant="secondary" (click)="toggleDisabled()">Toggle Disabled</ifx-button>
  <ifx-button variant="secondary" (click)="toggleRequired()">Toggle Required</ifx-button>
  <ifx-button variant="secondary" (click)="toggleError()">Toggle Error</ifx-button>
  <ifx-button variant="secondary" (click)="toggleShowSearch()">Toggle Search</ifx-button>
  <ifx-button variant="secondary" (click)="toggleShowClearButton()">Toggle Clear Button</ifx-button>
  <ifx-button variant="secondary" (click)="toggleSize()">Toggle Size</ifx-button>
</div>
<br />

<div class="state">
  <div><b>Disabled:</b> {{ disabled }}</div>
  <div><b>Required:</b> {{ required }}</div>
  <div><b>Error:</b> {{ error }}</div>
  <div><b>Show Search:</b> {{ showSearch }}</div>
  <div><b>Show Clear Button:</b> {{ showClearButton }}</div>
  <div><b>Size:</b> {{ size }}</div>
</div>
