// examples/wrapper-components/vue-javascript/src/components/Dropdown.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const sizes = ["m", "s"];
const sizeIndex = ref(0);
const size = computed(() => sizes[sizeIndex.value]);

const variants = ["primary", "secondary", "tertiary"];
const variantIndex = ref(0);
const variant = computed(() => variants[variantIndex.value]);

const placements = ["bottom-start", "auto", "auto-start", "auto-end", "top", "top-start", "top-end", "bottom", "bottom-end", "right", "right-start", "right-end", "left", "left-start", "left-end"];
const placementIndex = ref(0);
const placement = computed(() => placements[placementIndex.value]);

const disabled = ref(false);
const noCloseOnOutsideClick = ref(false);
const noCloseOnMenuClick = ref(false);

function toggleSize() {
  sizeIndex.value = (sizeIndex.value + 1) % sizes.length;
}

function toggleVariant() {
  variantIndex.value = (variantIndex.value + 1) % variants.length;
}

function togglePlacement() {
  placementIndex.value = (placementIndex.value + 1) % placements.length;
}

function toggleDisabled() {
  disabled.value = !disabled.value;
}

function toggleNoCloseOnOutsideClick() {
  noCloseOnOutsideClick.value = !noCloseOnOutsideClick.value;
}

function toggleNoCloseOnMenuClick() {
  noCloseOnMenuClick.value = !noCloseOnMenuClick.value;
}

</script>

<template>
  <div class="component">
    <h2>Dropdown</h2>
    <div>
      <ifx-dropdown :placement="placement" :disabled="disabled" default-open="false"
        :noCloseOnOutsideClick="noCloseOnOutsideClick" :noCloseOnMenuClick="noCloseOnMenuClick"
        no-append-to-body="false">
        <ifx-dropdown-trigger-button :variant="variant">
          Dropdown
        </ifx-dropdown-trigger-button>

        <ifx-dropdown-menu :size="size">
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
          <ifx-dropdown-item icon="c-info-16" target="_self" href="">Menu Item</ifx-dropdown-item>
        </ifx-dropdown-menu>
      </ifx-dropdown>
    </div>
    <br>
    <br>

    <h3 class="controls-title">Controls</h3>
    <div class="controls">
      <ifx-button variant="secondary" @click="toggleDisabled">Toggle Disabled</ifx-button>
      <ifx-button variant="secondary" @click="toggleSize">Toggle Size of Dropdown Items</ifx-button>
      <ifx-button variant="secondary" @click="toggleVariant">Toggle Variant</ifx-button>
      <ifx-button variant="secondary" @click="togglePlacement">Toggle Placement</ifx-button>
      <ifx-button variant="secondary" @click="toggleNoCloseOnOutsideClick">Toggle No Close on Outside Click</ifx-button>
      <ifx-button variant="secondary" @click="toggleNoCloseOnMenuClick">Toggle No Close on Menu Click</ifx-button>
    </div>
    <br>

    <div class="state">
      <div><b>Disabled:</b> {{ disabled }} </div>
      <div><b>Variant:</b> {{ variant }} </div>
      <div><b>Size of dropdown items:</b> {{ size }} </div>
      <div><b>Placement:</b> {{ placement }} </div>
      <div><b>No Close on Outside Click:</b> {{ noCloseOnOutsideClick }} </div>
      <div><b>No Close on Menu Click:</b> {{ noCloseOnMenuClick }} </div>
    </div>
  </div>
</template>

// examples/wrapper-components/react-vite-js/src/components/Dropdown/Dropdown.jsx
import { useState } from 'react';
import { IfxDropdown, IfxDropdownMenu, IfxDropdownItem, IfxDropdownTriggerButton, IfxButton } from '@infineon/infineon-design-system-react';

function Dropdown() {
  const [disabled, setDisabled] = useState(false);
  const [noCloseOnMenuClick, setNoCloseOnMenuClick] = useState(false);
  const [noCloseOnOutsideClick, setNoCloseOnOutsideClick] = useState(false);

  const [sizeIndex, setSizeIndex] = useState(0);
  const sizes = ["m", "s"];

  const [variantIndex, setVariantIndex] = useState(0);
  const variants = ["primary", "secondary", "tertiary"];

  const [placementIndex, setPlacementIndex] = useState(0);
  const placements = ["bottom-start", "auto", "auto-start", "auto-end", "top-start", "top", "top-end", "bottom", "bottom-end", "right-start", "right", "right-end", "left-start", "left", "left-end"];

  const toggleDisabled = () => {
    setDisabled(prevDisabled => !prevDisabled);
  }

  const toggleNoCloseOnOutsideClick = () => {
    setNoCloseOnOutsideClick(prevNoCloseOnOutsideClick => !prevNoCloseOnOutsideClick);
  }

  const toggleNoCloseOnMenuClick = () => {
    setNoCloseOnMenuClick(prevNoCloseOnMenuClick => !prevNoCloseOnMenuClick);
  }

  const toggleSize = () => {
    setSizeIndex((index) => (index + 1) % sizes.length);
  }

  const toggleVariant = () => {
    setVariantIndex((index) => (index + 1) % variants.length);
  }

  const togglePlacement = () => {
    setPlacementIndex((index) => (index + 1) % placements.length);
  }

  return (
    <div className="component">
      <h2>Dropdown</h2>
      <IfxDropdown placement={placements[placementIndex]} disabled={disabled} default-open="false" no-close-on-outside-click={noCloseOnOutsideClick} no-close-on-menu-click={noCloseOnMenuClick} no-append-to-body="false">
        <IfxDropdownTriggerButton variant={variants[variantIndex]}>
          Dropdown
        </IfxDropdownTriggerButton>

        <IfxDropdownMenu size={sizes[sizeIndex]}>
          <IfxDropdownItem icon="c-info-16" target="_self" href="">Menu Item</IfxDropdownItem>
          <IfxDropdownItem icon="c-info-16" target="_self" href="">Menu Item</IfxDropdownItem>
          <IfxDropdownItem icon="c-info-16" target="_self" href="">Menu Item</IfxDropdownItem>
          <IfxDropdownItem icon="c-info-16" target="_self" href="">Menu Item</IfxDropdownItem>
          <IfxDropdownItem icon="c-info-16" target="_self" href="">Menu Item</IfxDropdownItem>
        </IfxDropdownMenu>
      </IfxDropdown>
      <br />
      <br />

      <h3 class="controls-title">Controls</h3>
      <div class="controls">
        <IfxButton variant="secondary" onClick={toggleDisabled}>Toggle Disabled</IfxButton>
        <IfxButton variant="secondary" onClick={toggleSize}>Toggle Size of Dropdown Items</IfxButton>
        <IfxButton variant="secondary" onClick={toggleVariant}>Toggle Variant</IfxButton>
        <IfxButton variant="secondary" onClick={togglePlacement}>Toggle Placement</IfxButton>
        <IfxButton variant="secondary" onClick={toggleNoCloseOnOutsideClick}>Toggle No Close on Outside Click</IfxButton>
        <IfxButton variant="secondary" onClick={toggleNoCloseOnMenuClick}>Toggle No Close on Menu Click</IfxButton>
      </div>
      <br />

      <div class="state">
        <div><b>Disabled:</b> {String(disabled)}</div>
        <div><b>Variant:</b> {variants[variantIndex]}</div>
        <div><b>Size of dropdown items:</b> {sizes[sizeIndex]}</div>
        <div><b>Placement:</b> {placements[placementIndex]}</div>
        <div><b>No Close on Outside Click:</b> {String(noCloseOnOutsideClick)}</div>
        <div><b>No Close on Menu Click:</b> {String(noCloseOnMenuClick)}</div>
      </div>
    </div>
  );
}

export default Dropdown;
